/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bins.CidadeBins;
import bins.PessoaBins;
import bins.RuaBins;
import dao.CidadeDao;
import dao.RuaDao;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCOS
 */
public class PesquisaEndereco extends javax.swing.JFrame {
    DefaultTableModel tmcidade= new DefaultTableModel(null, new String[]{"ID CIDADE","DISTRITO","CIDADE","ESTADO","PAIS"});
    List<CidadeBins> lcidade;
    ListSelectionModel lsmcidade;
    
    DefaultTableModel tmrua= new DefaultTableModel(null, new String[]{"ID RUA","RUA","BAIRRO","CEP"});
    List<RuaBins> lrua;
    ListSelectionModel lsmrua;
    
   int idcidade;
   int idrua; 
   
    public String nome;
    public String apelido;
    public int tipo;
    public int modalidade;
    public String cpf;
    public String inscricao;
    public String telefone;
    public String senha;
    public String lembra;
    public String id;
    public Boolean ativo;
    public int idempresa;
    public String fantasia;
   
    public PesquisaEndereco() {
        initComponents();
        jTtabelacidade.getColumnModel().getColumn(0);
        jTtabelacidade.getColumnModel().getColumn(1);
        jTtabelacidade.getColumnModel().getColumn(2);
        jTtabelacidade.getColumnModel().getColumn(3);
        jTtabelacidade.getColumnModel().getColumn(4);
        
        jTtabelarua.getColumnModel().getColumn(0);
        jTtabelarua.getColumnModel().getColumn(1);
        jTtabelarua.getColumnModel().getColumn(2);
        jTtabelarua.getColumnModel().getColumn(3);
        try {
            jTcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("########")));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Mascara CEP nao Adicionada");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGcidade = new javax.swing.ButtonGroup();
        bGrua = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTtabelacidade = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTtabelarua = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTrua = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTbairro = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jBsalvar = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jBcarregar = new javax.swing.JButton();
        jBnovo = new javax.swing.JButton();
        jTpcidade = new javax.swing.JTextField();
        jTprua = new javax.swing.JTextField();
        jRdistrito = new javax.swing.JRadioButton();
        jRcidade = new javax.swing.JRadioButton();
        jRrua = new javax.swing.JRadioButton();
        jRcep = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTpais = new javax.swing.JTextField();
        jTestado = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTdistrito = new javax.swing.JTextField();
        jTcep = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        jTtabelacidade.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTtabelacidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID CIDADE", "DISTRITO", "CIDADE", "ESTADO", "PAIS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTtabelacidade.getTableHeader().setResizingAllowed(false);
        jTtabelacidade.getTableHeader().setReorderingAllowed(false);
        jTtabelacidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTtabelacidadeMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTtabelacidade);
        jTtabelacidade.getColumnModel().getColumn(0).setResizable(false);
        jTtabelacidade.getColumnModel().getColumn(1).setResizable(false);
        jTtabelacidade.getColumnModel().getColumn(2).setResizable(false);
        jTtabelacidade.getColumnModel().getColumn(3).setResizable(false);
        jTtabelacidade.getColumnModel().getColumn(4).setResizable(false);
        jTtabelacidade.getColumnModel().getColumn(4).setHeaderValue("PAIS");

        jTtabelarua.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTtabelarua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID RUA", "RUA ", "BAIRRO", "CEP"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTtabelarua.getTableHeader().setResizingAllowed(false);
        jTtabelarua.getTableHeader().setReorderingAllowed(false);
        jTtabelarua.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTtabelaruaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTtabelarua);
        jTtabelarua.getColumnModel().getColumn(0).setResizable(false);
        jTtabelarua.getColumnModel().getColumn(1).setResizable(false);
        jTtabelarua.getColumnModel().getColumn(2).setResizable(false);
        jTtabelarua.getColumnModel().getColumn(3).setResizable(false);

        jLabel1.setText("RUA:");

        jLabel2.setText("CIDADE:");

        jTrua.setEditable(false);

        jLabel3.setText("RUA:");

        jTbairro.setEditable(false);

        jLabel4.setText("BAIRRO:");

        jLabel5.setText("CEP:");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBsalvar.setText("SALVAR");
        jBsalvar.setEnabled(false);
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBalterar.setText("ALTERAR");
        jBalterar.setEnabled(false);
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBcarregar.setText("CARREGAR");
        jBcarregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcarregarActionPerformed(evt);
            }
        });

        jBnovo.setText("NOVO");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jBnovo)
                .addGap(37, 37, 37)
                .addComponent(jBsalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jBalterar)
                .addGap(34, 34, 34)
                .addComponent(jBcarregar)
                .addGap(40, 40, 40))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBalterar, jBcarregar, jBnovo, jBsalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBcarregar)
                    .addComponent(jBalterar)
                    .addComponent(jBsalvar)
                    .addComponent(jBnovo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBalterar, jBcarregar, jBnovo, jBsalvar});

        jTpcidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTpcidadeKeyReleased(evt);
            }
        });

        jTprua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTpruaKeyReleased(evt);
            }
        });

        bGcidade.add(jRdistrito);
        jRdistrito.setSelected(true);
        jRdistrito.setText("DISTRITO");
        jRdistrito.setName("distrito"); // NOI18N

        bGcidade.add(jRcidade);
        jRcidade.setText("CIDADE");
        jRcidade.setName("nome"); // NOI18N

        bGrua.add(jRrua);
        jRrua.setSelected(true);
        jRrua.setText("RUA");
        jRrua.setName("nome"); // NOI18N

        bGrua.add(jRcep);
        jRcep.setText("CEP");
        jRcep.setName("cep"); // NOI18N

        jLabel6.setText("PAIS:");

        jLabel7.setText("ESTADO:");

        jTpais.setEditable(false);
        jTpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpaisActionPerformed(evt);
            }
        });

        jTestado.setEditable(false);
        jTestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestadoActionPerformed(evt);
            }
        });

        jLabel8.setText("DISTRITO:");

        jTdistrito.setEditable(false);

        jTcep.setEditable(false);
        jTcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 784, Short.MAX_VALUE)
                            .addComponent(jScrollPane2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTprua, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(47, 47, 47)
                                .addComponent(jRrua)
                                .addGap(43, 43, 43)
                                .addComponent(jRcep)
                                .addGap(0, 271, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTrua, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(73, 73, 73)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jTcep, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTpcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jRdistrito)
                                .addGap(26, 26, 26)
                                .addComponent(jRcidade)
                                .addGap(39, 261, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 129, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTestado, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jTpais, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel7)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTdistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTpcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRdistrito)
                    .addComponent(jRcidade))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTprua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRrua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jRcep))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(820, 692));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTtabelacidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTtabelacidadeMouseClicked
        // TODO add your handling code here:      
        try{
        selecaocidade();
        limparua();
        }catch(NullPointerException ex){
            //JOptionPane.showMessageDialog(null, "Selecione uma Cidade"+ex);
        }
    }//GEN-LAST:event_jTtabelacidadeMouseClicked

    private void jTtabelaruaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTtabelaruaMouseClicked
        // TODO add your handling code here: 
       try{
        limparua();
        selecaorua(lrua);
        idrua=(int) jTtabelarua.getValueAt(jTtabelarua.getSelectedRow(), 0);
        }catch(NullPointerException ex){
           // JOptionPane.showMessageDialog(null, "Nao a Rua\n"+ ex);
        }
        
    }//GEN-LAST:event_jTtabelaruaMouseClicked

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
        abilitado();
        limparua();
        jBsalvar.setEnabled(true);
        jBalterar.setEnabled(false);
        jBcarregar.setEnabled(false);
        jBnovo.setEnabled(false);
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:      
        if(idrua<1){
        cadastrorua();
        desabilitado();
        limparua();
        }else{
        alterarua();
        desabilitado();
        }
    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // TODO add your handling code here:
       /* alterarua();
        desabilitado();*/
        abilitado();
        jBsalvar.setEnabled(true);
        jBalterar.setEnabled(false);
    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBcarregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcarregarActionPerformed
        // TODO add your handling code here:
       Pessoa p=new Pessoa();
       
       p.jTrua.setText(jTrua.getText());
       p.jTbairro.setText(jTbairro.getText());
       p.jTcep.setText(jTcep.getText());
       p.jTcidade.setText(jTdistrito.getText());
       p.jTestado.setText(jTestado.getText());
       p.jTidrua.setText(Integer.toString(idrua));
       p.jTpais.setText(jTpais.getText());
           
        p.jTidpessoa.setText(id);
        p.jTnome.setText(nome);        
        p.jTusuario.setText(apelido);
        p.jCtipo.setSelectedIndex(tipo);
        p.jCmodalidade.setSelectedIndex(modalidade);
        p.jFcpfcnpj.setText(cpf);
        p.jTinscricao.setText(inscricao);
        p.jTtelefone.setText(telefone);
        p.jPsenha.setText(senha);
        p.jTlembra.setText(lembra);
        p.jCativo.setSelected(ativo);
        p.jTfantasia.setText(fantasia);
        p.ativar();
        p.salvarcancelarpesquisaendereco();
       p.setVisible(true);
       PesquisaEndereco.this.setVisible(false);
      
    }//GEN-LAST:event_jBcarregarActionPerformed

    private void jTpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpaisActionPerformed

    private void jTestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTestadoActionPerformed

    private void jTpcidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpcidadeKeyReleased
        // TODO add your handling code here:
        try {
            CidadeDao cd= new CidadeDao();
            lcidade=cd.getLista("%"+jTpcidade.getText()+"%",selecaorbcidade());
            mostrapesquisacidade(lcidade);
        } catch (SQLException ex) {
           // Logger.getLogger(PesquisaEndereco.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jTpcidadeKeyReleased

    private void jTpruaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTpruaKeyReleased
        // TODO add your handling code here:
         try {
            idcidade= (int)jTtabelacidade.getValueAt(jTtabelacidade.getSelectedRow(), 0);
            RuaDao rd= new RuaDao();
            lrua= rd.getPesquisa("%"+jTprua.getText()+"%",selecaorbrua(),idcidade);
            mostrapesquisarua(lrua);
        } catch (SQLException |ArrayIndexOutOfBoundsException|NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Nao a Rua cadastrada nessa Cidade\n"+ex);
        } 
    }//GEN-LAST:event_jTpruaKeyReleased
    public void cadastrorua() {
        if (idcidade > 0) {
            try {
                RuaBins rb = new RuaBins();
                rb.setNome(jTrua.getText());
                rb.setBairro(jTbairro.getText());
                rb.setCep(jTcep.getText());
                rb.setCidade(idcidade);
                RuaDao rd = new RuaDao();
                rd.adiciona(rb);
                jBnovo.setEnabled(true);
                jBalterar.setEnabled(false);
                jBcarregar.setEnabled(true);
                jBsalvar.setEnabled(false);
            } catch (SQLException ex) {
                JOptionPane.showMessageDialog(null, "Rua nao Cadastrada" + ex);
                jBnovo.setEnabled(true);
                jBalterar.setEnabled(false);
                jBcarregar.setEnabled(true);
                jBsalvar.setEnabled(false);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma cidade");
            jBalterar.setEnabled(false);
            jBcarregar.setEnabled(true);
            jBnovo.setEnabled(true);
            jBsalvar.setEnabled(false);
        }
    }
    public void alterarua() {
        try {
            RuaBins rb = new RuaBins();
            rb.setNome(jTrua.getText());
            rb.setBairro(jTbairro.getText());
            rb.setCep(jTcep.getText());
            rb.setCidade(idcidade);
            rb.setId(idrua);
            RuaDao rd = new RuaDao();
            rd.altera(rb);
            jBnovo.setEnabled(true);
            jBalterar.setEnabled(true);
            jBcarregar.setEnabled(true);
            jBsalvar.setEnabled(false);
            JOptionPane.showMessageDialog(null, "Rua Alterada");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Rua nao Alterada" + ex);
            jBnovo.setEnabled(true);
            jBalterar.setEnabled(true);
            jBcarregar.setEnabled(true);
            jBsalvar.setEnabled(false);
        }
    }
    public void limparua(){
        idrua=0;
        jTrua.setText("");
        jTbairro.setText("");
        jTcep.setText("");
    }
    public void selecaorua(List<RuaBins> rb){
        for (int i = 0; i < rb.size(); i++) {
            if (jTtabelarua.getSelectedRow() == i) {
                jTrua.setText(rb.get(i).getNome());
                jTbairro.setText(rb.get(i).getBairro());
                jTcep.setText(rb.get(i).getCep());         
                jBalterar.setEnabled(true);
                jBcarregar.setEnabled(true);
                jBnovo.setEnabled(true);
                jBsalvar.setEnabled(false);
            }
        }
    }
    public void mostraselecaocidade(List<CidadeBins> cb){
        for(int i=0; i< cb.size();i++){
            if(jTtabelacidade.getSelectedRow() == i){
                jTestado.setText(cb.get(i).getEstado());
                jTdistrito.setText(cb.get(i).getDistrito());
                jTpais.setText(cb.get(i).getPais());
            }
        }
     }
    
            
    public void selecaocidade(){      
        try {
            idcidade = (int) jTtabelacidade.getValueAt(jTtabelacidade.getSelectedRow(), 0);
            RuaDao rd = new RuaDao();
            lrua = rd.getLista(idcidade);
            mostrapesquisarua(lrua);
            mostraselecaocidade(lcidade);
        } catch (SQLException ex) {
           // JOptionPane.showMessageDialog(null, ex);
        }
        
    }
    public String selecaorbcidade(){
        if(jRcidade.isSelected()){
            return jRcidade.getName();
        }else{
        return jRdistrito.getName();
        }
    }
    public String selecaorbrua(){
        if(jRrua.isSelected()){
            return jRrua.getName();
            
        }else{
            return jRcep.getName();
        }
    }
    public void mostrapesquisacidade(List<CidadeBins> lcidade){
        DefaultTableModel modelocidade = (DefaultTableModel) jTtabelacidade.getModel(); //CRIA OBJETO MODELO DO TIPO DEFAULTTABLEMODEL
        modelocidade.setNumRows(0);//
        for(int i=0; i<lcidade.size();i++){ //ENQUANTO O RESET DO METODO EXECULTA SQL TIVER DADOS ELE VAI PREENCHER A TABELA
                modelocidade.addRow(new Object[]{lcidade.get(i).getId(),lcidade.get(i).getDistrito(),lcidade.get(i).getNome(),lcidade.get(i).getEstado(),lcidade.get(i).getPais()});                            
            }  
    }
    public void mostrapesquisarua(List<RuaBins> lrua){
        DefaultTableModel modelorua= (DefaultTableModel) jTtabelarua.getModel();
       modelorua.setRowCount(0);
       for(int i=0;i<lrua.size();i++){     
           modelorua.addRow(new Object[]{lrua.get(i).getId(),lrua.get(i).getNome(),lrua.get(i).getBairro(),lrua.get(i).getCep()});
       }
    }
    public void abilitado(){
        jTrua.setEditable(true);
        jTbairro.setEditable(true);
        jTcep.setEditable(true);
    }
     public void desabilitado(){
        jTrua.setEditable(false);
        jTbairro.setEditable(false);
        jTcep.setEditable(false);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisaEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new PesquisaEndereco().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGcidade;
    private javax.swing.ButtonGroup bGrua;
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBcarregar;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRcep;
    private javax.swing.JRadioButton jRcidade;
    private javax.swing.JRadioButton jRdistrito;
    private javax.swing.JRadioButton jRrua;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTbairro;
    private javax.swing.JFormattedTextField jTcep;
    private javax.swing.JTextField jTdistrito;
    private javax.swing.JTextField jTestado;
    private javax.swing.JTextField jTpais;
    private javax.swing.JTextField jTpcidade;
    private javax.swing.JTextField jTprua;
    private javax.swing.JTextField jTrua;
    private javax.swing.JTable jTtabelacidade;
    private javax.swing.JTable jTtabelarua;
    // End of variables declaration//GEN-END:variables
}
