/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bins.CidadeBins;
import Validador.*;
import bancodados.CriaConexao;
import bins.DadosEmpresaBins;
import dao.CidadeDao;
import bins.PessoaBins;
import dao.PessoaDao;
import dao.RuaDao;
import bins.RuaBins;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MARCOS
 */
public class Pessoa extends javax.swing.JFrame {
    PesquisaEndereco pendereco = new PesquisaEndereco();
    
    DefaultTableModel tmppessoa = new DefaultTableModel(null, new String[]{"ID", "NOME", "APELIDO", "CPF_CNPJ", "TELEFONE"});
    List<PessoaBins> lppessoa;
    List<RuaBins> lprua;
    List<CidadeBins> lpcidade;
    ListSelectionModel lsmppessoa;
    
    
//public String nome; 
    /**
     * Creates new form Pessoa
     */
    public Pessoa() {
        initComponents();
        inicializaAtalho();
        jTdpessoa.getColumnModel().getColumn(0).setMaxWidth(60);
        jTdpessoa.getColumnModel().getColumn(1);
        jTdpessoa.getColumnModel().getColumn(2);
        jTdpessoa.getColumnModel().getColumn(3);
        jTdpessoa.getColumnModel().getColumn(4);
        try {
            jTcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null, "Erro mascara cep");
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDppessoa = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jTdpesquisa = new javax.swing.JTextField();
        jRdnome = new javax.swing.JRadioButton();
        jRdapelido = new javax.swing.JRadioButton();
        jRdcpf_cnpj = new javax.swing.JRadioButton();
        jLabel16 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTdpessoa = new javax.swing.JTable();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jTnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTinscricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jCtipo = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jTestado = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTpais = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jBpendereco = new javax.swing.JButton();
        jTcidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTbairro = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTrua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTnumero = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTidrua = new javax.swing.JTextField();
        jTcep = new javax.swing.JFormattedTextField();
        jCmodalidade = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jPsenha = new javax.swing.JPasswordField();
        jLabel14 = new javax.swing.JLabel();
        jTlembra = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTusuario = new javax.swing.JTextField();
        jTtelefone = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jBalterar = new javax.swing.JButton();
        jBnovo = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jBpesquisar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jTidpessoa = new javax.swing.JTextField();
        jCativo = new javax.swing.JCheckBox();
        jFcpfcnpj = new javax.swing.JTextField();
        jTfantasia = new javax.swing.JTextField();

        jDppessoa.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDppessoa.setTitle("PESQUISA");
        jDppessoa.setIconImage(null);
        jDppessoa.setMinimumSize(new java.awt.Dimension(678, 390));
        jDppessoa.setModal(true);
        jDppessoa.setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel3.setMaximumSize(new java.awt.Dimension(645, 32767));
        jPanel3.setMinimumSize(new java.awt.Dimension(645, 73));
        jPanel3.setName(""); // NOI18N

        jTdpesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTdpesquisaKeyReleased(evt);
            }
        });

        buttonGroup1.add(jRdnome);
        jRdnome.setSelected(true);
        jRdnome.setText("RAZAO");
        jRdnome.setName("nome"); // NOI18N

        buttonGroup1.add(jRdapelido);
        jRdapelido.setText("FANTASIA");
        jRdapelido.setName("fantasia"); // NOI18N

        buttonGroup1.add(jRdcpf_cnpj);
        jRdcpf_cnpj.setText("CPF_CNPJ");
        jRdcpf_cnpj.setName("cpf_cnpj"); // NOI18N

        jLabel16.setText("PESQUISA:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTdpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(jRdnome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRdapelido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRdcpf_cnpj)
                .addGap(24, 24, 24))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTdpesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRdnome)
                    .addComponent(jRdapelido)
                    .addComponent(jRdcpf_cnpj)
                    .addComponent(jLabel16))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Uteis/EMPRIMIR32X32.png"))); // NOI18N
        jButton1.setText("IMPRIMIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTdpessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RAZÃO", "FANTASIA", "CPF_CNPJ", "TELEFONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTdpessoa.setMaximumSize(new java.awt.Dimension(645, 0));
        jTdpessoa.getTableHeader().setResizingAllowed(false);
        jTdpessoa.getTableHeader().setReorderingAllowed(false);
        jTdpessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTdpessoaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTdpessoa);

        javax.swing.GroupLayout jDppessoaLayout = new javax.swing.GroupLayout(jDppessoa.getContentPane());
        jDppessoa.getContentPane().setLayout(jDppessoaLayout);
        jDppessoaLayout.setHorizontalGroup(
            jDppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDppessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        jDppessoaLayout.setVerticalGroup(
            jDppessoaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDppessoaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("CADASTRO");
        setResizable(false);

        jLabel1.setText("RAZAO");

        jTnome.setEditable(false);
        jTnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnomeActionPerformed(evt);
            }
        });

        jLabel2.setText("FANTASIA");

        jLabel3.setText("CPF/CNPJ:");

        jLabel4.setText("INSCRIÇÃO:");

        jTinscricao.setEditable(false);
        jTinscricao.setText("ISENTO");

        jLabel5.setText("TIPO:");

        jCtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1_FISICA", "2_JURIDICA" }));
        jCtipo.setToolTipText("");
        jCtipo.setEnabled(false);
        jCtipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCtipoActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "ENDEREÇO", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 0, 14))); // NOI18N

        jTestado.setEditable(false);
        jTestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTestadoActionPerformed(evt);
            }
        });

        jLabel6.setText("RUA:");

        jTpais.setEditable(false);
        jTpais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTpaisActionPerformed(evt);
            }
        });

        jLabel7.setText("BAIRRO:");

        jBpendereco.setText("F1");
        jBpendereco.setEnabled(false);
        jBpendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpenderecoActionPerformed(evt);
            }
        });

        jTcidade.setEditable(false);
        jTcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTcidadeActionPerformed(evt);
            }
        });

        jLabel8.setText("CIDADE:");

        jTbairro.setEditable(false);
        jTbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbairroActionPerformed(evt);
            }
        });

        jLabel9.setText("NUMERO:");

        jTrua.setEditable(false);
        jTrua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTruaActionPerformed(evt);
            }
        });

        jLabel10.setText("ESTADO:");

        jTnumero.setEditable(false);
        jTnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnumeroActionPerformed(evt);
            }
        });

        jLabel11.setText("PAIS:");

        jLabel12.setText("CEP:");

        jTidrua.setEnabled(false);

        jTcep.setEditable(false);
        jTcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTidrua, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBpendereco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jTrua, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel10)
                    .addComponent(jTestado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jTpais, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39))))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTnumero, jTpais});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTbairro, jTcep});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel9)))
                            .addComponent(jTidrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBpendereco)
                            .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTrua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTestado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTpais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTcep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTnumero, jTpais});

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTbairro, jTcep});

        jCmodalidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1_CLIENTE", "2_FORNECEDOR", "3_CLIE_FORN", "4_FUNCIONARIO", "5_FUNC_CLIE" }));
        jCmodalidade.setEnabled(false);
        jCmodalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCmodalidadeActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("ACESSO AO SISTEMA"));

        jPsenha.setEditable(false);
        jPsenha.setText("jPasswordField1");

        jLabel14.setText("SENHA:");

        jTlembra.setEditable(false);

        jLabel15.setText("LEMBRA SENHA:");

        jLabel17.setText("USUARIO:");

        jTusuario.setEditable(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPsenha, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15)
                    .addComponent(jTlembra, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(65, 65, 65))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTlembra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jTtelefone.setEditable(false);

        jLabel13.setText("TELEFONE:");

        jBalterar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBalterar.setText("ALTERAR");
        jBalterar.setEnabled(false);
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBnovo.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBnovo.setText("NOVO");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jBsair.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBsair.setText("SAIR");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        jBsalvar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBsalvar.setText("SALVAR");
        jBsalvar.setEnabled(false);
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBpesquisar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBpesquisar.setText("PESQUISAR");
        jBpesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisarActionPerformed(evt);
            }
        });

        jBcancelar.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jBcancelar.setText("CANCELAR");
        jBcancelar.setEnabled(false);
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jTidpessoa.setEnabled(false);

        jCativo.setSelected(true);
        jCativo.setText("ATIVO");
        jCativo.setEnabled(false);

        jFcpfcnpj.setEditable(false);

        jTfantasia.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFcpfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTinscricao, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCmodalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jTidpessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(8, 8, 8))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                        .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(jLabel2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel13)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCativo)
                                    .addComponent(jTfantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 379, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jBnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jBalterar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jBsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jBcancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBsair, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(jBpesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84))))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTnome, jTtelefone});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTidpessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTfantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jCtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCmodalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCativo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jFcpfcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTinscricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBalterar)
                    .addComponent(jBnovo)
                    .addComponent(jBsair)
                    .addComponent(jBsalvar)
                    .addComponent(jBpesquisar)
                    .addComponent(jBcancelar))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    private void inicializaAtalho(){
        //ATALHO PARA JBENDERECO
        KeyStroke KeyStrokeJBENDERECO = KeyStroke.getKeyStroke(KeyEvent.VK_F1,0);
        String actionNameJBENDERECO= "TECLA_F1";
        InputMap InputMapJBENDERECO= jBpendereco.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        InputMapJBENDERECO.put(KeyStrokeJBENDERECO, actionNameJBENDERECO);
        ActionMap actionMapJBENDERECO=jBpendereco.getActionMap();
        actionMapJBENDERECO.put(actionNameJBENDERECO, acaoJBpendereco);
    }
    //ACAO DO BOTAO JBPENDERECO
    Action acaoJBpendereco= new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            jBpendereco.doClick();
            
        }
    };
    public void ativar(){
        jTnome.setEditable(true);
        
        jFcpfcnpj.setEditable(true);
        jTinscricao.setEditable(true);
        jTtelefone.setEditable(true);
        jTnumero.setEditable(true);
        jCmodalidade.setEnabled(true);
        jCativo.setEnabled(true);
        jCtipo.setEnabled(true);
        jTfantasia.setEditable(true);
       
    }
    public void desativa(){
        jTnome.setEditable(false);
        jTusuario.setEditable(false);
        jFcpfcnpj.setEditable(false);
        jTinscricao.setEditable(false);
        jTtelefone.setEditable(false);
        jTnumero.setEditable(false);
        jPsenha.setEditable(false);
        jTlembra.setEditable(false);
        jCativo.setEnabled(false);
        jCmodalidade.setEnabled(false);
        jCtipo.setEnabled(false);
        jTfantasia.setEditable(false);
    }
    public void limpa(){
        jTnome.setText("");
        jTusuario.setText("");
        jFcpfcnpj.setText("");
        jTinscricao.setText("");
        jTtelefone.setText("");
        jTrua.setText("");
        jTnumero.setText("");
        jPsenha.setText("");
        jTlembra.setText("");
        jTbairro.setText("");
        jTcidade.setText("");
        jTestado.setText("");
        jTpais.setText("");
        jTcep.setText("");
        jTidpessoa.setText("");
        jTidrua.setText("");
        jCtipo.setSelectedIndex(0);
        jCmodalidade.setSelectedIndex(0);
        jCativo.setSelected(true);
        jTfantasia.setText("");
    }
    public int verificaAtivo(Boolean b){
        if(b==true){
            return 0;
        }else{
            return 1;
        }
    }
    public Boolean converteAtivo(int a){
        if(a==0){
             
            return true;
        }else{
            return false;
        }
    }
    public void cadastro(){
        try {
            PessoaBins pb = new PessoaBins();
            DadosEmpresaBins de= new DadosEmpresaBins();
            pb.setNome(jTnome.getText());
            pb.setApelido(jTusuario.getText());
            pb.setTipo(jCtipo.getSelectedIndex() + 1);
            pb.setModalidade(jCmodalidade.getSelectedIndex() + 1);
            pb.setCpf_cnpj(jFcpfcnpj.getText());
            pb.setInscricao(jTinscricao.getText());
            pb.setTelefone(jTtelefone.getText());
            pb.setRua(Integer.parseInt(jTidrua.getText()));
            pb.setNumero(jTnumero.getText());
            pb.setSenha(jPsenha.getText());
            pb.setLembra(jTlembra.getText());
            pb.setAtivo(verificaAtivo(jCativo.isSelected()));
            pb.setEmpresa(de.getId());
            pb.setFantasia(jTfantasia.getText());
            PessoaDao pd = new PessoaDao();
            pd.adiciona(pb);
            desativa();
            JOptionPane.showMessageDialog(null, "Registro Cadastrado");
            
        } catch (SQLException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }
    private void jTnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnomeActionPerformed

    private void jTestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTestadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTestadoActionPerformed

    private void jTpaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTpaisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTpaisActionPerformed

    private void jTcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTcidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTcidadeActionPerformed

    private void jTbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbairroActionPerformed

    private void jTruaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTruaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTruaActionPerformed

    private void jTnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnumeroActionPerformed

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
        jTnome.requestFocus();
        ativar();
        limpa();
        salvarcancelarpesquisaendereco();
        jTinscricao.setText("ISENTO");
    }//GEN-LAST:event_jBnovoActionPerformed
public void salvarcancelarpesquisaendereco(){
    jBsalvar.setEnabled(true);
    jBcancelar.setEnabled(true);
    jBnovo.setEnabled(false);
    jBpesquisar.setEnabled(false);
    jBsair.setEnabled(false);
    jBalterar.setEnabled(false);
    jBpendereco.setEnabled(true);
    
}

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        //cpf vcpf = new cpf();
       // cnpj vcnpj= new cnpj();
        if (cpf.isCPF(jFcpfcnpj.getText())) {
            if ("".equals(jTidpessoa.getText())) {
                cadastro();
                novosairpesquisa();
                desativa();
            } else {
                alterapessoa();
                novosairpesquisa();
                desativa();
            }
        }else
        if(cnpj.isCNPJ(jFcpfcnpj.getText())){
           if ("".equals(jTidpessoa.getText())) {
                cadastro();
                novosairpesquisa();
                desativa();
            } else {
                alterapessoa();
                novosairpesquisa();
                desativa();
            } 
        }else{
        JOptionPane.showMessageDialog(null, "CPF ou CNPJ invalido");
        }
    }//GEN-LAST:event_jBsalvarActionPerformed
public void novosairpesquisa(){
    jBalterar.setEnabled(false);
    jBcancelar.setEnabled(false);
    jBnovo.setEnabled(true);
    jBpendereco.setEnabled(false);
    jBpesquisar.setEnabled(true);
    jBsair.setEnabled(true);
    jBsalvar.setEnabled(false);         
}
public void alterarnovoacancelarpesquisa(){
    jBalterar.setEnabled(true);
    jBcancelar.setEnabled(true);
    jBnovo.setEnabled(true);
    jBpendereco.setEnabled(false);
    jBpesquisar.setEnabled(true);
    jBsair.setEnabled(false);
    jBsalvar.setEnabled(false); 
}
    private void jCtipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCtipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCtipoActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        // TODO add your handling code here:
        Pessoa.this.dispose(); 
        limpa();
        desativa();
       // novosairpesquisa();
    }//GEN-LAST:event_jBsairActionPerformed
    
    private void jBpenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpenderecoActionPerformed
        // TODO add your handling code here:
       if(!pendereco.isVisible()){        
           pendereco.setVisible(true);
           pendereco.nome=jTnome.getText();
           pendereco.apelido=jTusuario.getText();
           pendereco.tipo=jCtipo.getSelectedIndex();
           pendereco.modalidade=jCmodalidade.getSelectedIndex();
           pendereco.cpf=jFcpfcnpj.getText();
           pendereco.inscricao=jTinscricao.getText();
           pendereco.telefone=jTtelefone.getText();
           pendereco.senha=jPsenha.getText();
           pendereco.lembra=jTlembra.getText();
           pendereco.id=jTidpessoa.getText();
           pendereco.ativo=jCativo.isSelected();
           pendereco.fantasia=jTfantasia.getText();
           Pessoa.this.setVisible(false);
           
       }else{
           JOptionPane.showMessageDialog(null, "Tela de Pesquisa Ja esta aberta");
       }
    }//GEN-LAST:event_jBpenderecoActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        limpa();
        novosairpesquisa();
        desativa();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // TODO add your handling code here:
        ativar();
        salvarcancelarpesquisaendereco();
    }//GEN-LAST:event_jBalterarActionPerformed
public void alterapessoa(){
    try {
            PessoaBins pb = new PessoaBins();
            pb.setNome(jTnome.getText());
            pb.setApelido(jTusuario.getText());
            pb.setTipo(jCtipo.getSelectedIndex() + 1);
            pb.setModalidade(jCmodalidade.getSelectedIndex() + 1);
            pb.setCpf_cnpj(jFcpfcnpj.getText());
            pb.setInscricao(jTinscricao.getText());
            pb.setTelefone(jTtelefone.getText());
            pb.setRua(Integer.parseInt(jTidrua.getText()));
            pb.setNumero(jTnumero.getText());
            pb.setSenha(jPsenha.getText());
            pb.setLembra(jTlembra.getText());
            pb.setId(Integer.parseInt(jTidpessoa.getText()));
            pb.setAtivo(verificaAtivo(jCativo.isSelected()));
            pb.setFantasia(jTfantasia.getText());
            PessoaDao pd = new PessoaDao();
            pd.altera(pb);
            desativa();
            JOptionPane.showMessageDialog(null, "Registro Alterado");

        } catch (SQLException | NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
}
    private void jBpesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisarActionPerformed
        // TODO add your handling code here:
        if(!jDppessoa.isVisible()){
        DefaultTableModel modelocidade = (DefaultTableModel) jTdpessoa.getModel(); //CRIA OBJETO MODELO DO TIPO DEFAULTTABLEMODEL
        modelocidade.setNumRows(0);
        jDppessoa.setLocationRelativeTo(null);
        jDppessoa.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "PESQUISA JA ABERTA");
        }
    }//GEN-LAST:event_jBpesquisarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Aguarde t=new Aguarde();
        threadAguarde(t);
        threadrelatorio(t);
        jDppessoa.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTdpesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdpesquisaKeyReleased
        // TODO add your handling code here:
        try {
            PessoaDao pd= new PessoaDao();
            DadosEmpresaBins de= new DadosEmpresaBins();
            lppessoa=pd.getLista("%"+jTdpesquisa.getText()+"%",selecaojrd(),de.getId()); 
            
            mostrapesquisapessoa(lppessoa);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Pesquisar");
        }
    }//GEN-LAST:event_jTdpesquisaKeyReleased

    private void jTdpessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTdpessoaMouseClicked
        // TODO add your handling code here:
        selecaopesquisapessoa(lppessoa);
        alterarnovoacancelarpesquisa();
        jDppessoa.dispose();
        if(!Pessoa.this.isVisible()){
         Pessoa.this.setVisible(true);   
        }
    }//GEN-LAST:event_jTdpessoaMouseClicked

    private void jCmodalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCmodalidadeActionPerformed
        // TODO add your handling code here:
         if((jCmodalidade.getSelectedIndex()+1)==4 || (jCmodalidade.getSelectedIndex()+1)==5 ){
          jTusuario.setEditable(true);  
          jPsenha.setEditable(true);
         jTlembra.setEditable(true);
         
        }else{
           jTusuario.setEditable(false);  
          jPsenha.setEditable(false);
         jTlembra.setEditable(false); 
         
         jTusuario.setText("");
         jPsenha.setText("");
         jTlembra.setText("");
        }
    }//GEN-LAST:event_jCmodalidadeActionPerformed
    public void threadrelatorio(final Aguarde t){
        new Thread(new Runnable() {

            @Override
            public void run() {
               imprimepessoa();
               t.setVisible(false);
            }
        }).start();
    }
    public void threadAguarde(final Aguarde t){
       new Thread(new Runnable() {

           @Override
           public void run() {
               t.setVisible(true);
           }
       }).start();
         
    }
    public void imprimepessoa(){    
      try {
          DadosEmpresaBins de= new DadosEmpresaBins();
            String sql="pessoa."+selecaojrd()+" like '%"+jTdpesquisa.getText()+"%' and pessoa.empresa="+de.getId()+"";
            CriaConexao con = new CriaConexao();//cria variavel tipo conexao
            Map map = new HashMap();//cria variativo de parametro
            map.put("LOCAL",sql);//recebe parametro para o relatorio
            JasperPrint jasperPrint = JasperFillManager.fillReport("./Relatorio/pessoa.jasper", map, CriaConexao.getConexao());//chama relatorio   
           JasperViewer jrviewer = new JasperViewer(jasperPrint, false);//cria variavel do tipo vil
            jrviewer.setVisible(true);   //visualiza o relatorio
           jrviewer.toFront();  //coloca ela na frente das janelas
        } catch (JRException |SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatorio"+ex);
        }catch(NumberFormatException ex){
            JOptionPane.showMessageDialog(null, "Selecione um Orcamento"+ex);
        }
   
    }
    public void selecaopesquisapessoa(List<PessoaBins> pb){
        for (int i=0;i< pb.size();i++){
            if(jTdpessoa.getSelectedRow()==i){
                jTidpessoa.setText(Integer.toString(pb.get(i).getId()));
                jTnome.setText(pb.get(i).getNome());
                jTusuario.setText(pb.get(i).getApelido());
                jCtipo.setSelectedIndex((pb.get(i).getTipo())-1);
                jCmodalidade.setSelectedIndex((pb.get(i).getModalidade())-1);
                jFcpfcnpj.setText(pb.get(i).getCpf_cnpj());
                jTinscricao.setText(pb.get(i).getInscricao());
                jTnumero.setText(pb.get(i).getNumero());
                jTtelefone.setText(pb.get(i).getTelefone());
                jTlembra.setText(pb.get(i).getLembra());
                jPsenha.setText(pb.get(i).getSenha());
                jCativo.setSelected(converteAtivo(pb.get(i).getAtivo()));
                jTfantasia.setText(pb.get(i).getFantasia());
                selecaoenderecorua(pb.get(i).getRua());
            }
        }
    }
    public void selecaoenderecorua(Integer idrua){
        
        try {
            RuaDao rd= new RuaDao();
            lprua=rd.getruapessoa(idrua);
            mostrarua(lprua);
        } catch (SQLException ex) {
            Logger.getLogger(Pessoa.class.getName()).log(Level.SEVERE, null, ex);
        }
       
    }
    public void mostrarua(List<RuaBins> lprua){
        jTidrua.setText(Integer.toString(lprua.get(0).getId()));
        jTrua.setText(lprua.get(0).getNome());
        jTbairro.setText(lprua.get(0).getBairro());
        jTcep.setText(lprua.get(0).getCep());
        selecaoenderecocidade(lprua.get(0).getCidade());
    }
    public void selecaoenderecocidade(Integer idcidade){
        
        try {
            CidadeDao cd= new CidadeDao();
            lpcidade=cd.getcidadepessoa(idcidade);
        } catch (SQLException ex) {
            Logger.getLogger(Pessoa.class.getName()).log(Level.SEVERE, null, ex);
        }
        mostracidade(lpcidade);
    }
    public void mostracidade(List<CidadeBins> lpcidade){
        jTcidade.setText(lpcidade.get(0).getNome());
        jTestado.setText(lpcidade.get(0).getEstado());
        jTpais.setText(lpcidade.get(0).getPais());
    }
    public String selecaojrd(){
    if(jRdapelido.isSelected()){
        return jRdapelido.getName();
    }
    if(jRdcpf_cnpj.isSelected()){
        return jRdcpf_cnpj.getName();
    }
    if(jRdnome.isSelected()){
        return jRdnome.getName();
    }else{
        return "Fudel";
    }
}
public void mostrapesquisapessoa(List<PessoaBins> lpessoa){
        DefaultTableModel modelocidade = (DefaultTableModel) jTdpessoa.getModel(); //CRIA OBJETO MODELO DO TIPO DEFAULTTABLEMODEL
        modelocidade.setNumRows(0);//
        for(int i=0; i<lpessoa.size();i++){ //ENQUANTO O RESET DO METODO EXECULTA SQL TIVER DADOS ELE VAI PREENCHER A TABELA          
                modelocidade.addRow(new Object[]{lpessoa.get(i).getId(),lpessoa.get(i).getNome(),lpessoa.get(i).getFantasia(),lpessoa.get(i).getCpf_cnpj(),lpessoa.get(i).getTelefone()});                            
            }  
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pessoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            @Override
            public void run() {
                new Pessoa().setVisible(true);
                
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBpendereco;
    private javax.swing.JButton jBpesquisar;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JButton jButton1;
    public javax.swing.JCheckBox jCativo;
    public javax.swing.JComboBox jCmodalidade;
    public javax.swing.JComboBox jCtipo;
    public javax.swing.JDialog jDppessoa;
    public javax.swing.JTextField jFcpfcnpj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    public javax.swing.JPasswordField jPsenha;
    private javax.swing.JRadioButton jRdapelido;
    private javax.swing.JRadioButton jRdcpf_cnpj;
    private javax.swing.JRadioButton jRdnome;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTextField jTbairro;
    public javax.swing.JFormattedTextField jTcep;
    public javax.swing.JTextField jTcidade;
    protected javax.swing.JTextField jTdpesquisa;
    protected javax.swing.JTable jTdpessoa;
    public javax.swing.JTextField jTestado;
    public javax.swing.JTextField jTfantasia;
    public javax.swing.JTextField jTidpessoa;
    public javax.swing.JTextField jTidrua;
    public javax.swing.JTextField jTinscricao;
    public javax.swing.JTextField jTlembra;
    public javax.swing.JTextField jTnome;
    public javax.swing.JTextField jTnumero;
    public javax.swing.JTextField jTpais;
    public javax.swing.JTextField jTrua;
    public javax.swing.JTextField jTtelefone;
    public javax.swing.JTextField jTusuario;
    // End of variables declaration//GEN-END:variables
}
