/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bancodados.CriaConexao;
import bins.DadosEmpresaBins;
import bins.PessoaBins;
import bins.ReceberBins;
import dao.PessoaDao;
import dao.ReceberDao;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Date;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MARCOS
 */
public class Receber extends javax.swing.JFrame {

    DefaultTableModel tmppessoa = new DefaultTableModel(null, new String[]{"ID", "NOME", "APELIDO", "CPF_CNPJ", "TELEFONE"});
    List<PessoaBins> lppessoa;
    DefaultTableModel tmpvendedor = new DefaultTableModel(null, new String[]{"ID", "NOME"});
    List<PessoaBins> lpvendedor;
    DefaultTableModel tmpconta = new DefaultTableModel(null, new String[]{"ID", "CLIENTE", "CNPJ", "NORCAMENTO", "NDOCUMENTO", "DATAVENDA", "VENCIMENTO", "VALOR"});
    List<ReceberBins> lpconta;
    List<ReceberBins> lultimoAdc;

    /**
     * Creates new form Receber
     */
    public Receber() {
        initComponents();
        inicializaTabelas();
        inicializaAtalhos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGrouppago = new javax.swing.ButtonGroup();
        jDcliente = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTdpessoa = new javax.swing.JTable();
        jTdidpessoa = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jTdpesquisacliente = new javax.swing.JTextField();
        jRdnome = new javax.swing.JRadioButton();
        jRdapelido = new javax.swing.JRadioButton();
        jRdcpf_cnpj = new javax.swing.JRadioButton();
        jLabel22 = new javax.swing.JLabel();
        buttonGroupjdcliente = new javax.swing.ButtonGroup();
        jDvendedor = new javax.swing.JDialog();
        jTdpesquisavendedor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTdvendedor = new javax.swing.JTable();
        jTdidvendedor = new javax.swing.JTextField();
        jDpesquisa = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTdconta = new javax.swing.JTable();
        jTdpesquisaconta = new javax.swing.JTextField();
        jCcampo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jBimprimir = new javax.swing.JButton();
        jRppago = new javax.swing.JRadioButton();
        jRpapagar = new javax.swing.JRadioButton();
        jRptodos = new javax.swing.JRadioButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        bGpesqreceber = new javax.swing.ButtonGroup();
        jTrecebidreceber = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jTrecebcliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTrecebcnpj = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTrecebvendedor = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTrecebnorcamento = new javax.swing.JTextField();
        jTrecebndocumento = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jBcliente = new javax.swing.JButton();
        jBvendedor = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTAobs = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jFrecebvalortitulo = new javax.swing.JFormattedTextField();
        jDatedatapagamento = new com.toedter.calendar.JDateChooser();
        jDatedatavencimento = new com.toedter.calendar.JDateChooser();
        jDatedatavenda = new com.toedter.calendar.JDateChooser();
        jCemissao = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCtipo = new javax.swing.JComboBox();
        jRpago = new javax.swing.JRadioButton();
        jRaberto = new javax.swing.JRadioButton();
        jXPanel1 = new org.jdesktop.swingx.JXPanel();
        jBnovo = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jBpesquisa = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBsair = new javax.swing.JButton();

        jDcliente.setTitle("PESQUISA CLIENTES");
        jDcliente.setMinimumSize(new java.awt.Dimension(720, 420));
        jDcliente.setModal(true);
        jDcliente.setResizable(false);

        jTdpessoa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "APELIDO", "CPF_CNPJ", "TELEFONE"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTdpessoa.getTableHeader().setResizingAllowed(false);
        jTdpessoa.getTableHeader().setReorderingAllowed(false);
        jTdpessoa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTdpessoaMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTdpessoa);

        jTdidpessoa.setEditable(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jTdpesquisacliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdpesquisaclienteActionPerformed(evt);
            }
        });
        jTdpesquisacliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTdpesquisaclienteKeyReleased(evt);
            }
        });

        buttonGroupjdcliente.add(jRdnome);
        jRdnome.setSelected(true);
        jRdnome.setText("NOME");
        jRdnome.setName("nome"); // NOI18N

        buttonGroupjdcliente.add(jRdapelido);
        jRdapelido.setText("APELIDO");
        jRdapelido.setName("apelido"); // NOI18N

        buttonGroupjdcliente.add(jRdcpf_cnpj);
        jRdcpf_cnpj.setText("CPF_CNPJ");
        jRdcpf_cnpj.setName("cpf_cnpj"); // NOI18N

        jLabel22.setText("PESQUISA:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTdpesquisacliente, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRdnome, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRdapelido)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRdcpf_cnpj)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTdpesquisacliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jRdnome)
                    .addComponent(jRdapelido)
                    .addComponent(jRdcpf_cnpj)
                    .addComponent(jLabel22))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDclienteLayout = new javax.swing.GroupLayout(jDcliente.getContentPane());
        jDcliente.getContentPane().setLayout(jDclienteLayout);
        jDclienteLayout.setHorizontalGroup(
            jDclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDclienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTdidpessoa, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        jDclienteLayout.setVerticalGroup(
            jDclienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDclienteLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jTdidpessoa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        jDvendedor.setTitle("VENDEDOR");
        jDvendedor.setMinimumSize(new java.awt.Dimension(363, 293));
        jDvendedor.setModal(true);
        jDvendedor.setResizable(false);

        jTdpesquisavendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdpesquisavendedorActionPerformed(evt);
            }
        });
        jTdpesquisavendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTdpesquisavendedorKeyPressed(evt);
            }
        });

        jLabel12.setText("NOME:");

        jTdvendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTdvendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTdvendedorMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTdvendedor);

        jTdidvendedor.setEditable(false);
        jTdidvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdidvendedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDvendedorLayout = new javax.swing.GroupLayout(jDvendedor.getContentPane());
        jDvendedor.getContentPane().setLayout(jDvendedorLayout);
        jDvendedorLayout.setHorizontalGroup(
            jDvendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDvendedorLayout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jDvendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDvendedorLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTdpesquisavendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(jTdidvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jDvendedorLayout.setVerticalGroup(
            jDvendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDvendedorLayout.createSequentialGroup()
                .addGroup(jDvendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDvendedorLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jTdpesquisavendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDvendedorLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTdidvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)))
                .addGap(49, 49, 49)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(61, Short.MAX_VALUE))
        );

        jDpesquisa.setMinimumSize(new java.awt.Dimension(720, 420));
        jDpesquisa.setModal(true);

        jTdconta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "CLIENTE", "CNPJ", "NORCAMENTO", "NDOCUMENTO", "DATAVENDA", "VENCIMENTO", "VALOR"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTdconta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTdconta.getTableHeader().setResizingAllowed(false);
        jTdconta.getTableHeader().setReorderingAllowed(false);
        jTdconta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTdcontaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTdconta);

        jTdpesquisaconta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTdpesquisacontaActionPerformed(evt);
            }
        });
        jTdpesquisaconta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTdpesquisacontaKeyReleased(evt);
            }
        });

        jCcampo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PESSOA.NOME", "NORCAMENTO", "NDOCUMENTO", "PESSOA.CPF_CNPJ", "VALOR", "DATAVENDA", "DATAVENCIMENTO" }));

        jLabel13.setText("PESQUISA:");

        jBimprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Uteis/EMPRIMIR32X32.png"))); // NOI18N
        jBimprimir.setText("IMPRIMIR");
        jBimprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBimprimirActionPerformed(evt);
            }
        });

        bGpesqreceber.add(jRppago);
        jRppago.setText("PAGO");
        jRppago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRppagoActionPerformed(evt);
            }
        });

        bGpesqreceber.add(jRpapagar);
        jRpapagar.setText("A PAGAR");

        bGpesqreceber.add(jRptodos);
        jRptodos.setSelected(true);
        jRptodos.setText("TODOS");

        javax.swing.GroupLayout jDpesquisaLayout = new javax.swing.GroupLayout(jDpesquisa.getContentPane());
        jDpesquisa.getContentPane().setLayout(jDpesquisaLayout);
        jDpesquisaLayout.setHorizontalGroup(
            jDpesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDpesquisaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jDpesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jDpesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jDpesquisaLayout.createSequentialGroup()
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jTdpesquisaconta)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jCcampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRppago)
                            .addGap(18, 18, 18)
                            .addComponent(jRpapagar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jRptodos))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 687, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBimprimir))
                .addGap(20, 20, 20))
        );
        jDpesquisaLayout.setVerticalGroup(
            jDpesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDpesquisaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jDpesquisaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTdpesquisaconta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCcampo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jRppago)
                    .addComponent(jRpapagar)
                    .addComponent(jRptodos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBimprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)
                .addGap(11, 11, 11))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane4.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("A RECEBER");
        setResizable(false);

        jTrecebidreceber.setEditable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cliente/Vendedor"));

        jTrecebcliente.setEditable(false);
        jTrecebcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrecebclienteActionPerformed(evt);
            }
        });

        jLabel1.setText("NOME:");

        jTrecebcnpj.setEditable(false);

        jLabel2.setText("CNPJ:");

        jTrecebvendedor.setEditable(false);

        jLabel6.setText("Vendedor:");

        jLabel8.setText("N.ORCAMENTO");

        jTrecebnorcamento.setEditable(false);

        jTrecebndocumento.setEditable(false);

        jLabel11.setText("N.DOCUMENTO");

        jBcliente.setText("F1");
        jBcliente.setEnabled(false);
        jBcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBclienteActionPerformed(evt);
            }
        });

        jBvendedor.setText("F2");
        jBvendedor.setEnabled(false);
        jBvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBvendedorActionPerformed(evt);
            }
        });

        jTAobs.setEditable(false);
        jTAobs.setColumns(20);
        jTAobs.setLineWrap(true);
        jTAobs.setRows(5);
        jTAobs.setToolTipText("");
        jTAobs.setBorder(null);
        jScrollPane5.setViewportView(jTAobs);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(55, 55, 55))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jTrecebcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTrecebnorcamento, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jTrecebndocumento))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBcliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTrecebcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTrecebvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBvendedor))))
                    .addComponent(jScrollPane5))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTrecebcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTrecebcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTrecebvendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBvendedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTrecebnorcamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTrecebndocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel3.setText("DATA VENDA:");

        jLabel7.setText("VALOR TITULO:");

        jLabel9.setText("DATA VENCIMENTO:");

        jLabel10.setText("DATA PAGAMENTO:");

        jFrecebvalortitulo.setEditable(false);
        jFrecebvalortitulo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0.00"))));

        jDatedatapagamento.setDateFormatString("dd.MM.yyyy");
        jDatedatapagamento.setEnabled(false);

        jDatedatavencimento.setDateFormatString("dd.MM.yyyy");
        jDatedatavencimento.setEnabled(false);

        jDatedatavenda.setToolTipText("");
        jDatedatavenda.setDateFormatString("dd.MM.yyyy");
        jDatedatavenda.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jDatedatavenda, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jDatedatavencimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jDatedatapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jFrecebvalortitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jFrecebvalortitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatedatapagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatedatavencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDatedatavenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jCemissao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PROPRIA", "TERCEIROS" }));
        jCemissao.setEnabled(false);
        jCemissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCemissaoActionPerformed(evt);
            }
        });

        jLabel4.setText("Emissão:");

        jLabel5.setText("Tipo:");

        jCtipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "DUPLICATA", "RECIBO", "CHEQUE", "OUTROS" }));
        jCtipo.setEnabled(false);

        buttonGrouppago.add(jRpago);
        jRpago.setText("PAGO");
        jRpago.setEnabled(false);
        jRpago.setName("S"); // NOI18N

        buttonGrouppago.add(jRaberto);
        jRaberto.setSelected(true);
        jRaberto.setText("ABERTO");
        jRaberto.setEnabled(false);
        jRaberto.setName("N"); // NOI18N
        jRaberto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRabertoActionPerformed(evt);
            }
        });

        jXPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jBnovo.setText("NOVO");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jBsalvar.setText("SALVAR");
        jBsalvar.setEnabled(false);
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBpesquisa.setText("PESQUISA");
        jBpesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBpesquisaActionPerformed(evt);
            }
        });

        jBalterar.setText("ALTERAR");
        jBalterar.setEnabled(false);
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBcancelar.setText("CANCELAR");
        jBcancelar.setEnabled(false);
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        jBexcluir.setText("EXCLUIR");
        jBexcluir.setEnabled(false);
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBsair.setText("SAIR");
        jBsair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jXPanel1Layout = new javax.swing.GroupLayout(jXPanel1);
        jXPanel1.setLayout(jXPanel1Layout);
        jXPanel1Layout.setHorizontalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jXPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jBnovo, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jBsalvar)
                .addGap(15, 15, 15)
                .addComponent(jBalterar)
                .addGap(15, 15, 15)
                .addComponent(jBcancelar)
                .addGap(15, 15, 15)
                .addComponent(jBexcluir)
                .addGap(15, 15, 15)
                .addComponent(jBsair, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBpesquisa)
                .addContainerGap())
        );
        jXPanel1Layout.setVerticalGroup(
            jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jXPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jXPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnovo)
                    .addComponent(jBsalvar)
                    .addComponent(jBpesquisa)
                    .addComponent(jBalterar)
                    .addComponent(jBcancelar)
                    .addComponent(jBexcluir)
                    .addComponent(jBsair))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addGap(10, 10, 10)
                .addComponent(jCemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(10, 10, 10)
                .addComponent(jCtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(jRpago)
                .addGap(18, 18, 18)
                .addComponent(jRaberto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTrecebidreceber, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jXPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCemissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel5))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jCtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jRpago)
                        .addComponent(jRaberto))
                    .addComponent(jTrecebidreceber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jXPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        setSize(new java.awt.Dimension(775, 471));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void inicializaTabelas() {//INICIALIZA TABELAS DO FRAME
        jTdpessoa.getColumnModel().getColumn(0).setMaxWidth(40);
        jTdpessoa.getColumnModel().getColumn(1);
        jTdpessoa.getColumnModel().getColumn(2);
        jTdpessoa.getColumnModel().getColumn(3);
        jTdpessoa.getColumnModel().getColumn(4);

        jTdvendedor.getColumnModel().getColumn(0).setMaxWidth(40);
        jTdvendedor.getColumnModel().getColumn(1);

        jTdconta.getColumnModel().getColumn(0).setMinWidth(60);
        jTdconta.getColumnModel().getColumn(0).setMaxWidth(60);
        jTdconta.getColumnModel().getColumn(1).setMinWidth(300);
        jTdconta.getColumnModel().getColumn(1).setMaxWidth(300);
        jTdconta.getColumnModel().getColumn(2).setMinWidth(120);
        jTdconta.getColumnModel().getColumn(2).setMaxWidth(120);
        jTdconta.getColumnModel().getColumn(3).setMinWidth(120);
        jTdconta.getColumnModel().getColumn(3).setMaxWidth(120);
        jTdconta.getColumnModel().getColumn(4).setMinWidth(120);
        jTdconta.getColumnModel().getColumn(4).setMaxWidth(120);
        jTdconta.getColumnModel().getColumn(5).setMinWidth(120);
        jTdconta.getColumnModel().getColumn(5).setMaxWidth(120);
        jTdconta.getColumnModel().getColumn(6).setMinWidth(120);
        jTdconta.getColumnModel().getColumn(6).setMaxWidth(120);
        jTdconta.getColumnModel().getColumn(7).setMaxWidth(120);
        jTdconta.getColumnModel().getColumn(7).setMaxWidth(120);
    }

    private void inicializaAtalhos() {
        //ATALHO PARA O BOTAO JBCLIENTE
        KeyStroke keyStrokeJBCLIENTE = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0);
        String actionNameJBCLIENTE = "TECLA_F1";
        InputMap inputMapJBCLIENTE = jBcliente.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapJBCLIENTE.put(keyStrokeJBCLIENTE, actionNameJBCLIENTE);
        ActionMap actionMapJBCLIENTE = jBcliente.getActionMap();
        actionMapJBCLIENTE.put(actionNameJBCLIENTE, acaoJBcliente);
        
        //ATALHO PARA O BOTAO JBVENDEDOR
         KeyStroke keyStrokeJBVENDEDOR = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        String actionNameJBVENDEDOR = "TECLA_F2";
        InputMap inputMapJBVENDEDOR = jBvendedor.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        
        inputMapJBVENDEDOR.put(keyStrokeJBVENDEDOR, actionNameJBVENDEDOR);
        ActionMap actionMapJBVENDEDOR = jBvendedor.getActionMap();
        actionMapJBVENDEDOR.put(actionNameJBVENDEDOR, acaojBvendedor);
    }
    //ACAO DO BOTAO JBCLIENTE
    Action acaoJBcliente= new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            jBcliente.doClick();
        }
    };
    //ACAO DO BOTAO JBVENDEDOR
    Action acaojBvendedor= new AbstractAction() {

        @Override
        public void actionPerformed(ActionEvent e) {
            jBvendedor.doClick();
        }
    };
    public void ativar() {
        jCemissao.setEnabled(true);
        jCtipo.setEnabled(true);
        jRaberto.setEnabled(true);
        jRpago.setEnabled(true);
        jTrecebnorcamento.setEditable(true);
        jTrecebndocumento.setEditable(true);
        jDatedatapagamento.setEnabled(true);
        jDatedatavencimento.setEnabled(true);
        jDatedatavenda.setEnabled(true);
        jFrecebvalortitulo.setEditable(true);
        jBcliente.setEnabled(true);
        jBvendedor.setEnabled(true);
        jTAobs.setEditable(true);
    }

    public void limpa() {
        jTrecebcliente.setText("");
        jTrecebidreceber.setText("");
        jTrecebcnpj.setText("");
        jTrecebvendedor.setText("");
        jTrecebnorcamento.setText("");
        jTrecebndocumento.setText("");
        jDatedatapagamento.setDate(null);
        jDatedatavencimento.setDate(null);
        jDatedatavenda.setDate(null);
        jFrecebvalortitulo.setText("0,00");
        jTAobs.setText("");

    }
    public void salvarcancelar(){
        jBnovo.setEnabled(false);
        jBsalvar.setEnabled(true);
        jBalterar.setEnabled(false);
        jBpesquisa.setEnabled(false);
        jBcancelar.setEnabled(true);
        jBexcluir.setEnabled(false);
    }
    public void novopesquisa(){
        jBnovo.setEnabled(true);
        jBsalvar.setEnabled(false);
        jBalterar.setEnabled(false);
        jBpesquisa.setEnabled(true);
        jBcancelar.setEnabled(false);
        jBexcluir.setEnabled(false);
    }
    public void novoalterarexcluir(){
        jBnovo.setEnabled(true);
        jBsalvar.setEnabled(false);
        jBalterar.setEnabled(true);
        jBpesquisa.setEnabled(true);
        jBcancelar.setEnabled(false);
        jBexcluir.setEnabled(true);
    }
    public Date ConverteData(String data) {
        java.sql.Date date = null;
        if (data != "" && data != null) {
            try {
                DateFormat formato = new SimpleDateFormat("dd.MM.yyyy");
                date = new java.sql.Date(formato.parse(data).getTime());
            } catch (ParseException e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
        return date;
    }

    public void desativar() {
        jCemissao.setEditable(false);
        jCtipo.setEditable(false);
        jRaberto.setEnabled(false);
        jRpago.setEnabled(false);
        jTrecebnorcamento.setEditable(false);
        jTrecebndocumento.setEditable(false);
        jDatedatapagamento.setEnabled(false);
        jDatedatavencimento.setEnabled(false);
        jDatedatavenda.setEnabled(false);
        jFrecebvalortitulo.setEditable(false);
        jBcliente.setEnabled(false);
        jBvendedor.setEnabled(false);
        jTAobs.setEditable(false);

    }
    private void jTrecebclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrecebclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTrecebclienteActionPerformed

    private void jRabertoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRabertoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRabertoActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        // String data = new SimpleDateFormat("dd.MM.yyyy").format(jDatedatapagamento.getDate()).replace("/", ".");                 
        if(jRpago.isSelected()){
            if(jDatedatapagamento.getDate()!=null){
                salvarReceber();
            }else{
                JOptionPane.showMessageDialog(null, "Data de Pagamento Não Foi Selecionado");
            }
        }else if(!jRpago.isSelected()){
            if(jDatedatapagamento.getDate()==null){
                salvarReceber();
            }else{
                JOptionPane.showMessageDialog(null, "Data de Pagamento Selecionado se Não Foi Pago \n Apague a Data de Pagamento.");
            }
        }
    }//GEN-LAST:event_jBsalvarActionPerformed
    public void salvarReceber(){
        if ("".equals(jTrecebidreceber.getText())) {
            if (salvanovo()) {             
                    novopesquisa();
                    desativar();
                    JOptionPane.showMessageDialog(null, "Cadastro Efetuado com Sucesso");
            }
        } else {
            if (alterar()) {
                
                novopesquisa();
                desativar();
                JOptionPane.showMessageDialog(null, "Alteração Efetuado com Sucesso");
            }
        }
    }
    public boolean salvanovo() {//SALVA NOVA CONTA A RECEBER
        ReceberBins rb = new ReceberBins();
        DadosEmpresaBins de = new DadosEmpresaBins();
        rb.setEmissao(String.valueOf(jCemissao.getSelectedItem()));
        rb.setTipo(String.valueOf(jCtipo.getSelectedItem()));
        rb.setPg(selecaopagamento());
        if (jTAobs.getText().length() < 150) {
            rb.setObs(jTAobs.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Campo Observação muito longo!!");
            return false;
        }
        try {
            rb.setCliente(Integer.valueOf(jTdidpessoa.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Escolha o Cliente");
            return false;
        }
        try {
            rb.setVendedor(Integer.valueOf(jTdidvendedor.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Escolha o Vendedor");
            return false;
        }
        if (!"".equals(jTrecebnorcamento.getText()) && !"0".equals(jTrecebnorcamento.getText())) {//VERIFICA SE O HA NUMERO DE ORCAMENTO
            try {
                rb.setNorcamento(Integer.valueOf(jTrecebnorcamento.getText()));//CONVERTE NUMERO DE ORCAMENTO PARA INTEIRO
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Numero de Orcamento Incorreto");
                return false;
            }
        } else {
            rb.setNorcamento(null);//SE NAO HAVER NUMERO DE ORCAMENTO PASSA NULO
        }
        rb.setNdocumento(jTrecebndocumento.getText());
        try {//VERIFICA SE A DATA E VALIDA
            rb.setDatavenda(new SimpleDateFormat("yyyy.MM.dd").format(jDatedatavenda.getDate()));
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Data da Venda Incorreta");
            return false;
        }

        try {//VERIFICA SE A DATA DO VENCIMENTO E VALIDA
            rb.setDatavencimento(new SimpleDateFormat("yyyy.MM.dd").format(jDatedatavencimento.getDate()));
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Data Vencimento Incorreta");
            return false;
        }
        try {//VERIFICA SE A DATA DO PAGAMENTO E VALIDA          
            rb.setDatapg(new SimpleDateFormat("yyyy.MM.dd").format(jDatedatapagamento.getDate()));
        } catch (NullPointerException ex) {
            rb.setDatapg(null);
        }
        if(!"0,00".equals(jFrecebvalortitulo.getText()) && !"".equals(jFrecebvalortitulo.getText())){
           rb.setValor(Float.valueOf(jFrecebvalortitulo.getText().replace(",", ".")));
        }else{
            JOptionPane.showMessageDialog(null, "Documento sem Valor");
            return false;
        }
        rb.setEmpresa(de.getId());
        try {
            ReceberDao rd = new ReceberDao();
            rd.adiciona(rb);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            return false;
        }
        return true;
    }
    
    public boolean alterar(){//ALTERA CONTA A RECEBER
         ReceberBins rb = new ReceberBins();
        DadosEmpresaBins de = new DadosEmpresaBins();
        rb.setId(Integer.valueOf(jTrecebidreceber.getText()));
        rb.setEmissao(String.valueOf(jCemissao.getSelectedItem()));
        rb.setTipo(String.valueOf(jCtipo.getSelectedItem()));
        rb.setPg(selecaopagamento());
        if (jTAobs.getText().length() < 150) {
            rb.setObs(jTAobs.getText());
        } else {
            JOptionPane.showMessageDialog(null, "Campo Observação muito longo!!");
            return false;
        }
        try {
            rb.setCliente(Integer.valueOf(jTdidpessoa.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Escolha o Cliente");
            return false;
        }
        try {
            rb.setVendedor(Integer.valueOf(jTdidvendedor.getText()));
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Escolha o Vendedor");
            return false;
        }
        if (!"".equals(jTrecebnorcamento.getText()) && !"0".equals(jTrecebnorcamento.getText())) {//VERIFICA SE O HA NUMERO DE ORCAMENTO
            try {
                rb.setNorcamento(Integer.valueOf(jTrecebnorcamento.getText()));//CONVERTE NUMERO DE ORCAMENTO PARA INTEIRO
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "Numero de Orcamento Incorreto");
                return false;
            }
        } else {
            rb.setNorcamento(null);//SE NAO HAVER NUMERO DE ORCAMENTO PASSA NULO
        }
        rb.setNdocumento(jTrecebndocumento.getText());
        try {//VERIFICA SE A DATA DA VENDA E VALIDA
            rb.setDatavenda(new SimpleDateFormat("yyyy.MM.dd").format(jDatedatavenda.getDate()));
            
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Data da Venda Incorreta");
            return false;
        }

        try {//VERIFICA SE A DATA DO VENCIMENTO E VALIDA
            rb.setDatavencimento(new SimpleDateFormat("yyyy.MM.dd").format(jDatedatavencimento.getDate()));
        } catch (NullPointerException ex) {
            JOptionPane.showMessageDialog(null, "Data Vencimento Incorreta");
            return false;
        }
        try {//VERIFICA SE A DATA DO PAGAMENTO E VALIDA          
            rb.setDatapg(new SimpleDateFormat("yyyy.MM.dd").format(jDatedatapagamento.getDate()));
        } catch (NullPointerException ex) {
            rb.setDatapg(null);
        }
        if(!"0,00".equals(jFrecebvalortitulo.getText()) && !"".equals(jFrecebvalortitulo.getText())){
           rb.setValor(Float.valueOf(jFrecebvalortitulo.getText().replace(",", ".")));
        }else{
            JOptionPane.showMessageDialog(null, "Documento sem Valor");
            return false;
        }
        rb.setEmpresa(de.getId());
        try {
            ReceberDao rd = new ReceberDao();
            rd.altera(rb);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
            return false;
        }
        return true;
        
    }
    public String selecaopagamento() {//RETORNA P OU A DE ACORDO COM A SELECAO DO RADIOBUTON
        if (jRpago.isSelected()) {
            return "S";
        } else {
            return "N";
        }
    }
    private void jCemissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCemissaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCemissaoActionPerformed

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
        ativar();//ATIVA OS CAMPOS
        limpa();//LIMPA OS CAMPOS
        salvarcancelar();
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jTdpessoaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTdpessoaMouseClicked
        // TODO add your handling code here:
        selecaopesquisapessoa(lppessoa);
        jDcliente.setVisible(false);
    }//GEN-LAST:event_jTdpessoaMouseClicked
    public void selecaopesquisapessoa(List<PessoaBins> pb) {
        for (int i = 0; i < pb.size(); i++) {
            if (jTdpessoa.getSelectedRow() == i) {
                jTrecebcliente.setText(pb.get(i).getNome());
                jTrecebcnpj.setText(pb.get(i).getCpf_cnpj());
                jTdidpessoa.setText(String.valueOf(pb.get(i).getId()));
            }
        }
    }
    private void jTdpesquisaclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdpesquisaclienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdpesquisaclienteActionPerformed

    private void jBclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBclienteActionPerformed
        // TODO add your handling code here:
        jDcliente.setLocationRelativeTo(null);
        jDcliente.setVisible(true);
        DefaultTableModel modelopessoa = (DefaultTableModel) jTdpessoa.getModel();
        modelopessoa.setNumRows(0);
        jTdpesquisacliente.setText("");
        jTdpesquisacliente.requestFocus();

    }//GEN-LAST:event_jBclienteActionPerformed

    private void jTdpesquisavendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdpesquisavendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdpesquisavendedorActionPerformed

    private void jTdpesquisavendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdpesquisavendedorKeyPressed
        // TODO add your handling code here:
        try {
            PessoaDao pd = new PessoaDao();
            DadosEmpresaBins de = new DadosEmpresaBins();
            lpvendedor = pd.getListavendedor("%" + jTdpesquisavendedor.getText() + "%", de.getId());
            mostravendedor(lpvendedor);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar" + ex);
        }
    }//GEN-LAST:event_jTdpesquisavendedorKeyPressed
    public void mostravendedor(List<PessoaBins> pb) {
        DefaultTableModel modelovendedor = (DefaultTableModel) jTdvendedor.getModel();
        modelovendedor.setNumRows(0);
        for (int i = 0; i < pb.size(); i++) {
            modelovendedor.addRow(new Object[]{pb.get(i).getId(), pb.get(i).getNome()});
        }
    }
    private void jTdvendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTdvendedorMouseClicked
        // TODO add your handling code here:
        selecaopesquisavendedor(lpvendedor);
        jDvendedor.setVisible(false);

    }//GEN-LAST:event_jTdvendedorMouseClicked
    public void selecaopesquisavendedor(List<PessoaBins> pb) {
        for (int i = 0; i < pb.size(); i++) {
            if (jTdvendedor.getSelectedRow() == i) {
                jTdidvendedor.setText(String.valueOf(pb.get(i).getId()));
                jTrecebvendedor.setText(pb.get(i).getNome());
            }
        }
    }
    private void jTdidvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdidvendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdidvendedorActionPerformed

    private void jBvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBvendedorActionPerformed
        // TODO add your handling code here:
        jDvendedor.setLocationRelativeTo(null);
        jDvendedor.setVisible(true);
        DefaultTableModel modelovendedor = (DefaultTableModel) jTdvendedor.getModel();
        modelovendedor.setNumRows(0);
    }//GEN-LAST:event_jBvendedorActionPerformed

    private void jBpesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBpesquisaActionPerformed
        // TODO add your handling code here:
        jDpesquisa.setLocationRelativeTo(null);
        DefaultTableModel modeloconta = (DefaultTableModel) jTdconta.getModel();
        modeloconta.setNumRows(0);
        jTdpesquisaconta.setText("");
        jDpesquisa.setVisible(true);
        jTdpesquisaconta.requestFocus();
    }//GEN-LAST:event_jBpesquisaActionPerformed

    private void jTdpesquisacontaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTdpesquisacontaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTdpesquisacontaActionPerformed

    private void jTdcontaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTdcontaMouseClicked
        // TODO add your handling code here:
        limpa();
        selecaoconta(lpconta);//PREENCHE TELA COM OS DADOS SELECIONADOS
        jDpesquisa.setVisible(false);
        novoalterarexcluir();
        if(!Receber.this.isVisible()){
            Receber.this.setVisible(true);
        }
    }//GEN-LAST:event_jTdcontaMouseClicked

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // TODO add your handling code here:
        ativar();
        salvarcancelar();
    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        limpa();
        desativar();
        novopesquisa();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        // TODO add your handling code here:
        ReceberBins rb = new ReceberBins();
        rb.setId(Integer.valueOf(jTrecebidreceber.getText()));
        try {
            ReceberDao rd = new ReceberDao();
            rd.remove(rb);
            limpa();
            desativar();
            novopesquisa();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
            JOptionPane.showMessageDialog(null, "Registro Excluido com Sucesso");
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBsairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsairActionPerformed
        // TODO add your handling code here:
        limpa();
        desativar();
        novopesquisa();
        Receber.this.dispose();
    }//GEN-LAST:event_jBsairActionPerformed

    private void jBimprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBimprimirActionPerformed
        // TODO add your handling code here:
        jDpesquisa.setVisible(false);
        Aguarde a = new Aguarde();
        threadaguarde(a);
        threadreceber(a);
    }//GEN-LAST:event_jBimprimirActionPerformed

    private void jTdpesquisaclienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdpesquisaclienteKeyReleased
        // TODO add your handling code here:
         try {
            PessoaDao pd = new PessoaDao();
            DadosEmpresaBins de = new DadosEmpresaBins();
            lppessoa = pd.getListacliente("%" + jTdpesquisacliente.getText() + "%", selecaojrd(), de.getId());
            mostrapesquisapessoa(lppessoa);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao pesquisar" + ex);
        }
    }//GEN-LAST:event_jTdpesquisaclienteKeyReleased

    private void jTdpesquisacontaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTdpesquisacontaKeyReleased
        // TODO add your handling code here:
        pesquisareceber();
    }//GEN-LAST:event_jTdpesquisacontaKeyReleased

    private void jRppagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRppagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRppagoActionPerformed
    public void threadaguarde(final Aguarde a){
        new Thread(new Runnable() {

            @Override
            public void run() {
               a.setVisible(true);
            }
        }).start();
    }
    public void threadreceber(final Aguarde a){
        new Thread(new Runnable() {

            @Override
            public void run() {
                imprimePesqReceber();
                a.setVisible(false);
            }
        }).start();
    }
    
    public void imprimePesqReceber() {
        try {
            DadosEmpresaBins de= new DadosEmpresaBins();
            CriaConexao con = new CriaConexao();
            Map map = new HashMap();
            if(jCcampo.getSelectedItem().equals("DATAVENDA") || jCcampo.getSelectedItem().equals("DATAVENCIMENTO")){
                map.put("campo", "DATE_FORMAT("+jCcampo.getSelectedItem()+", '%d.%m.%Y')"+ " like '%" + jTdpesquisaconta.getText() + "%'");
            }else{
                map.put("campo", jCcampo.getSelectedItem() + " like '%" + jTdpesquisaconta.getText() + "%'");
            }
            map.put("empresa", de.getId());
            map.put("pg", selecaoJRpesquisaReceber());
            JasperPrint jasperPrint = JasperFillManager.fillReport("./Relatorio/receberpesq.jasper", map, con.getConexao());
            JasperViewer jrviewer = new JasperViewer(jasperPrint, false);//cria variavel do tipo vil
            jrviewer.setVisible(true);   //visualiza o relatorio
            jrviewer.toFront();  //coloca ela na frente das janelas
        } catch (JRException | SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao gerar relatorio" + ex);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Selecione uma Conta" + ex);
        }
    }
    public void selecaoconta(List<ReceberBins> lrb) {//PREENCHE TELA COM OS DADOS SELECIONADOS
        for (int i = 0; i < lrb.size(); i++) {//PERCORRE A LISTA 
            if (jTdconta.getSelectedRow() == i) {//PEGA OS DADOS DO INDICE DA LISTA ESPECIFICADO
                jCemissao.setSelectedItem(lrb.get(i).getEmissao());
                jCtipo.setSelectedItem(lrb.get(i).getTipo());
                marcapagamento(lrb.get(i).getPg());
                jTrecebidreceber.setText(String.valueOf(lrb.get(i).getId()));
                jTrecebcliente.setText(lrb.get(i).getNomecliente());
                jTdidpessoa.setText(String.valueOf(lrb.get(i).getCliente()));
                jTrecebcnpj.setText(lrb.get(i).getCnpjcliente());
                jTrecebvendedor.setText(lrb.get(i).getNomevendedor());
                jTdidvendedor.setText(String.valueOf(lrb.get(i).getVendedor()));
                jTrecebnorcamento.setText(String.valueOf(lrb.get(i).getNorcamento()));
                jTrecebndocumento.setText(lrb.get(i).getNdocumento());
                jDatedatavenda.setDate(ConverteData(lrb.get(i).getDatavenda()));
                jDatedatavencimento.setDate(ConverteData(lrb.get(i).getDatavencimento()));
                jDatedatapagamento.setDate(ConverteData(lrb.get(i).getDatapg()));
                jFrecebvalortitulo.setText(String.valueOf(lrb.get(i).getValor()).replace(".", ","));
                jTAobs.setText(lrb.get(i).getObs());
            }
        }
    }

    public void marcapagamento(String s) {//RETORNA P OU A DE ACORDO COM A SELECAO DO RADIOBUTON
        if ("S".equals(s)) {
            jRpago.setSelected(true);
        } else {
            jRaberto.setSelected(true);
        }
    }

    public void pesquisareceber() {
        try {
            ReceberDao rd = new ReceberDao();
            DadosEmpresaBins de = new DadosEmpresaBins();
            if(jCcampo.getSelectedItem().equals("DATAVENDA") || jCcampo.getSelectedItem().equals("DATAVENCIMENTO")){
                lpconta = rd.getlista("DATE_FORMAT("+ jCcampo.getSelectedItem() +", '%d.%m.%Y') like '%"+jTdpesquisaconta.getText()+"%'", de.getId(),selecaoJRpesquisaReceber());
            }else{
                lpconta = rd.getlista(jCcampo.getSelectedItem() + " like '%" + jTdpesquisaconta.getText() + "%'", de.getId(),selecaoJRpesquisaReceber());
            }            

            mostrapesquisaconta(lpconta);
        } catch (SQLException ex) {
            Logger.getLogger(Receber.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    public String selecaoJRpesquisaReceber(){
        if(jRppago.isSelected()){
            return "N";
        }
        if(jRpapagar.isSelected()){
            return "S";
        }
        return "";
    }
    public void mostrapesquisaconta(List<ReceberBins> lconta) {
        DefaultTableModel modeloconta = (DefaultTableModel) jTdconta.getModel();
        modeloconta.setNumRows(0);
        for (int i = 0; i < lconta.size(); i++) {
            modeloconta.addRow(new Object[]{lconta.get(i).getId(), lconta.get(i).getNomecliente(), lconta.get(i).getCnpjcliente(), lconta.get(i).getNorcamento(), lconta.get(i).getNdocumento(), lconta.get(i).getDatavenda(), lconta.get(i).getDatavencimento(), lconta.get(i).getValor()});
        }
    }

    public void mostrapesquisapessoa(List<PessoaBins> lpessoa) {
        DefaultTableModel modelopessoa = (DefaultTableModel) jTdpessoa.getModel(); //CRIA OBJETO MODELO DO TIPO DEFAULTTABLEMODEL
        modelopessoa.setNumRows(0);//
        for (int i = 0; i < lpessoa.size(); i++) { //ENQUANTO O RESET DO METODO EXECULTA SQL TIVER DADOS ELE VAI PREENCHER A TABELA
            modelopessoa.addRow(new Object[]{lpessoa.get(i).getId(), lpessoa.get(i).getNome(), lpessoa.get(i).getApelido(), lpessoa.get(i).getCpf_cnpj(), lpessoa.get(i).getTelefone()});
        }
    }

    public String selecaojrd() {
        if (jRdapelido.isSelected()) {
            return jRdapelido.getName();
        }
        if (jRdcpf_cnpj.isSelected()) {
            return jRdcpf_cnpj.getName();
        }
        if (jRdnome.isSelected()) {
            return jRdnome.getName();
        } else {
            return null;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receber.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receber().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup bGpesqreceber;
    private javax.swing.ButtonGroup buttonGroupjdcliente;
    private javax.swing.ButtonGroup buttonGrouppago;
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBcliente;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBimprimir;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBpesquisa;
    private javax.swing.JButton jBsair;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JButton jBvendedor;
    private javax.swing.JComboBox jCcampo;
    private javax.swing.JComboBox jCemissao;
    private javax.swing.JComboBox jCtipo;
    private com.toedter.calendar.JDateChooser jDatedatapagamento;
    private com.toedter.calendar.JDateChooser jDatedatavencimento;
    private com.toedter.calendar.JDateChooser jDatedatavenda;
    private javax.swing.JDialog jDcliente;
    protected javax.swing.JDialog jDpesquisa;
    private javax.swing.JDialog jDvendedor;
    private javax.swing.JFormattedTextField jFrecebvalortitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JRadioButton jRaberto;
    private javax.swing.JRadioButton jRdapelido;
    private javax.swing.JRadioButton jRdcpf_cnpj;
    private javax.swing.JRadioButton jRdnome;
    private javax.swing.JRadioButton jRpago;
    private javax.swing.JRadioButton jRpapagar;
    private javax.swing.JRadioButton jRppago;
    private javax.swing.JRadioButton jRptodos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTAobs;
    protected javax.swing.JTable jTdconta;
    private javax.swing.JTextField jTdidpessoa;
    private javax.swing.JTextField jTdidvendedor;
    private javax.swing.JTextField jTdpesquisacliente;
    protected javax.swing.JTextField jTdpesquisaconta;
    private javax.swing.JTextField jTdpesquisavendedor;
    private javax.swing.JTable jTdpessoa;
    private javax.swing.JTable jTdvendedor;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTrecebcliente;
    private javax.swing.JTextField jTrecebcnpj;
    private javax.swing.JTextField jTrecebidreceber;
    private javax.swing.JTextField jTrecebndocumento;
    private javax.swing.JTextField jTrecebnorcamento;
    private javax.swing.JTextField jTrecebvendedor;
    private org.jdesktop.swingx.JXPanel jXPanel1;
    // End of variables declaration//GEN-END:variables
}
