/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atmatech.sac.view;

import br.com.atmatech.sac.beans.VeiculoBeans;
import br.com.atmatech.sac.controller.NivelAcesso;
import br.com.atmatech.sac.dao.VeiculoDao;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCOS
 */
public class ViewVeiculo extends javax.swing.JPanel {

    /**
     * Creates new form ViewModulo
     */
    List<VeiculoBeans> lvb;

    public ViewVeiculo() {
        initComponents();
        jTidveiculo.setVisible(false);
        jTkmatual.setText("0,000");
        buscaveiculo();
        permissaoUsuario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jBnovo = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTmodelo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCmarca = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jTplaca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTperiodo = new javax.swing.JTextField();
        jCmonitor = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jTtrocafin = new javax.swing.JTextField();
        jBtroca = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jTtrocaini = new javax.swing.JTextField();
        jTidveiculo = new javax.swing.JTextField();
        jTkmatual = new javax.swing.JFormattedTextField();
        jCativo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtveiculo = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(799, 613));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Add.png"))); // NOI18N
        jBnovo.setText("Novo");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jBsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Valid Blue.png"))); // NOI18N
        jBsalvar.setText("Salvar");
        jBsalvar.setEnabled(false);
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Attention.png"))); // NOI18N
        jBalterar.setText("Alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Remove Red.png"))); // NOI18N
        jBexcluir.setText("Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Loop Off.png"))); // NOI18N
        jBcancelar.setText("Cancelar");
        jBcancelar.setEnabled(false);
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBnovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBsalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBalterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBexcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBcancelar)
                .addContainerGap(158, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBalterar, jBcancelar, jBexcluir, jBnovo, jBsalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnovo)
                    .addComponent(jBsalvar)
                    .addComponent(jBalterar)
                    .addComponent(jBexcluir)
                    .addComponent(jBcancelar))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBalterar, jBcancelar, jBexcluir, jBnovo, jBsalvar});

        jPanel2.setPreferredSize(new java.awt.Dimension(779, 294));

        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Modelo:");

        jTmodelo.setEditable(false);
        jTmodelo.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));

        jLabel2.setText("Marca:");

        jCmarca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "HONDA", "YAMAHA", "SUZUKI", "DAFRA", "KASINSKI", "TRAXX", "SHINERAY", "SUNDOWN" }));
        jCmarca.setEnabled(false);

        jLabel3.setText("Placa:");

        jTplaca.setEditable(false);
        jTplaca.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(7,true));

        jLabel4.setText("KM Atual:");

        jLabel5.setText("Periodo:");

        jTperiodo.setEditable(false);
        jTperiodo.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(15,false));
        jTperiodo.setText("0");

        jCmonitor.setText("Monitorar Troca de Oleo");
        jCmonitor.setEnabled(false);

        jLabel6.setText("Proxima Troca:");

        jTtrocafin.setEditable(false);
        jTtrocafin.setText("0,000");

        jBtroca.setText("Troca");
        jBtroca.setEnabled(false);

        jLabel7.setText("Troca:");

        jTtrocaini.setEditable(false);
        jTtrocaini.setText("0,000");

        jTidveiculo.setEnabled(false);

        jTkmatual.setEditable(false);
        jTkmatual.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0.000"))));
        jTkmatual.setText("0000");

        jCativo.setSelected(true);
        jCativo.setText("Ativo");
        jCativo.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jTkmatual, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTmodelo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCmarca, javax.swing.GroupLayout.Alignment.LEADING, 0, 257, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTplaca, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(jTperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jCmonitor)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jCativo))
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addGap(0, 40, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTtrocafin)
                                            .addComponent(jTtrocaini, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtroca)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTidveiculo)))))
                        .addGap(115, 115, 115))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(2, 2, 2)
                        .addComponent(jTmodelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTperiodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCmonitor)
                            .addComponent(jCativo))))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel7))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCmarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTtrocaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(2, 2, 2)
                        .addComponent(jTplaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTtrocafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtroca)
                            .addComponent(jTidveiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addGap(2, 2, 2)
                .addComponent(jTkmatual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );

        jTtveiculo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "MODELO", "MARCA", "PLACA", "KM ATUAL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTtveiculo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTtveiculoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTtveiculo);
        if (jTtveiculo.getColumnModel().getColumnCount() > 0) {
            jTtveiculo.getColumnModel().getColumn(0).setResizable(false);
            jTtveiculo.getColumnModel().getColumn(1).setResizable(false);
            jTtveiculo.getColumnModel().getColumn(2).setResizable(false);
            jTtveiculo.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
        ativaSalvarCancelar();
        ativaView();
        limpaView();
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        if (validaCampos()) {
            if (jTidveiculo.getText().equals("")) {
                cadastrarVeiculo();
            } else {
                alterarVeiculo();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Há Campos Obrigatorios", "Salvar", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // TODO add your handling code here:
        if (!jTidveiculo.getText().equals("")) {
            ativaView();
            ativaSalvarCancelar();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Registro", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        // TODO add your handling code here:
        if (!jTidveiculo.getText().equals("")) {
            excluiVeiculo();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Registro", "Atenção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed
        // TODO add your handling code here:
        desativaView();
        limpaView();
        ativaNovoAlterarExcluir();
    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jTtveiculoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTtveiculoMouseClicked
        // TODO add your handling code here:
        clickVeiculo();
    }//GEN-LAST:event_jTtveiculoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JButton jBtroca;
    private javax.swing.JCheckBox jCativo;
    private javax.swing.JComboBox jCmarca;
    private javax.swing.JCheckBox jCmonitor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTidveiculo;
    private javax.swing.JFormattedTextField jTkmatual;
    private javax.swing.JTextField jTmodelo;
    private javax.swing.JTextField jTperiodo;
    private javax.swing.JTextField jTplaca;
    private javax.swing.JTextField jTtrocafin;
    private javax.swing.JTextField jTtrocaini;
    private javax.swing.JTable jTtveiculo;
    // End of variables declaration//GEN-END:variables
private void ativaView() {
        jTmodelo.setEditable(true);
        jTperiodo.setEditable(true);
        jCmonitor.setEnabled(true);
        jCmarca.setEnabled(true);
        jTplaca.setEditable(true);
        jTkmatual.setEditable(true);
        jBtroca.setEnabled(true);
        jTtveiculo.setEnabled(false);
        jTtveiculo.clearSelection();
        jCativo.setEnabled(true);
    }

    private void desativaView() {
        jTmodelo.setEditable(false);
        jTperiodo.setEditable(false);
        jCmonitor.setEnabled(false);
        jCmarca.setEnabled(false);
        jTplaca.setEditable(false);
        jTkmatual.setEditable(false);
        jBtroca.setEnabled(false);
        jTtveiculo.setEnabled(true);
        jCativo.setEnabled(false);

    }

    private void limpaView() {
        jTmodelo.setText("");
        jTperiodo.setText("0");
        jCmonitor.setSelected(false);
        jCmarca.setSelectedIndex(0);
        jTtrocaini.setText("0,000");
        jTplaca.setText("");
        jTtrocafin.setText("0,000");
        jTkmatual.setText("0,000");
        jTidveiculo.setText("");
        jCativo.setSelected(true);
    }

    private void ativaSalvarCancelar() {
        jBnovo.setEnabled(false);
        jBalterar.setEnabled(false);
        jBcancelar.setEnabled(true);
        jBexcluir.setEnabled(false);
        jBsalvar.setEnabled(true);
    }

    private void ativaNovoAlterarExcluir() {
        jBnovo.setEnabled(true);
        jBalterar.setEnabled(true);
        jBcancelar.setEnabled(false);
        jBexcluir.setEnabled(true);
        jBsalvar.setEnabled(false);
    }

    private void cadastrarVeiculo() {
        try {
            VeiculoBeans vb = new VeiculoBeans();
            vb.setModelo(jTmodelo.getText());
            vb.setPeriodo(Integer.valueOf(jTperiodo.getText()));
            vb.setMonitor(jCmonitor.isSelected());
            vb.setMarca(jCmarca.getItemAt(jCmarca.getSelectedIndex()).toString());
            vb.setTrocaini(Double.valueOf(jTtrocaini.getText().replace(",", ".")));
            vb.setTrocafin(Double.valueOf(jTtrocafin.getText().replace(",", ".")));
            vb.setPlaca(jTplaca.getText());
            vb.setKm(Double.valueOf(jTkmatual.getText().replace(",", ".")));
            vb.setAtivo(jCativo.isSelected());
            new VeiculoDao().setVeiculo(vb);

            limpaView();
            desativaView();
            ativaNovoAlterarExcluir();
            buscaveiculo();
            JOptionPane.showMessageDialog(this, "Registro Salvo com Sucesso.", "Salvar", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Salvar\n" + ex, "Salvar", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Salvar\n" + ex, "Salvar", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void alterarVeiculo() {
        try {
            VeiculoBeans vb = new VeiculoBeans();
            vb.setModelo(jTmodelo.getText());
            vb.setPeriodo(Integer.valueOf(jTperiodo.getText()));
            vb.setMonitor(jCmonitor.isSelected());
            vb.setMarca(jCmarca.getItemAt(jCmarca.getSelectedIndex()).toString());
            vb.setTrocaini(Double.valueOf(jTtrocaini.getText().replace(",", ".")));
            vb.setTrocafin(Double.valueOf(jTtrocafin.getText().replace(",", ".")));
            vb.setPlaca(jTplaca.getText());
            vb.setKm(Double.valueOf(jTkmatual.getText().replace(",", ".")));
            vb.setAtivo(jCativo.isSelected());
            vb.setIdveiculo(Integer.valueOf(jTidveiculo.getText()));
            new VeiculoDao().updateVeiculo(vb);
            limpaView();
            desativaView();
            ativaNovoAlterarExcluir();
            buscaveiculo();
            JOptionPane.showMessageDialog(this, "Registro Alterado com Sucesso.", "Alterar", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Alterar\n" + ex, "Alterar", JOptionPane.ERROR_MESSAGE);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Alterar\n" + ex, "Alterar", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void excluiVeiculo() {
        try {
            new VeiculoDao().deleteVeiculo(Integer.valueOf(jTidveiculo.getText()));
            limpaView();
            desativaView();
            ativaNovoAlterarExcluir();
            buscaveiculo();
            JOptionPane.showMessageDialog(this, "Registro Excluido com Sucesso.", "Excluir", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Excluir\n" + ex, "Excluir", JOptionPane.ERROR_MESSAGE);
        }
    }

    private boolean validaCampos() {
        return !jTmodelo.getText().equals("");
    }

    private void buscaveiculo() {
        lvb = new VeiculoDao().getVeiculo();
        DefaultTableModel tabelaveiculo = (DefaultTableModel) jTtveiculo.getModel();
        tabelaveiculo.setNumRows(0);
        for (VeiculoBeans vb : lvb) {
            tabelaveiculo.addRow(new Object[]{vb.getModelo(), vb.getMarca(), vb.getPlaca(), vb.getKm()});
        }
    }

    private void clickVeiculo() {
        for (int i = 0; i < lvb.size(); i++) {
            if (jTtveiculo.getSelectedRow() == i) {
                jTmodelo.setText(lvb.get(i).getModelo());
                jTperiodo.setText(lvb.get(i).getPeriodo().toString());
                jCmonitor.setSelected(lvb.get(i).isMonitor());
                jCativo.setSelected(lvb.get(i).isAtivo());
                jCmarca.setSelectedItem(lvb.get(i).getMarca());
                jTtrocaini.setText(String.valueOf(lvb.get(i).getTrocaini()).replace(".", ","));
                jTplaca.setText(lvb.get(i).getPlaca());
                jTtrocafin.setText(String.valueOf(lvb.get(i).getTrocafin()).replace(".", ","));
                jTidveiculo.setText(lvb.get(i).getIdveiculo().toString());
                jTkmatual.setText(String.valueOf(lvb.get(i).getKm()).replace(".", ","));
            }
        }
    }

    private void permissaoUsuario() {
        int ver=0;
        if(!new NivelAcesso().getAcesso("ViewVeiculo","alterar",false)){
            jBalterar.setVisible(false); 
            ver++;
        }
        if(!new NivelAcesso().getAcesso("ViewVeiculo","excluir",false)){
            jBexcluir.setVisible(false); 
            ver++;
        }
        if(!new NivelAcesso().getAcesso("ViewVeiculo","cadastrar",false)){
            jBnovo.setVisible(false);
            ver++;
        }
        if(ver==3){
            jPanel1.setVisible(false);
        }
    }
}
