/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atmatech.sac.view;

import br.com.atmatech.sac.beans.DBConfigBeans;
import br.com.atmatech.sac.beans.EmpresaBeans;
import br.com.atmatech.sac.beans.ListPerUsuarioBeans;
import br.com.atmatech.sac.beans.UsuarioBeans;
import br.com.atmatech.sac.beans.UsuarioLogadoBeans;
import br.com.atmatech.sac.config.DBConfig;
import br.com.atmatech.sac.controller.Versao;
import br.com.atmatech.sac.dao.EmpresaDao;
import br.com.atmatech.sac.dao.PerusuarioDao;
import br.com.atmatech.sac.dao.UsuarioDao;
import com.nilo.plaf.nimrod.NimRODLookAndFeel;
import com.nilo.plaf.nimrod.NimRODTheme;
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JColorChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCOS
 */
public class ViewLogin extends javax.swing.JFrame {

    /**
     * Creates new form ViewLogin
     */
    final Integer versao = 1;
    final Integer edicao = 4;
    final Integer seguranca = 12;
    List<EmpresaBeans>leb=new ArrayList<>();

    public ViewLogin() {
        initComponents();
        jTusuario.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDconfig = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTcaminhobd = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTusuariobd = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTsenhabd = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jThost = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jTusuariofin = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTsenhafin = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPprimaria1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPprimaria2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPprimaria3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPsecundaria1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jPsecundaria2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPsecundaria3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        JPwhite = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPblack = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSopacidademenu = new javax.swing.JSlider();
        jLmenu = new javax.swing.JLabel();
        jLframe = new javax.swing.JLabel();
        jSopacidadeframe = new javax.swing.JSlider();
        jButton5 = new javax.swing.JButton();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMconfiguracao = new javax.swing.JMenuItem();
        jMempresa = new javax.swing.JMenuItem();
        jDempresa = new javax.swing.JDialog();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTtdempresa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTusuario = new javax.swing.JTextField();
        jPsenha = new javax.swing.JPasswordField();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBopcao = new javax.swing.JButton();
        jLempresa = new javax.swing.JLabel();

        jDconfig.setTitle("Configuraçao");
        jDconfig.setMinimumSize(new java.awt.Dimension(565, 375));
        jDconfig.setModal(true);
        jDconfig.setResizable(false);

        jTabbedPane1.setName(""); // NOI18N

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Banco de Dados"));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel3.setText("Caminho:");

        jTcaminhobd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel12.setText("Usuario:");

        jTusuariobd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel13.setText("Senha:");

        jTsenhabd.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel16.setText("Host:");

        jThost.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTcaminhobd)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTusuariobd, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                        .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jTsenhabd, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jThost))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addGap(1, 1, 1)
                .addComponent(jTcaminhobd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTusuariobd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTsenhabd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jThost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 11, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema Financeiro"));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel14.setText("Usuario:");

        jTusuariofin.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel15.setText("Senha:");

        jTsenhafin.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addComponent(jTusuariofin, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jTsenhafin, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTusuariofin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTsenhafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Configuração", jPanel8);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Seleção,Linha de Menu, Barras Leterais"));

        jLabel4.setText("Barra:");

        jPprimaria1.setBackground(new java.awt.Color(204, 51, 0));
        jPprimaria1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPprimaria1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPprimaria1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPprimaria1Layout = new javax.swing.GroupLayout(jPprimaria1);
        jPprimaria1.setLayout(jPprimaria1Layout);
        jPprimaria1Layout.setHorizontalGroup(
            jPprimaria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        jPprimaria1Layout.setVerticalGroup(
            jPprimaria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel5.setText("Seleçao:");

        jPprimaria2.setBackground(new java.awt.Color(204, 51, 0));
        jPprimaria2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPprimaria2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPprimaria2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPprimaria2Layout = new javax.swing.GroupLayout(jPprimaria2);
        jPprimaria2.setLayout(jPprimaria2Layout);
        jPprimaria2Layout.setHorizontalGroup(
            jPprimaria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        jPprimaria2Layout.setVerticalGroup(
            jPprimaria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel6.setText("Menu:");

        jPprimaria3.setBackground(new java.awt.Color(204, 51, 0));
        jPprimaria3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPprimaria3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPprimaria3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPprimaria3Layout = new javax.swing.GroupLayout(jPprimaria3);
        jPprimaria3.setLayout(jPprimaria3Layout);
        jPprimaria3Layout.setHorizontalGroup(
            jPprimaria3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        jPprimaria3Layout.setVerticalGroup(
            jPprimaria3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPprimaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPprimaria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPprimaria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jPprimaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jPprimaria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jPprimaria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Cortornos,Background"));
        jPanel5.setPreferredSize(new java.awt.Dimension(478, 336));

        jLabel7.setText("Botões:");

        jPsecundaria1.setBackground(new java.awt.Color(204, 51, 0));
        jPsecundaria1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPsecundaria1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPsecundaria1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPsecundaria1Layout = new javax.swing.GroupLayout(jPsecundaria1);
        jPsecundaria1.setLayout(jPsecundaria1Layout);
        jPsecundaria1Layout.setHorizontalGroup(
            jPsecundaria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        jPsecundaria1Layout.setVerticalGroup(
            jPsecundaria1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jLabel8.setText("Painel:");

        jPsecundaria2.setBackground(new java.awt.Color(204, 51, 0));
        jPsecundaria2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPsecundaria2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPsecundaria2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPsecundaria2Layout = new javax.swing.GroupLayout(jPsecundaria2);
        jPsecundaria2.setLayout(jPsecundaria2Layout);
        jPsecundaria2Layout.setHorizontalGroup(
            jPsecundaria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        jPsecundaria2Layout.setVerticalGroup(
            jPsecundaria2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel9.setText("Frame:");

        jPsecundaria3.setBackground(new java.awt.Color(204, 51, 0));
        jPsecundaria3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPsecundaria3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPsecundaria3MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPsecundaria3Layout = new javax.swing.GroupLayout(jPsecundaria3);
        jPsecundaria3.setLayout(jPsecundaria3Layout);
        jPsecundaria3Layout.setHorizontalGroup(
            jPsecundaria3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        jPsecundaria3Layout.setVerticalGroup(
            jPsecundaria3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel10.setText("Edição:");

        JPwhite.setBackground(new java.awt.Color(204, 51, 0));
        JPwhite.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        JPwhite.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JPwhiteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout JPwhiteLayout = new javax.swing.GroupLayout(JPwhite);
        JPwhite.setLayout(JPwhiteLayout);
        JPwhiteLayout.setHorizontalGroup(
            JPwhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        JPwhiteLayout.setVerticalGroup(
            JPwhiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        jLabel11.setText("Fonte:");

        jPblack.setBackground(new java.awt.Color(204, 51, 0));
        jPblack.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPblack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPblackMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPblackLayout = new javax.swing.GroupLayout(jPblack);
        jPblack.setLayout(jPblackLayout);
        jPblackLayout.setHorizontalGroup(
            jPblackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 33, Short.MAX_VALUE)
        );
        jPblackLayout.setVerticalGroup(
            jPblackLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 22, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPsecundaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPsecundaria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPsecundaria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPwhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPblack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jPblack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10)
                    .addComponent(JPwhite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jPsecundaria1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jPsecundaria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jPsecundaria3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Opacidade"));

        jSopacidademenu.setMaximum(200);
        jSopacidademenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jSopacidademenuMousePressed(evt);
            }
        });
        jSopacidademenu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSopacidademenuMouseDragged(evt);
            }
        });

        jLmenu.setText("Menu:");

        jLframe.setText("Frame:");

        jSopacidadeframe.setMaximum(200);
        jSopacidadeframe.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jSopacidadeframeMouseDragged(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSopacidademenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLmenu)))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLframe)
                    .addComponent(jSopacidadeframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLmenu)
                    .addComponent(jLframe))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSopacidademenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSopacidadeframe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cores", jPanel7);

        jButton5.setText("Aplicar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDconfigLayout = new javax.swing.GroupLayout(jDconfig.getContentPane());
        jDconfig.getContentPane().setLayout(jDconfigLayout);
        jDconfigLayout.setHorizontalGroup(
            jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDconfigLayout.createSequentialGroup()
                .addGroup(jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDconfigLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDconfigLayout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addComponent(jButton5)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jDconfigLayout.setVerticalGroup(
            jDconfigLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDconfigLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName("Cores");

        jMconfiguracao.setText("Configuração");
        jMconfiguracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMconfiguracaoActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMconfiguracao);

        jMempresa.setText("Empresa");
        jMempresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMempresaActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMempresa);

        jDempresa.setTitle("Empresa");
        jDempresa.setMinimumSize(new java.awt.Dimension(538, 249));
        jDempresa.setModal(true);
        jDempresa.setResizable(false);
        jDempresa.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDempresaWindowOpened(evt);
            }
        });
        jDempresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jDempresaKeyPressed(evt);
            }
        });

        jTtdempresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "FANTASIA", "RAZAO", "CNPJ", "CIDADE", "ENDERECO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTtdempresa.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTtdempresa.getTableHeader().setReorderingAllowed(false);
        jTtdempresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTtdempresaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jTtdempresaMouseEntered(evt);
            }
        });
        jTtdempresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTtdempresaKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jTtdempresa);
        if (jTtdempresa.getColumnModel().getColumnCount() > 0) {
            jTtdempresa.getColumnModel().getColumn(0).setResizable(false);
            jTtdempresa.getColumnModel().getColumn(0).setPreferredWidth(200);
            jTtdempresa.getColumnModel().getColumn(1).setMinWidth(200);
            jTtdempresa.getColumnModel().getColumn(1).setPreferredWidth(200);
            jTtdempresa.getColumnModel().getColumn(2).setMinWidth(120);
            jTtdempresa.getColumnModel().getColumn(2).setPreferredWidth(120);
            jTtdempresa.getColumnModel().getColumn(3).setMinWidth(200);
            jTtdempresa.getColumnModel().getColumn(3).setPreferredWidth(200);
            jTtdempresa.getColumnModel().getColumn(4).setMinWidth(300);
            jTtdempresa.getColumnModel().getColumn(4).setPreferredWidth(300);
        }

        javax.swing.GroupLayout jDempresaLayout = new javax.swing.GroupLayout(jDempresa.getContentPane());
        jDempresa.getContentPane().setLayout(jDempresaLayout);
        jDempresaLayout.setHorizontalGroup(
            jDempresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDempresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 518, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDempresaLayout.setVerticalGroup(
            jDempresaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDempresaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("SAC");
        setMinimumSize(new java.awt.Dimension(360, 260));
        setUndecorated(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setText("Usuario:");

        jLabel2.setText("Senha:");

        jTusuario.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));

        jPsenha.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPsenhaKeyPressed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Valid Green.png"))); // NOI18N
        jButton1.setText("Confirma");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Cancel.png"))); // NOI18N
        jButton2.setText("Sair");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBopcao.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Smart.png"))); // NOI18N
        jBopcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBopcaoActionPerformed(evt);
            }
        });

        jLempresa.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPsenha))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jBopcao, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLempresa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(122, 122, 122))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBopcao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLempresa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTusuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPsenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(514, 246));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //TODO add your handling code here:                 
        logar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBopcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBopcaoActionPerformed
        // TODO add your handling code here:
        jPopupMenu1.show(jBopcao, WIDTH, jBopcao.getHeight());
    }//GEN-LAST:event_jBopcaoActionPerformed

    private void jPsenhaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPsenhaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == evt.VK_ENTER) {
            logar();
        }
    }//GEN-LAST:event_jPsenhaKeyPressed

    private void jPprimaria1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPprimaria1MouseClicked
        // TODO add your handling code here:        
        jPprimaria1.setBackground(selecionaCor());
    }//GEN-LAST:event_jPprimaria1MouseClicked

    private void jPprimaria2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPprimaria2MouseClicked
        // TODO add your handling code here:
        jPprimaria2.setBackground(selecionaCor());
    }//GEN-LAST:event_jPprimaria2MouseClicked

    private void jPprimaria3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPprimaria3MouseClicked
        // TODO add your handling code here:
        jPprimaria3.setBackground(selecionaCor());
    }//GEN-LAST:event_jPprimaria3MouseClicked

    private void jPsecundaria1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPsecundaria1MouseClicked
        // TODO add your handling code here:
        jPsecundaria1.setBackground(selecionaCor());
    }//GEN-LAST:event_jPsecundaria1MouseClicked

    private void jPsecundaria2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPsecundaria2MouseClicked
        // TODO add your handling code here:
        jPsecundaria2.setBackground(selecionaCor());
    }//GEN-LAST:event_jPsecundaria2MouseClicked

    private void jPsecundaria3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPsecundaria3MouseClicked
        // TODO add your handling code here:
        jPsecundaria3.setBackground(selecionaCor());
    }//GEN-LAST:event_jPsecundaria3MouseClicked

    private void JPwhiteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JPwhiteMouseClicked
        // TODO add your handling code here:
        JPwhite.setBackground(selecionaCor());
    }//GEN-LAST:event_JPwhiteMouseClicked

    private void jPblackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPblackMouseClicked
        // TODO add your handling code here:
        jPblack.setBackground(selecionaCor());
    }//GEN-LAST:event_jPblackMouseClicked

    private void jSopacidademenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSopacidademenuMousePressed
        // TODO add your handling code here:

    }//GEN-LAST:event_jSopacidademenuMousePressed

    private void jSopacidademenuMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSopacidademenuMouseDragged
        // TODO add your handling code here:
        jLmenu.setText("Menu:" + jSopacidademenu.getValue());
    }//GEN-LAST:event_jSopacidademenuMouseDragged

    private void jSopacidadeframeMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jSopacidadeframeMouseDragged
        // TODO add your handling code here:
        jLframe.setText("Frame:" + jSopacidadeframe.getValue());
    }//GEN-LAST:event_jSopacidadeframeMouseDragged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        alteraConfig();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:        
        try {
            jTusuario.requestFocusInWindow();
            DBConfigBeans dbcb = new DBConfigBeans();
            dbcb.setUsehost("local");
           if (!new Versao().verificaVersao(versao, edicao, seguranca)) {
                jButton1.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Versão Incompativel com Servidor");
                try {
                    Runtime.getRuntime().exec("cmd.exe /c java -jar srv.jar i");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao Atualizar\n" + ex);
                }
                System.exit(0);
           }
            jPanel1.setBorder(BorderFactory.createTitledBorder("LOGIN V-" + versao + "." + edicao + "." + seguranca + " BETA"));
            buscaEmpresa(dbcb.getCompany());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Verificar Versão\nTentando Conexão Pelo Host Remoto\n" + ex, "Versão", JOptionPane.ERROR_MESSAGE);
            connectionHostHemoto();      
    }
    }//GEN-LAST:event_formWindowOpened

    private void jMconfiguracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMconfiguracaoActionPerformed
        // TODO add your handling code here:
        carregaDados();
        jDconfig.setLocationRelativeTo(null);
        jDconfig.setVisible(true);
    }//GEN-LAST:event_jMconfiguracaoActionPerformed

    private void jTtdempresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTtdempresaMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            clienteSelecionado();
        }
    }//GEN-LAST:event_jTtdempresaMouseClicked

    private void jTtdempresaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTtdempresaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtdempresaMouseEntered

    private void jTtdempresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtdempresaKeyPressed
        // TODO add your handling code here:
       
        if ((evt.getKeyCode() == KeyEvent.VK_F)) {
            if (evt.isControlDown()) {
                atalhoBuscaCliente();
            }
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            clienteSelecionado();
        }
    }//GEN-LAST:event_jTtdempresaKeyPressed

    private void jDempresaWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDempresaWindowOpened
        // TODO add your handling code here:
        atalhoBuscaCliente();
    }//GEN-LAST:event_jDempresaWindowOpened

    private void jDempresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jDempresaKeyPressed
        // TODO add your handling code here:
        if ((evt.getKeyCode() == KeyEvent.VK_F)) {
            if (evt.isControlDown()) {
                atalhoBuscaCliente();
            }
        }
    }//GEN-LAST:event_jDempresaKeyPressed

    private void jMempresaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMempresaActionPerformed
        // TODO add your handling code here:
        showJDempresa();
    }//GEN-LAST:event_jMempresaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
            UIManager.setLookAndFeel(new ViewLogin().getTema());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Ler Arquivo Config " + ex, "Erro Tema", JOptionPane.ERROR_MESSAGE);
        }

//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(ViewLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } 
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPwhite;
    private javax.swing.JButton jBopcao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JDialog jDconfig;
    private javax.swing.JDialog jDempresa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLempresa;
    private javax.swing.JLabel jLframe;
    private javax.swing.JLabel jLmenu;
    private javax.swing.JMenuItem jMconfiguracao;
    private javax.swing.JMenuItem jMempresa;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPblack;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPanel jPprimaria1;
    private javax.swing.JPanel jPprimaria2;
    private javax.swing.JPanel jPprimaria3;
    private javax.swing.JPanel jPsecundaria1;
    private javax.swing.JPanel jPsecundaria2;
    private javax.swing.JPanel jPsecundaria3;
    private javax.swing.JPasswordField jPsenha;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSlider jSopacidadeframe;
    private javax.swing.JSlider jSopacidademenu;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTcaminhobd;
    private javax.swing.JTextField jThost;
    private javax.swing.JTextField jTsenhabd;
    private javax.swing.JTextField jTsenhafin;
    private javax.swing.JTable jTtdempresa;
    private javax.swing.JTextField jTusuario;
    private javax.swing.JTextField jTusuariobd;
    private javax.swing.JTextField jTusuariofin;
    // End of variables declaration//GEN-END:variables

    private void carregaConfig() {
        try {
            DBConfigBeans cb = new DBConfig().getConfig();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro Ao Ler Arquivo de Configuração\n" + ex, "SAC", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void logar() {
        UsuarioBeans ub = new UsuarioBeans();
        ub = new UsuarioDao().getUsuario(jTusuario.getText(), new String(jPsenha.getPassword()).trim(), new DBConfigBeans().getCompany());
        if (ub.getIdusuario() != null) {
            UsuarioLogadoBeans ulb = new UsuarioLogadoBeans();
            ulb.setIdusuario(ub.getIdusuario());
            ulb.setLogin(ub.getLogin());
            ulb.setNome(ub.getNome());
            ulb.setTecnico(ub.getTecnico());
            ulb.setSenha(ub.getSenha());
            ulb.setVchamados(ub.getVchamados());
            ulb.setAlttecnico(ub.getAlttecnico());
            ulb.setSmtp(ub.getSmtp());
            ulb.setPorta(ub.getPorta());
            ulb.setSsl(ub.getSsl());
            ulb.setTls(ub.getTls());
            ulb.setEmail(ub.getEmail());
            ulb.setSenhaemail(ub.getSenhaemail());
            ulb.setAssinatura(ub.getAssinatura());
            ulb.setBconsulta(ub.getBconsulta());
            ulb.setRasaoemp(jLempresa.getText());
            //pega as permissoes do usuario
            List<ListPerUsuarioBeans> lpub = new ArrayList<>();
            lpub = new PerusuarioDao().getPerusuario(ub.getIdusuario());
            ListPerUsuarioBeans l1 = new ListPerUsuarioBeans();
            l1.setLupb(lpub);
            new ViewPrincipal().setVisible(true);
            ViewLogin.this.setVisible(false);
        } else {
            JOptionPane.showMessageDialog(this, "Usuario Não Encontrado", "Usuario", JOptionPane.INFORMATION_MESSAGE);
        }
    }

    private Color selecionaCor() {
        JColorChooser choose = new JColorChooser();
        Color cor = choose.showDialog(choose, "Selecione", Color.yellow);
        return cor;
    }

    private NimRODLookAndFeel getTema() {
        try {
            carregaConfig();
            NimRODTheme nt = new NimRODTheme();
            DBConfigBeans db = new DBConfigBeans();
            nt.setPrimary1(new Color(db.getPrimary1r(), db.getPrimary1g(), db.getPrimary1b()));
            nt.setPrimary2(new Color(db.getPrimary2r(), db.getPrimary2g(), db.getPrimary2b()));//cor da selecao
            nt.setPrimary3(new Color(db.getPrimary3r(), db.getPrimary3g(), db.getPrimary3b()));//cor da linha de menu
            nt.setSecondary1(new Color(db.getSecondary1r(), db.getSecondary1g(), db.getSecondary1b()));//cortono dos botoes
            nt.setSecondary2(new Color(db.getSecondary2r(), db.getSecondary2g(), db.getSecondary2b()));//contorno do painel
            nt.setSecondary3(new Color(db.getSecondary3r(), db.getSecondary3g(), db.getSecondary3b()));//background do frame
            nt.setWhite(new Color(db.getWhiter(), db.getWhiteg(), db.getWhiteb()));//COR DO FUNDO EDIÇÃO
            nt.setBlack(new Color(db.getBlackr(), db.getBlackg(), db.getBlackb()));//COR FONTE
            nt.setMenuOpacity(db.getMenuopacity()); //opacidade do menu
            nt.setFrameOpacity(db.getFrameopacity());
            NimRODLookAndFeel NimRODLF = new NimRODLookAndFeel();
            NimRODLF.setCurrentTheme(nt);
            return NimRODLF;
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Ler Arquivo Config" + ex, "Tema", JOptionPane.ERROR_MESSAGE);
            return null;
        }
    }

    private void setTema() {
        try {

            //seta o tema
            UIManager.setLookAndFeel(new ViewLogin().getTema());
            //atualiza em temo de execulsão
            javax.swing.SwingUtilities.updateComponentTreeUI(this);
            javax.swing.SwingUtilities.updateComponentTreeUI(jDconfig);
        } catch (UnsupportedLookAndFeelException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Ler Arquivo Config" + ex, "Tema", JOptionPane.ERROR_MESSAGE);
        }

    }

    private void carregaDados() {
        DBConfigBeans cb = new DBConfigBeans();
        jTusuariobd.setText(cb.getUser());
        jTsenhabd.setText(cb.getPassword());
        jTcaminhobd.setText(cb.getDirdb());
        jTusuariofin.setText(cb.getLogin());
        jTsenhafin.setText(cb.getSenha());
        jThost.setText(cb.getDirdbhost());
        jPprimaria1.setBackground(new Color(cb.getPrimary1r(), cb.getPrimary1g(), cb.getPrimary1b()));
        jPprimaria2.setBackground(new Color(cb.getPrimary2r(), cb.getPrimary2g(), cb.getPrimary2b()));
        jPprimaria3.setBackground(new Color(cb.getPrimary3r(), cb.getPrimary3g(), cb.getPrimary3b()));
        jPsecundaria1.setBackground(new Color(cb.getSecondary1r(), cb.getSecondary1g(), cb.getSecondary1b()));
        jPsecundaria2.setBackground(new Color(cb.getSecondary2r(), cb.getSecondary2g(), cb.getSecondary2b()));
        jPsecundaria3.setBackground(new Color(cb.getSecondary3r(), cb.getSecondary3g(), cb.getSecondary3b()));
        JPwhite.setBackground(new Color(cb.getWhiter(), cb.getWhiteg(), cb.getWhiteb()));
        jPblack.setBackground(new Color(cb.getBlackr(), cb.getBlackg(), cb.getBlackb()));
        jSopacidademenu.setValue(cb.getMenuopacity());
        jSopacidadeframe.setValue(cb.getFrameopacity());
        jLmenu.setText("Menu: " + cb.getMenuopacity());
        jLframe.setText("Frame: " + cb.getFrameopacity());

    }

    private void alteraConfig() {
        try {
            DBConfigBeans cb = new DBConfigBeans();
            cb.setDirdb(jTcaminhobd.getText());
            cb.setUser(jTusuariobd.getText());
            cb.setPassword(jTsenhabd.getText());
            cb.setLogin(jTusuariofin.getText());
            cb.setSenha(jTsenhafin.getText());
            cb.setDirdbhost(jThost.getText());

            cb.setPrimary1r(jPprimaria1.getBackground().getRed());
            cb.setPrimary1g(jPprimaria1.getBackground().getGreen());
            cb.setPrimary1b(jPprimaria1.getBackground().getBlue());
            cb.setPrimary2r(jPprimaria2.getBackground().getRed());
            cb.setPrimary2g(jPprimaria2.getBackground().getGreen());
            cb.setPrimary2b(jPprimaria2.getBackground().getBlue());
            cb.setPrimary3r(jPprimaria3.getBackground().getRed());
            cb.setPrimary3g(jPprimaria3.getBackground().getGreen());
            cb.setPrimary3b(jPprimaria3.getBackground().getBlue());
            cb.setSecondary1r(jPsecundaria1.getBackground().getRed());
            cb.setSecondary1g(jPsecundaria1.getBackground().getGreen());
            cb.setSecondary1b(jPsecundaria1.getBackground().getBlue());
            cb.setSecondary2r(jPsecundaria2.getBackground().getRed());
            cb.setSecondary2g(jPsecundaria2.getBackground().getGreen());
            cb.setSecondary2b(jPsecundaria2.getBackground().getBlue());
            cb.setSecondary3r(jPsecundaria3.getBackground().getRed());
            cb.setSecondary3b(jPsecundaria3.getBackground().getBlue());
            cb.setSecondary3g(jPsecundaria3.getBackground().getGreen());
            cb.setWhiter(JPwhite.getBackground().getRed());
            cb.setWhiteg(JPwhite.getBackground().getGreen());
            cb.setWhiteb(JPwhite.getBackground().getBlue());
            cb.setBlackr(jPblack.getBackground().getRed());
            cb.setBlackg(jPblack.getBackground().getGreen());
            cb.setBlackb(jPblack.getBackground().getBlue());
            cb.setMenuopacity(Integer.valueOf(jSopacidademenu.getValue()));
            cb.setFrameopacity(Integer.valueOf(jSopacidadeframe.getValue()));

            new DBConfig().createConfig(cb);
            setTema();
        } catch (IOException ex) {
            Logger.getLogger(ViewLogin.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void connectionHostHemoto() {
        try {
            jTusuario.requestFocusInWindow();
            DBConfigBeans dbcb = new DBConfigBeans();
            dbcb.setUsehost("remoto");
            if (!new Versao().verificaVersao(versao, edicao, seguranca)) {
                jPanel1.setBorder(BorderFactory.createTitledBorder("LOGIN V-" + versao + "." + edicao + "." + seguranca + " BETA"));
                jButton1.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Versão Incompativel com Servidor");
                try {
                    Runtime.getRuntime().exec("cmd.exe /c java -jar svr.jar i");
                } catch (IOException ex) {
                    JOptionPane.showMessageDialog(null, "Erro ao Atualizar\n" + ex);
                }
                System.exit(0);
            }
            jPanel1.setBorder(BorderFactory.createTitledBorder("LOGIN V-" + versao + "." + edicao + "." + seguranca + " BETA"));
            buscaEmpresa(dbcb.getCompany());
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Verificar Versão\n" + ex, "Versão", JOptionPane.ERROR_MESSAGE);
            System.exit(0);
        }
    }

    private void buscaEmpresa(Integer idempresa) {
        EmpresaBeans eb = new EmpresaBeans();
        eb = new EmpresaDao().getEmpresaAtivo(idempresa);
        if (eb != null) {
            jLempresa.setText(eb.getRazao());
        } else {
            JOptionPane.showMessageDialog(null, "Empresa não Emcontrada");
        }
    }

    public void showJDempresa() {
        //buscaCliente("fantasia", "", "fantasia");
        jDempresa.setLocationRelativeTo(this);
        jDempresa.setVisible(true);
    }

    private void atalhoBuscaCliente() {

        String text = JOptionPane.showInputDialog(jDempresa, "Pesquisa: ", "PESQUISA", JOptionPane.WARNING_MESSAGE);
        if (text != null) {

            text = text.toUpperCase();

            buscaEmpresa(text, "RAZAO");
        }

    }

    private void clienteSelecionado() {
        try {
            clickCliente();
            jDempresa.setVisible(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, "Erro\n"+ex);
        }
    }

    private void buscaEmpresa(String parametro, String ordenacao) {
        leb = new EmpresaDao().getEmpresa(ordenacao, parametro, ordenacao);
        DefaultTableModel tabelaempresa = (DefaultTableModel) jTtdempresa.getModel();
        tabelaempresa.setNumRows(0);
        for (EmpresaBeans pb : leb) {
            tabelaempresa.addRow(new Object[]{pb.getFantasia(), pb.getRazao(), pb.getCnpj(), pb.getDistrito(), pb.getEndereco()});
        }
    }
    private void clickCliente() throws IOException {
        for (int i = 0; i < leb.size(); i++) {
            if (i == jTtdempresa.getSelectedRow()) {
                jLempresa.setText(leb.get(i).getRazao());
                new UsuarioLogadoBeans().setIdempresa(leb.get(i).getIdempresa());
                new UsuarioLogadoBeans().setRasaoemp(leb.get(i).getRazao());
                new DBConfigBeans().setCompany(leb.get(i).getIdempresa());                
                new DBConfig().createConfig(new DBConfigBeans());
            }
        }
    }
}
