/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atmatech.sac.view;

import br.com.atmatech.sac.beans.DistritoBeans;
import br.com.atmatech.sac.beans.EmpresaBeans;
import br.com.atmatech.sac.beans.SituacaoBeans;
import br.com.atmatech.sac.dao.DistritoDao;
import br.com.atmatech.sac.dao.EmpresaDao;
import br.com.atmatech.sac.dao.SituacaoDao;
import br.com.atmatech.sac.webService.WebServiceCadastro;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.sql.SQLException;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCOS
 */
public class ViewEmpresa extends javax.swing.JPanel {

    /**
     * Creates new form ViewPessoa
     */
    List<SituacaoBeans> lsb;
    List<DistritoBeans> ldb;
    List<EmpresaBeans> lpb;
    JPanel TempViewPessoa = this;
    boolean inicializatela = false;

    public ViewEmpresa() {
        initComponents();
        // buscaDistrito();
        desativaColunas();
        // jTiddistrito.setVisible(false);
        jTidempresa.setVisible(false);
        jTiddistrito.setVisible(false);
        // buscaEmpresa();
        jDaguarde.setUndecorated(true);
        inicializaAtalhos();
        this.inicializatela = true;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDcidade = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTtcidade = new javax.swing.JTable();
        jTconsulta = new javax.swing.JTextField();
        jLindice = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jDaguarde = new javax.swing.JDialog();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTtempresa = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jBnovo = new javax.swing.JButton();
        jBsalvar = new javax.swing.JButton();
        jBalterar = new javax.swing.JButton();
        jBexcluir = new javax.swing.JButton();
        jBcancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTrazao = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTfantasia = new javax.swing.JTextField();
        jFcnpj = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTinscrição = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jFtelefone1 = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jFtelefone2 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jFtelefone3 = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jTendereco = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTnumero = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTcidade = new javax.swing.JTextField();
        jBcidade = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jCsituacao = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jTemail = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTobs = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTbairro = new javax.swing.JTextField();
        jTiddistrito = new javax.swing.JTextField();
        jTidempresa = new javax.swing.JTextField();
        jBcadcnpj = new javax.swing.JButton();
        jLabel19 = new javax.swing.JLabel();
        jTresponsavel = new javax.swing.JTextField();

        jDcidade.setTitle("Cidade");
        jDcidade.setMinimumSize(new java.awt.Dimension(635, 270));
        jDcidade.setModal(true);
        jDcidade.setResizable(false);

        jTtcidade.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDDISTRITO", "DISTRITO", "MUNICIPIO", "UF", "PAIS"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTtcidade.getTableHeader().setResizingAllowed(false);
        jTtcidade.getTableHeader().setReorderingAllowed(false);
        jTtcidade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTtcidadeMouseClicked(evt);
            }
        });
        jTtcidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTtcidadeKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jTtcidade);
        if (jTtcidade.getColumnModel().getColumnCount() > 0) {
            jTtcidade.getColumnModel().getColumn(0).setResizable(false);
            jTtcidade.getColumnModel().getColumn(1).setResizable(false);
            jTtcidade.getColumnModel().getColumn(2).setResizable(false);
            jTtcidade.getColumnModel().getColumn(3).setResizable(false);
            jTtcidade.getColumnModel().getColumn(4).setResizable(false);
        }

        jTconsulta.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(100,true));
        jTconsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTconsultaActionPerformed(evt);
            }
        });
        jTconsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTconsultaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTconsultaKeyReleased(evt);
            }
        });

        jLabel23.setForeground(new java.awt.Color(204, 0, 0));
        jLabel23.setText("F12 SELECIONA REGISTRO");

        javax.swing.GroupLayout jDcidadeLayout = new javax.swing.GroupLayout(jDcidade.getContentPane());
        jDcidade.getContentPane().setLayout(jDcidadeLayout);
        jDcidadeLayout.setHorizontalGroup(
            jDcidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDcidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDcidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 615, Short.MAX_VALUE)
                    .addComponent(jTconsulta)
                    .addGroup(jDcidadeLayout.createSequentialGroup()
                        .addComponent(jLindice, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel23)))
                .addContainerGap())
        );
        jDcidadeLayout.setVerticalGroup(
            jDcidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDcidadeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDcidadeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLindice, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTconsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jDcidade.getAccessibleContext().setAccessibleParent(null);

        jLabel16.setText("jLabel16");

        jDaguarde.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDaguarde.setMinimumSize(new java.awt.Dimension(247, 90));
        jDaguarde.setModal(true);
        jDaguarde.setResizable(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("AGUARDE....");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel21)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDaguardeLayout = new javax.swing.GroupLayout(jDaguarde.getContentPane());
        jDaguarde.getContentPane().setLayout(jDaguardeLayout);
        jDaguardeLayout.setHorizontalGroup(
            jDaguardeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDaguardeLayout.setVerticalGroup(
            jDaguardeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTtempresa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDEMPRESA", "RAZAO", "FANTASIA", "CNPJ", "ENDERECO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTtempresa.getTableHeader().setReorderingAllowed(false);
        jTtempresa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTtempresaMouseClicked(evt);
            }
        });
        jTtempresa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTtempresaKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTtempresa);
        if (jTtempresa.getColumnModel().getColumnCount() > 0) {
            jTtempresa.getColumnModel().getColumn(0).setResizable(false);
        }

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jBnovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Add.png"))); // NOI18N
        jBnovo.setText("F1-Novo");
        jBnovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnovoActionPerformed(evt);
            }
        });

        jBsalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Valid Blue.png"))); // NOI18N
        jBsalvar.setText("F2-Salvar");
        jBsalvar.setEnabled(false);
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jBalterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Attention.png"))); // NOI18N
        jBalterar.setText("F3-Alterar");
        jBalterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBalterarActionPerformed(evt);
            }
        });

        jBexcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Remove Red.png"))); // NOI18N
        jBexcluir.setText("F4-Excluir");
        jBexcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBexcluirActionPerformed(evt);
            }
        });

        jBcancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/Knob Loop Off.png"))); // NOI18N
        jBcancelar.setText("Cancelar");
        jBcancelar.setEnabled(false);
        jBcancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBnovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBsalvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBalterar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBexcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBcancelar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBalterar, jBcancelar, jBexcluir, jBnovo, jBsalvar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBnovo)
                    .addComponent(jBsalvar)
                    .addComponent(jBalterar)
                    .addComponent(jBexcluir)
                    .addComponent(jBcancelar))
                .addContainerGap())
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jBalterar, jBcancelar, jBexcluir, jBnovo, jBsalvar});

        jLabel1.setForeground(new java.awt.Color(255, 102, 102));
        jLabel1.setText("Razão:");

        jTrazao.setEditable(false);
        jTrazao.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));
        jTrazao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTrazaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Fantasia:");

        jTfantasia.setEditable(false);
        jTfantasia.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));

        jFcnpj.setEditable(false);
        jFcnpj.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(14,false));

        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("CNPJ:");

        jLabel4.setText("Inscrição:");

        jTinscrição.setEditable(false);
        jTinscrição.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(20,false));

        jLabel5.setText("Telefone 1:");

        jFtelefone1.setEditable(false);
        jFtelefone1.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(10,false));

        jLabel6.setText("Telefone 2:");

        jFtelefone2.setEditable(false);
        jFtelefone2.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(10,false));

        jLabel7.setText("Telefone 3:");

        jFtelefone3.setEditable(false);
        jFtelefone3.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(10,false));

        jLabel8.setText("Endereço:");

        jTendereco.setEditable(false);
        jTendereco.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));
        jTendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTenderecoActionPerformed(evt);
            }
        });

        jLabel10.setText("Numero:");

        jTnumero.setEditable(false);
        jTnumero.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(10,true));
        jTnumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTnumeroActionPerformed(evt);
            }
        });

        jLabel9.setForeground(new java.awt.Color(255, 102, 102));
        jLabel9.setText("Cidade:");

        jTcidade.setEditable(false);
        jTcidade.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(200,true));
        jTcidade.setEnabled(false);
        jTcidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTcidadeFocusLost(evt);
            }
        });

        jBcidade.setText("...");
        jBcidade.setEnabled(false);
        jBcidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcidadeActionPerformed(evt);
            }
        });

        jLabel11.setText("Situação");

        jCsituacao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ativo", "Inativo", "Bloqueado" }));
        jCsituacao.setEnabled(false);

        jLabel12.setText("E-mail:");

        jTemail.setEditable(false);
        jTemail.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));

        jTobs.setEditable(false);
        jTobs.setColumns(20);
        jTobs.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(600,true));
        jTobs.setLineWrap(true);
        jTobs.setRows(5);
        jScrollPane3.setViewportView(jTobs);

        jLabel14.setText("Observação:");

        jLabel15.setText("Bairro:");

        jTbairro.setEditable(false);
        jTbairro.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));
        jTbairro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTbairroActionPerformed(evt);
            }
        });

        jTiddistrito.setEditable(false);

        jTidempresa.setEditable(false);

        jBcadcnpj.setText("...");
        jBcadcnpj.setEnabled(false);
        jBcadcnpj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBcadcnpjActionPerformed(evt);
            }
        });

        jLabel19.setText("Responsável:");

        jTresponsavel.setEditable(false);
        jTresponsavel.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(20,true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jTrazao, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jFtelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBcadcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jTinscrição, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTresponsavel))
                            .addComponent(jTendereco, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTfantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jLabel10)
                                    .addComponent(jTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7)
                                    .addComponent(jFtelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(jFtelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9)
                                    .addComponent(jTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(2, 2, 2)
                                .addComponent(jBcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTidempresa)
                                    .addComponent(jTiddistrito))))))
                .addContainerGap(224, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jFtelefone1, jFtelefone2, jFtelefone3, jTcidade});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel11))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTrazao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFtelefone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCsituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(25, 25, 25)
                        .addComponent(jLabel7)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFtelefone3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTidempresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTfantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFtelefone2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(1, 1, 1)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTinscrição, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBcadcnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addGap(1, 1, 1)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTcidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBcidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTiddistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTbairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTnumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel19))
                        .addGap(2, 2, 2)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTresponsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10))
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jFtelefone1, jFtelefone2, jFtelefone3, jTcidade});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 167, Short.MAX_VALUE)
                .addGap(1, 1, 1))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTrazaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTrazaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTrazaoActionPerformed

    private void jTenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTenderecoActionPerformed

    private void jBnovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnovoActionPerformed
        // TODO add your handling code here:
        ativaView();
        ativaSalvarCancelar();
        limpaView();
    }//GEN-LAST:event_jBnovoActionPerformed

    private void jTnumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTnumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTnumeroActionPerformed

    private void jTbairroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTbairroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTbairroActionPerformed

    private void jBcidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcidadeActionPerformed
        // TODO add your handling code here:
        buscaDistrito();
        jLindice.setText("MUNICIPIO");
        this.jDcidade.setLocationRelativeTo(jPanel2);
        this.jDcidade.setVisible(true);


    }//GEN-LAST:event_jBcidadeActionPerformed

    private void jTconsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTconsultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTconsultaActionPerformed

    private void jTtcidadeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTtcidadeMouseClicked
        // TODO add your handling code here:
        jLindice.setText(jTtcidade.getColumnName(jTtcidade.getSelectedColumn()));
        jTconsulta.requestFocus();
    }//GEN-LAST:event_jTtcidadeMouseClicked

    private void jTconsultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTconsultaKeyReleased
        // TODO add your handling code here:
        buscaDistrito(jTconsulta.getText(), jLindice.getText());
    }//GEN-LAST:event_jTconsultaKeyReleased

    private void jTcidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTcidadeFocusLost
        // TODO add your handling code here:
        buscaDistrito(jTcidade.getText(), "DISTRITO");
        jLindice.setText("DISTRITO");
        jTconsulta.setText(jTcidade.getText());
        jDcidade.setLocationRelativeTo(null);
        jDcidade.setVisible(true);
    }//GEN-LAST:event_jTcidadeFocusLost

    private void jTtcidadeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtcidadeKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTtcidadeKeyPressed

    private void jTconsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTconsultaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_F12 && jTtcidade.getSelectedRow() > -1) {
            jTiddistrito.setText(jTtcidade.getValueAt(jTtcidade.getSelectedRow(), 0).toString());
            jTcidade.setText(jTtcidade.getValueAt(jTtcidade.getSelectedRow(), 1).toString());
            jDcidade.setVisible(false);
        }
    }//GEN-LAST:event_jTconsultaKeyPressed

    private void jBalterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBalterarActionPerformed
        // TODO add your handling code here:
        if (!jTidempresa.getText().equals("")) {
            ativaView();
            ativaSalvarCancelar();
        } else {
            JOptionPane.showMessageDialog(this, "Selecione um Registro", "Atenção", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBalterarActionPerformed

    private void jBexcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBexcluirActionPerformed
        try {
            // TODO add your handling code here:
            if (!jTidempresa.getText().equals("")) {
                if (JOptionPane.showConfirmDialog(null, "Deseja Excluir o Registro", "Atenção", JOptionPane.YES_NO_OPTION) == 0) {
                    new EmpresaDao().deleteEmpresa(Integer.valueOf(jTidempresa.getText()));
                    ativaNovoAlterarExcluir();
                    limpaView();
                    desativaView();
                    buscaEmpresa();
                    JOptionPane.showMessageDialog(this, "Registro Excluido", "Excluir", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(this, "Selecione um Registro", "Excluir", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Excluir" + ex, "Excluir", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_jBexcluirActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        if (validaCampos()) {
            if (jTidempresa.getText().equals("")) {
                salvaEmpresa();
            } else {
                alterarEmpresa();
            }
        } else {
            JOptionPane.showMessageDialog(this, "Há Campos Obrigatorios", "Salvar", JOptionPane.INFORMATION_MESSAGE);
        }


    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jBcancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcancelarActionPerformed

        // TODO add your handling code here:
        limpaView();
        desativaView();
        ativaNovoAlterarExcluir();


    }//GEN-LAST:event_jBcancelarActionPerformed

    private void jTtempresaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtempresaKeyPressed
        // TODO add your handling code here:

        int coluna = jTtempresa.getSelectedColumn();
        if ((evt.getKeyCode() == KeyEvent.VK_F) && (coluna >= 0)) {
            if (evt.isControlDown()) {
                String text = JOptionPane.showInputDialog(this, "Pesquisa: " + jTtempresa.getColumnName(coluna), "PESQUISA", JOptionPane.WARNING_MESSAGE);
                if (text != null) {
                    text = text.toUpperCase();
                    if (jTtempresa.getColumnName(coluna).equals("RAZAO")) {
                        buscaEmpresa("RAZAO", text);
                    }
                    if (jTtempresa.getColumnName(coluna).equals("FANTASIA")) {
                        buscaEmpresa("FANTASIA", text);
                    }
                    if (jTtempresa.getColumnName(coluna).equals("CNPJ")) {
                        buscaEmpresa("CNPJ", text);
                    }
                    if (jTtempresa.getColumnName(coluna).equals("ENDERECO")) {
                        buscaEmpresa("ENDERECO", text);
                    }
                }

            }
        }
    }//GEN-LAST:event_jTtempresaKeyPressed

    private void jTtempresaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTtempresaMouseClicked
        // TODO add your handling code here:
        clickEmpresa();
    }//GEN-LAST:event_jTtempresaMouseClicked

    private void jBcadcnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBcadcnpjActionPerformed

        new Thread(new Runnable() {

            @Override
            public void run() {
                try {
                    new Thread(new Runnable() {

                        @Override
                        public void run() {
                            showAguarde();
                        }
                    }).start();
                    // TODO add your handling code here:
                    EmpresaBeans pb = new EmpresaBeans();
                    pb = new WebServiceCadastro().postWebServiceEmp(jFcnpj.getText());
                    if (pb.getRazao() != null) {
                        jTrazao.setText(pb.getRazao());
                        jTinscrição.setText(pb.getIe());
                        jTendereco.setText(pb.getEndereco());
                        jTnumero.setText(pb.getNumero());
                        jTbairro.setText(pb.getBairro());
                        jFtelefone3.setText(pb.getTelefone1());
                        jDaguarde.setVisible(false);
                    } else {
                        jDaguarde.setVisible(false);
                        JOptionPane.showMessageDialog(null, "CNPJ Não Encontrado\n");
                    }
                } catch (IOException ex) {
                    jDaguarde.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Erro ao Conectar com Servidor\n" + ex);
                }
            }
        }).start();

    }//GEN-LAST:event_jBcadcnpjActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        if (inicializatela) {
            carregaPesquisa();
            inicializatela = false;
        }

    }//GEN-LAST:event_formComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBalterar;
    private javax.swing.JButton jBcadcnpj;
    private javax.swing.JButton jBcancelar;
    private javax.swing.JButton jBcidade;
    private javax.swing.JButton jBexcluir;
    private javax.swing.JButton jBnovo;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JComboBox jCsituacao;
    private javax.swing.JDialog jDaguarde;
    private javax.swing.JDialog jDcidade;
    private javax.swing.JFormattedTextField jFcnpj;
    private javax.swing.JFormattedTextField jFtelefone1;
    private javax.swing.JFormattedTextField jFtelefone2;
    private javax.swing.JFormattedTextField jFtelefone3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLindice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField jTbairro;
    private javax.swing.JTextField jTcidade;
    private javax.swing.JTextField jTconsulta;
    private javax.swing.JTextField jTemail;
    private javax.swing.JTextField jTendereco;
    private javax.swing.JTextField jTfantasia;
    private javax.swing.JTextField jTiddistrito;
    private javax.swing.JTextField jTidempresa;
    private javax.swing.JTextField jTinscrição;
    private javax.swing.JTextField jTnumero;
    public javax.swing.JTextArea jTobs;
    private javax.swing.JTextField jTrazao;
    private javax.swing.JTextField jTresponsavel;
    private javax.swing.JTable jTtcidade;
    private javax.swing.JTable jTtempresa;
    // End of variables declaration//GEN-END:variables
public void ativaView() {
        jBcadcnpj.setEnabled(true);
        jTrazao.setEditable(true);
        jTfantasia.setEditable(true);
        jFcnpj.setEditable(true);
        jTinscrição.setEditable(true);
        jTendereco.setEditable(true);
        jTnumero.setEditable(true);
        jTemail.setEditable(true);
        jFtelefone1.setEditable(true);
        jFtelefone2.setEditable(true);
        jFtelefone2.setEditable(true);
        jTcidade.setEditable(true);
        jTcidade.setEnabled(true);
        jTobs.setEditable(true);
        jCsituacao.setEnabled(true);
        jFtelefone3.setEditable(true);
        jTbairro.setEditable(true);
        jBcidade.setEnabled(true);
        jTtempresa.setEnabled(false);
        jTtempresa.clearSelection();
        jTresponsavel.setEditable(true);
    }

    public void desativaView() {
        jBcadcnpj.setEnabled(true);
        jTrazao.setEditable(false);
        jTfantasia.setEditable(false);
        jFcnpj.setEditable(false);
        jTinscrição.setEditable(false);
        jTendereco.setEditable(false);
        jTnumero.setEditable(false);
        jTemail.setEditable(false);
        jFtelefone1.setEditable(false);
        jFtelefone2.setEditable(false);
        jFtelefone2.setEditable(false);
        jTcidade.setEditable(false);
        jTcidade.setEnabled(false);
        jTobs.setEditable(false);
        jCsituacao.setEnabled(false);
        jFtelefone3.setEditable(false);
        jTbairro.setEditable(false);
        jBcidade.setEnabled(false);
        jTtempresa.setEnabled(true);
        jTresponsavel.setEditable(false);
    }

    private void buscaSituacao() {
        jCsituacao.removeAllItems();
        try {
            lsb = new SituacaoDao().getSituacao();
            for (SituacaoBeans sb : lsb) {
                jCsituacao.addItem(sb.getDescricao());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Erro ao Consultar Situação\n" + ex);
        }

    }

    private void buscaDistrito() {
        DefaultTableModel tcidade = (DefaultTableModel) jTtcidade.getModel();
        tcidade.setNumRows(0);
        ldb = new DistritoDao().getDistrito();
        for (DistritoBeans db : ldb) {
            tcidade.addRow(new Object[]{db.getIddistrito(), db.getDistrito(), db.getMunicipio(), db.getUf(), db.getPais()});
        }
    }

    private void buscaDistrito(String filtro, String campo) {
        DefaultTableModel tcidade = (DefaultTableModel) jTtcidade.getModel();
        tcidade.setNumRows(0);
        ldb = new DistritoDao().getDistrito(filtro, campo);
        for (DistritoBeans db : ldb) {
            tcidade.addRow(new Object[]{db.getIddistrito(), db.getDistrito(), db.getMunicipio(), db.getUf(), db.getPais()});
        }
    }

    private void ativaSalvarCancelar() {
        jBnovo.setEnabled(false);
        jBalterar.setEnabled(false);
        jBcancelar.setEnabled(true);
        jBexcluir.setEnabled(false);
        jBsalvar.setEnabled(true);
    }

    private void ativaNovoAlterarExcluir() {
        jBnovo.setEnabled(true);
        jBalterar.setEnabled(true);
        jBcancelar.setEnabled(false);
        jBexcluir.setEnabled(true);
        jBsalvar.setEnabled(false);
    }

    private void limpaView() {
        jTrazao.setText("");
        jTfantasia.setText("");
        jFcnpj.setText("");
        jTinscrição.setText("");
        jTendereco.setText("");
        jTnumero.setText("");
        jTemail.setText("");
        jFtelefone1.setText("");
        jFtelefone2.setText("");
        jFtelefone2.setText("");
        jTcidade.setText("");
        jTobs.setText("");
        jCsituacao.setSelectedIndex(0);
        jFtelefone3.setText("");
        jTbairro.setText("");
        //jBcidade.setText("");
        jTiddistrito.setText("");
        jTidempresa.setText("");
        jTresponsavel.setText("");
    }

    private void buscaEmpresa() {
        DefaultTableModel tabelaempresa = (DefaultTableModel) jTtempresa.getModel();
        tabelaempresa.setNumRows(0);
        lpb = new EmpresaDao().getEmpresa();
        for (EmpresaBeans pb : lpb) {
            tabelaempresa.addRow(new Object[]{pb.getIdempresa(), pb.getRazao(), pb.getFantasia(), pb.getCnpj(), pb.getEndereco()});
        }
    }

    private void buscaEmpresa(String coluna, String parametro) {
        DefaultTableModel tabelaempresa = (DefaultTableModel) jTtempresa.getModel();
        tabelaempresa.setNumRows(0);
        lpb = new EmpresaDao().getEmpresa(coluna, parametro, coluna);
        for (EmpresaBeans pb : lpb) {
            tabelaempresa.addRow(new Object[]{pb.getIdempresa(), pb.getRazao(), pb.getFantasia(), pb.getCnpj(), pb.getEndereco()});
        }
        if (tabelaempresa.getRowCount() == 0) {
            tabelaempresa.addRow(new Object[]{});
        }
    }

    private void desativaColunas() {
        jTtcidade.getColumnModel().getColumn(0).setMaxWidth(0);
        jTtcidade.getColumnModel().getColumn(0).setMinWidth(0);
        jTtcidade.getColumnModel().getColumn(0).setPreferredWidth(0);

        jTtempresa.getColumnModel().getColumn(0).setMaxWidth(0);
        jTtempresa.getColumnModel().getColumn(0).setMinWidth(0);
        jTtempresa.getColumnModel().getColumn(0).setPreferredWidth(0);

    }

    private void salvaEmpresa() {
        try {
            EmpresaBeans pb = new EmpresaBeans();
            pb.setRazao(jTrazao.getText());
            pb.setFantasia(jTfantasia.getText());
            pb.setCnpj(jFcnpj.getText());
            pb.setIe(jTinscrição.getText());
            pb.setEndereco(jTendereco.getText());
            pb.setIddistrito(Integer.valueOf(jTiddistrito.getText()));
            pb.setNumero(jTnumero.getText());
            pb.setEmail(jTemail.getText());
            pb.setTelefone1(jFtelefone1.getText());
            pb.setTelefone2(jFtelefone2.getText());
            pb.setTelefone3(jFtelefone3.getText());
            pb.setIdsituacao(lsb.get(jCsituacao.getSelectedIndex()).getIdsituacao());
            pb.setObs(jTobs.getText());
            pb.setBairro(jTbairro.getText());
            pb.setResponsavel(jTresponsavel.getText());
            EmpresaDao pd = new EmpresaDao();
            pd.setEmpresa(pb);
            JOptionPane.showMessageDialog(this, "Registro Salvo com Sucesso.", "Salvar", JOptionPane.INFORMATION_MESSAGE);
            limpaView();
            desativaView();
            ativaNovoAlterarExcluir();
            buscaEmpresa();
        } catch (SQLException | NumberFormatException ex) {
            if (ex.toString().contains("UNQ1_EMPRESA")) {
                JOptionPane.showMessageDialog(this, "CNPJ Já se Encontra Cadastrado\n", "Salvar", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Salvar\n" + ex, "Salvar", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void clickEmpresa() {
        for (int i = 0; i < lpb.size(); i++) {
            if (i == jTtempresa.getSelectedRow()) {
                jTrazao.setText(lpb.get(i).getRazao());
                jTfantasia.setText(lpb.get(i).getFantasia());
                jTidempresa.setText(lpb.get(i).getIdempresa().toString());
                jFtelefone1.setText(lpb.get(i).getTelefone1());
                jFtelefone2.setText(lpb.get(i).getTelefone2());
                jFtelefone3.setText(lpb.get(i).getTelefone3());
                jFcnpj.setText(lpb.get(i).getCnpj());
                jTinscrição.setText(lpb.get(i).getIe());
                jTendereco.setText(lpb.get(i).getEndereco());
                jTbairro.setText(lpb.get(i).getBairro());
                jTnumero.setText(lpb.get(i).getNumero());
                jTemail.setText(lpb.get(i).getEmail());
                jTobs.setText(lpb.get(i).getObs());
                jTiddistrito.setText(lpb.get(i).getIddistrito().toString());
                jTcidade.setText(lpb.get(i).getDistrito());
                jTresponsavel.setText(lpb.get(i).getResponsavel());
                for (int j = 0; j < lsb.size(); j++) {
                    if (lsb.get(j).getIdsituacao().equals(lpb.get(i).getIdsituacao())) {
                        jCsituacao.setSelectedIndex(j);
                    }
                }
                return;
            }
        }
    }

    private void alterarEmpresa() {
        try {
            EmpresaBeans pb = new EmpresaBeans();
            pb.setRazao(jTrazao.getText());
            pb.setFantasia(jTfantasia.getText());
            pb.setCnpj(jFcnpj.getText());
            pb.setIe(jTinscrição.getText());
            pb.setEndereco(jTendereco.getText());
            pb.setIddistrito(Integer.valueOf(jTiddistrito.getText()));
            pb.setNumero(jTnumero.getText());
            pb.setEmail(jTemail.getText());
            pb.setTelefone1(jFtelefone1.getText());
            pb.setTelefone2(jFtelefone2.getText());
            pb.setTelefone3(jFtelefone3.getText());
            pb.setIdsituacao(lsb.get(jCsituacao.getSelectedIndex()).getIdsituacao());
            pb.setObs(jTobs.getText());
            pb.setBairro(jTbairro.getText());
            pb.setIdempresa(Integer.valueOf(jTidempresa.getText()));
            pb.setResponsavel(jTresponsavel.getText());
            EmpresaDao pd = new EmpresaDao();
            pd.updateEmpresa(pb);
            JOptionPane.showMessageDialog(this, "Registro Alterado com Sucesso.", "Alterar", JOptionPane.INFORMATION_MESSAGE);
            limpaView();
            desativaView();
            ativaNovoAlterarExcluir();
            buscaEmpresa();
        } catch (SQLException | NumberFormatException ex) {
            if (ex.toString().contains("UNQ1_PESSOA")) {
                JOptionPane.showMessageDialog(this, "CNPJ Já se Encontra Cadastrado\n", "Salvar", JOptionPane.ERROR_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao Alterar" + ex, "Alterar", JOptionPane.ERROR_MESSAGE);
            }
        }

    }

    private boolean validaCampos() {
        if (jTiddistrito.getText().equals("")) {
            return false;
        }
        if (jFcnpj.getText().length() != 14) {
            return false;
        }
        if (jTrazao.getText().equals("")) {
            return false;
        }
        return true;
    }

    private void carregaPesquisa() {

        new Thread(new Runnable() {

            @Override
            public void run() {
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        showAguarde();
                    }
                }).start();
                buscaSituacao();
                buscaEmpresa();
                jDaguarde.setVisible(false);
            }
        }).start();

    }

    private void inicializaAtalhos() {
        //Atalho novo
        KeyStroke keyStrokeJBnovo = KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0);
        String actionNameJBnovo = "F1";
        InputMap inputMapJBnovo = jBnovo.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapJBnovo.put(keyStrokeJBnovo, actionNameJBnovo);
        ActionMap actionMapJBnovo = jBnovo.getActionMap();
        actionMapJBnovo.put(actionNameJBnovo, acaoJBnovo);

        //Atalho alterar
        KeyStroke keyStrokeJBalterar = KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0);
        String actionNameJBalterar = "F3";
        InputMap inputMapJBalterar = jBalterar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapJBalterar.put(keyStrokeJBalterar, actionNameJBalterar);
        ActionMap actionMapJBalterar = jBalterar.getActionMap();
        actionMapJBalterar.put(actionNameJBalterar, acaoJBalterar);

        //Atalho salvar
        KeyStroke keyStrokeJBsalvar = KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0);
        String actionNameJBsalvar = "F2";
        InputMap inputMapJBsalvar = jBsalvar.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapJBsalvar.put(keyStrokeJBsalvar, actionNameJBsalvar);
        ActionMap actionMapJBsalvar = jBsalvar.getActionMap();
        actionMapJBsalvar.put(actionNameJBsalvar, acaoJBsalvar);

        //Atalho excluir
        KeyStroke keyStrokeJBexcluir = KeyStroke.getKeyStroke(KeyEvent.VK_F4, 0);
        String actionNameJBexcluir = "F4";
        InputMap inputMapJBexcluir = jBexcluir.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapJBexcluir.put(keyStrokeJBexcluir, actionNameJBexcluir);
        ActionMap actionMapJBexcluir = jBexcluir.getActionMap();
        actionMapJBexcluir.put(actionNameJBexcluir, acaoJBexcluir);

    }

    //FUNCAO de atalho novo
    Action acaoJBnovo = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            jBnovo.doClick();

        }
    };

    //FUNCAO de atalho alterar
    Action acaoJBalterar = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            jBalterar.doClick();
        }
    };

    //FUNCAO de atalho salvar
    Action acaoJBsalvar = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            jBsalvar.doClick();
        }
    };

    //FUNCAO de atalho excluir
    Action acaoJBexcluir = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  

            jBexcluir.doClick();
        }
    };

    public void showAguarde() {
        jDaguarde.setLocationRelativeTo(this.jPanel2);
        jDaguarde.setVisible(true);
    }

}
