/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atmatech.sac.view;

import br.com.atmatech.sac.beans.PessoaBeans;
import br.com.atmatech.sac.beans.UsuarioBeans;
import br.com.atmatech.sac.beans.UsuarioLogadoBeans;
import br.com.atmatech.sac.controller.Avisos;
import br.com.atmatech.sac.controller.ButtonTabComponent;
import br.com.atmatech.sac.controller.NivelAcesso;
import br.com.atmatech.sac.dao.PessoaDao;
import br.com.atmatech.sac.dao.UsuarioDao;
import br.com.atmatech.sac.report.Report;
import java.awt.Component;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MARCOS
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    Integer countAtedTecnico = 0;
    JMenuItem menuitem;
    Boolean consultasintetico = false;
    Boolean consultadescritivo = false;

    public ViewPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //this.setUndecorated(true);
        inicializaView();
        carregaMenu();
        avisos();
        inicializaAtalhos();
        inicializaReport();

//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopcoes = new javax.swing.JPopupMenu();
        jMtela01 = new javax.swing.JMenuItem();
        jMtela02 = new javax.swing.JMenuItem();
        jDClienteChamadoSintetico = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTcliente = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jTidcliente = new javax.swing.JTextField();
        jSdias = new javax.swing.JSpinner();
        jDconsulta = new javax.swing.JDialog();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTconsulta = new javax.swing.JTable();
        jDaguarde = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jDClienteChamadoDescritivo = new javax.swing.JDialog();
        jLabel6 = new javax.swing.JLabel();
        jTclientedescritivo = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jTidclientedescritivo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTtecnico = new javax.swing.JTextField();
        jTidtecnico = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jCtipo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jCstatus = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jDaberturaini = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        jDiniciadoini = new com.toedter.calendar.JDateChooser();
        jLabel11 = new javax.swing.JLabel();
        jDfechadoini = new com.toedter.calendar.JDateChooser();
        jDaberturafin = new com.toedter.calendar.JDateChooser();
        jDiniciadofin = new com.toedter.calendar.JDateChooser();
        jDfechadofin = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLusuario = new javax.swing.JLabel();
        jLdata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBopcoes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTmenu = new javax.swing.JTree();
        jTaabas = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLpendente = new javax.swing.JLabel();
        jLaberto = new javax.swing.JLabel();
        jLiniciado = new javax.swing.JLabel();
        jPavisoAtendimento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPopcoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPopcoesKeyPressed(evt);
            }
        });
        jPopcoes.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jPopcoesMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });

        jMtela01.setText("Tela 01");
        jMtela01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMtela01ActionPerformed(evt);
            }
        });
        jPopcoes.add(jMtela01);

        jMtela02.setText("Tela 02");
        jMtela02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMtela02ActionPerformed(evt);
            }
        });
        jPopcoes.add(jMtela02);

        jDClienteChamadoSintetico.setTitle("Cliente Chamado Sintetico");
        jDClienteChamadoSintetico.setMinimumSize(new java.awt.Dimension(322, 210));
        jDClienteChamadoSintetico.setModal(true);
        jDClienteChamadoSintetico.setPreferredSize(new java.awt.Dimension(322, 210));
        jDClienteChamadoSintetico.setResizable(false);
        jDClienteChamadoSintetico.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDClienteChamadoSinteticoWindowOpened(evt);
            }
        });

        jLabel3.setText("Dias");

        jLabel5.setText("Cliente");

        jTcliente.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));
        jTcliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTclienteFocusLost(evt);
            }
        });
        jTcliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTclienteKeyPressed(evt);
            }
        });

        jButton3.setText("OK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jSdias.setModel(new javax.swing.SpinnerNumberModel(0, null, 0, 1));

        javax.swing.GroupLayout jDClienteChamadoSinteticoLayout = new javax.swing.GroupLayout(jDClienteChamadoSintetico.getContentPane());
        jDClienteChamadoSintetico.getContentPane().setLayout(jDClienteChamadoSinteticoLayout);
        jDClienteChamadoSinteticoLayout.setHorizontalGroup(
            jDClienteChamadoSinteticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDClienteChamadoSinteticoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDClienteChamadoSinteticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDClienteChamadoSinteticoLayout.createSequentialGroup()
                        .addComponent(jTcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addComponent(jTidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDClienteChamadoSinteticoLayout.createSequentialGroup()
                        .addGroup(jDClienteChamadoSinteticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jDClienteChamadoSinteticoLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jDClienteChamadoSinteticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jSdias, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jDClienteChamadoSinteticoLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDClienteChamadoSinteticoLayout.setVerticalGroup(
            jDClienteChamadoSinteticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDClienteChamadoSinteticoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jDClienteChamadoSinteticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTidcliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDClienteChamadoSinteticoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDClienteChamadoSinteticoLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jSdias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jButton3)
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jDconsulta.setTitle("Consulta");
        jDconsulta.setMinimumSize(new java.awt.Dimension(580, 224));
        jDconsulta.setModal(true);
        jDconsulta.setResizable(false);

        jTconsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Coluna1"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTconsulta.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_NEXT_COLUMN);
        jTconsulta.getTableHeader().setReorderingAllowed(false);
        jTconsulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTconsultaKeyPressed(evt);
            }
        });
        jScrollPane3.setViewportView(jTconsulta);

        javax.swing.GroupLayout jDconsultaLayout = new javax.swing.GroupLayout(jDconsulta.getContentPane());
        jDconsulta.getContentPane().setLayout(jDconsultaLayout);
        jDconsultaLayout.setHorizontalGroup(
            jDconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 580, Short.MAX_VALUE)
        );
        jDconsultaLayout.setVerticalGroup(
            jDconsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
        );

        jDaguarde.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        jDaguarde.setMinimumSize(new java.awt.Dimension(247, 90));
        jDaguarde.setModal(true);
        jDaguarde.setUndecorated(true);
        jDaguarde.setResizable(false);

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel21.setForeground(new java.awt.Color(255, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("AGUARDE....");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel21)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDaguardeLayout = new javax.swing.GroupLayout(jDaguarde.getContentPane());
        jDaguarde.getContentPane().setLayout(jDaguardeLayout);
        jDaguardeLayout.setHorizontalGroup(
            jDaguardeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jDaguardeLayout.setVerticalGroup(
            jDaguardeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jDClienteChamadoDescritivo.setTitle("Cliente Chamado Descritivo");
        jDClienteChamadoDescritivo.setMinimumSize(new java.awt.Dimension(322, 390));
        jDClienteChamadoDescritivo.setModal(true);
        jDClienteChamadoDescritivo.setPreferredSize(new java.awt.Dimension(322, 390));
        jDClienteChamadoDescritivo.setResizable(false);
        jDClienteChamadoDescritivo.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                jDClienteChamadoDescritivoWindowOpened(evt);
            }
        });

        jLabel6.setText("Cliente");

        jTclientedescritivo.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));
        jTclientedescritivo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTclientedescritivoFocusLost(evt);
            }
        });
        jTclientedescritivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTclientedescritivoKeyPressed(evt);
            }
        });

        jButton4.setText("OK");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel7.setText("Tecnico");

        jTtecnico.setDocument(new br.com.atmatech.sac.controller.LimitaCaracterUpper(80,true));
        jTtecnico.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTtecnicoFocusLost(evt);
            }
        });
        jTtecnico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTtecnicoKeyPressed(evt);
            }
        });

        jLabel4.setText("Tipo");

        jCtipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "INTERNO", "EXTERNO", "PLANTAO" }));

        jLabel8.setText("Status");

        jCstatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "ABERTO", "INICIADO", "PENDENTE", "FECHADO" }));

        jLabel9.setText("Abertura");

        jLabel10.setText("Iniciado");

        jLabel11.setText("Fechado");

        javax.swing.GroupLayout jDClienteChamadoDescritivoLayout = new javax.swing.GroupLayout(jDClienteChamadoDescritivo.getContentPane());
        jDClienteChamadoDescritivo.getContentPane().setLayout(jDClienteChamadoDescritivoLayout);
        jDClienteChamadoDescritivoLayout.setHorizontalGroup(
            jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDClienteChamadoDescritivoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jDClienteChamadoDescritivoLayout.createSequentialGroup()
                        .addComponent(jTclientedescritivo, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTidclientedescritivo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jDClienteChamadoDescritivoLayout.createSequentialGroup()
                        .addGroup(jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jDClienteChamadoDescritivoLayout.createSequentialGroup()
                                .addGroup(jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jCstatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDfechadoini, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(jDiniciadoini, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jDClienteChamadoDescritivoLayout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel6))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDaberturaini, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCtipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jDfechadofin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDaberturafin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jDiniciadofin, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jTtecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTidtecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jDClienteChamadoDescritivoLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDClienteChamadoDescritivoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jTclientedescritivo, jTtecnico});

        jDClienteChamadoDescritivoLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jDaberturafin, jDaberturaini, jDfechadofin, jDfechadoini, jDiniciadofin, jDiniciadoini});

        jDClienteChamadoDescritivoLayout.setVerticalGroup(
            jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDClienteChamadoDescritivoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTclientedescritivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTidclientedescritivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel7)
                .addGap(0, 0, 0)
                .addGroup(jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTtecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTidtecnico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel4)
                .addGap(0, 0, 0)
                .addComponent(jCtipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel8)
                .addGap(0, 0, 0)
                .addComponent(jCstatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel9)
                .addGap(0, 0, 0)
                .addGroup(jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDaberturaini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDaberturafin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel10)
                .addGap(0, 0, 0)
                .addGroup(jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDiniciadoini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDiniciadofin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jLabel11)
                .addGap(0, 0, 0)
                .addGroup(jDClienteChamadoDescritivoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDfechadofin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDfechadoini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jDClienteChamadoDescritivoLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jTclientedescritivo, jTtecnico});

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAC");
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 59));

        jLusuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLdata.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/logo.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("_");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBopcoes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBopcoes.setText("*");
        jBopcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBopcoesMouseClicked(evt);
            }
        });
        jBopcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBopcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBopcoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jBopcoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLdata, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setMaximumSize(new java.awt.Dimension(23, 23));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("MENU");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cadastro");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nível de Acesso");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuários");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Veiculos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empresas");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Atendimento");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Modulos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Email");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Relatórios");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Gerencial");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Clientes");
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Clientes Chamado Descritivo");
        treeNode3.add(treeNode4);
        treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Clientes Chamado Sintetico");
        treeNode3.add(treeNode4);
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTmenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTmenu.setMinimumSize(new java.awt.Dimension(90, 48));
        jTmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTmenuMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTmenu);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("AVISOS"));
        jPanel4.setMaximumSize(new java.awt.Dimension(207, 253));
        jPanel4.setMinimumSize(new java.awt.Dimension(207, 253));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Atendimento:"));

        jLpendente.setForeground(new java.awt.Color(255, 0, 0));
        jLpendente.setText(" ");
        jLpendente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLpendenteMouseClicked(evt);
            }
        });

        jLaberto.setForeground(new java.awt.Color(0, 204, 0));
        jLaberto.setText(" ");
        jLaberto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabertoMouseClicked(evt);
            }
        });

        jLiniciado.setForeground(new java.awt.Color(255, 255, 255));
        jLiniciado.setText(" ");
        jLiniciado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLiniciadoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLpendente)
                    .addComponent(jLaberto)
                    .addComponent(jLiniciado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLpendente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLaberto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLiniciado)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jPavisoAtendimento.setBackground(new java.awt.Color(255, 0, 0));
        jPavisoAtendimento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPavisoAtendimento.setPreferredSize(new java.awt.Dimension(200, 104));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VOCÊ POSSUI UM NOVO CHAMADO");

        javax.swing.GroupLayout jPavisoAtendimentoLayout = new javax.swing.GroupLayout(jPavisoAtendimento);
        jPavisoAtendimento.setLayout(jPavisoAtendimentoLayout);
        jPavisoAtendimentoLayout.setHorizontalGroup(
            jPavisoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        jPavisoAtendimentoLayout.setVerticalGroup(
            jPavisoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPavisoAtendimentoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPavisoAtendimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPavisoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTaabas)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTaabas))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(800, 667));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTmenuMousePressed
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null, jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()));         
        getTela();
    }//GEN-LAST:event_jTmenuMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBopcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBopcoesActionPerformed
        // TODO add your handling code here:        
        jPopcoes.show(this, jBopcoes.getX(), jBopcoes.getY());
    }//GEN-LAST:event_jBopcoesActionPerformed

    private void jBopcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBopcoesMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jBopcoesMouseClicked

    private void jPopcoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPopcoesKeyPressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jPopcoesKeyPressed

    private void jPopcoesMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jPopcoesMenuKeyPressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jPopcoesMenuKeyPressed

    private void jMtela01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMtela01ActionPerformed
        // TODO add your handling code here:
        exibeTelaSec(0);
    }//GEN-LAST:event_jMtela01ActionPerformed

    private void jMtela02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMtela02ActionPerformed
        // TODO add your handling code here:
        exibeTelaSec(1);
    }//GEN-LAST:event_jMtela02ActionPerformed

    private void jLpendenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLpendenteMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    chamdoPendente();
                }
            }).start();

        }
    }//GEN-LAST:event_jLpendenteMouseClicked

    private void jLabertoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabertoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    chamadoAberto();
                }
            }).start();

        }
    }//GEN-LAST:event_jLabertoMouseClicked

    private void jLiniciadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLiniciadoMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    chamadoIniciado();
                }
            }).start();

        }
    }//GEN-LAST:event_jLiniciadoMouseClicked

    private void jTclienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTclienteFocusLost
        // TODO add your handling code here:     
        if (jDClienteChamadoSintetico.isVisible()) {
            if (!jDconsulta.isVisible()) {
                if (consultasintetico) {
                    getCliente(jTcliente.getText());
                }
            }

        }
        consultasintetico = true;
    }//GEN-LAST:event_jTclienteFocusLost

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:        
        if (!jDconsulta.isVisible()) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    showAguarde();
                }
            }).start();
            new Thread(new Runnable() {
                @Override
                public void run() {
                    getReportClienteChamadoSintetico();
                }
            }).start();
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTconsultaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTconsultaKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jDClienteChamadoSintetico.isVisible()) {
                jTidcliente.setText(jTconsulta.getValueAt(jTconsulta.getSelectedRow(), 0).toString());
                jTcliente.setText(jTconsulta.getValueAt(jTconsulta.getSelectedRow(), 1).toString());
                jDconsulta.setVisible(false);
            } else if (jDClienteChamadoDescritivo.isVisible()) {
                if (jTconsulta.getColumnName(0).equals("idpessoa")) {
                    jTidclientedescritivo.setText(jTconsulta.getValueAt(jTconsulta.getSelectedRow(), 0).toString());
                    jTclientedescritivo.setText(jTconsulta.getValueAt(jTconsulta.getSelectedRow(), 1).toString());
                    jDconsulta.setVisible(false);
                } else if (jTconsulta.getColumnName(0).equals("idusuario")) {
                    jTidtecnico.setText(jTconsulta.getValueAt(jTconsulta.getSelectedRow(), 0).toString());
                    jTtecnico.setText(jTconsulta.getValueAt(jTconsulta.getSelectedRow(), 1).toString());
                    jDconsulta.setVisible(false);
                }

            }

        }

    }//GEN-LAST:event_jTconsultaKeyPressed

    private void jDClienteChamadoSinteticoWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDClienteChamadoSinteticoWindowOpened
        // TODO add your handling code here:  
        jSdias.requestFocusInWindow();
    }//GEN-LAST:event_jDClienteChamadoSinteticoWindowOpened

    private void jTclientedescritivoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTclientedescritivoFocusLost
        // TODO add your handling code here:
        if (jDClienteChamadoDescritivo.isVisible()) {
            if (!jDconsulta.isVisible()) {
                if (consultadescritivo) {
                    getCliente(jTclientedescritivo.getText());
                }
            }
        }
        consultadescritivo = true;
    }//GEN-LAST:event_jTclientedescritivoFocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        if (!jDconsulta.isVisible()) {            
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        showAguarde();
                    }
                }).start();
                new Thread(new Runnable() {
                    @Override
                    public void run() {
                        getReportClienteChamadoDescritivo();
                    }
                }).start();            
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jDClienteChamadoDescritivoWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jDClienteChamadoDescritivoWindowOpened
        // TODO add your handling code here:
        jButton4.requestFocusInWindow();
    }//GEN-LAST:event_jDClienteChamadoDescritivoWindowOpened

    private void jTtecnicoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTtecnicoFocusLost
        // TODO add your handling code here:
        if (jDClienteChamadoDescritivo.isVisible()) {
            if (!jDconsulta.isVisible()) {
                if (consultadescritivo) {
                    getTecnico();
                }
            }
        }
    }//GEN-LAST:event_jTtecnicoFocusLost

    private void jTclientedescritivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTclientedescritivoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jDClienteChamadoDescritivo.isVisible()) {
                if (!jDconsulta.isVisible()) {
                    if (consultadescritivo) {
                        jButton4.requestFocusInWindow();
                        getCliente(jTclientedescritivo.getText());
                    }
                }
            }
            consultadescritivo = true;
        }
    }//GEN-LAST:event_jTclientedescritivoKeyPressed

    private void jTtecnicoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTtecnicoKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jDClienteChamadoDescritivo.isVisible()) {
                if (!jDconsulta.isVisible()) {
                    if (consultadescritivo) {
                        jButton4.requestFocusInWindow();
                        getTecnico();
                    }
                }
            }
        }
    }//GEN-LAST:event_jTtecnicoKeyPressed

    private void jTclienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTclienteKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (jDClienteChamadoSintetico.isVisible()) {
                if (!jDconsulta.isVisible()) {
                    if (consultasintetico) {
                        jButton3.requestFocusInWindow();
                        getCliente(jTcliente.getText());
                    }
                }

            }
            consultasintetico = true;
        }
    }//GEN-LAST:event_jTclienteKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBopcoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox<String> jCstatus;
    private javax.swing.JComboBox<String> jCtipo;
    private javax.swing.JDialog jDClienteChamadoDescritivo;
    private javax.swing.JDialog jDClienteChamadoSintetico;
    private com.toedter.calendar.JDateChooser jDaberturafin;
    private com.toedter.calendar.JDateChooser jDaberturaini;
    private javax.swing.JDialog jDaguarde;
    private javax.swing.JDialog jDconsulta;
    private com.toedter.calendar.JDateChooser jDfechadofin;
    private com.toedter.calendar.JDateChooser jDfechadoini;
    private com.toedter.calendar.JDateChooser jDiniciadofin;
    private com.toedter.calendar.JDateChooser jDiniciadoini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLaberto;
    public javax.swing.JLabel jLdata;
    private javax.swing.JLabel jLiniciado;
    private javax.swing.JLabel jLpendente;
    public javax.swing.JLabel jLusuario;
    private javax.swing.JMenuItem jMtela01;
    private javax.swing.JMenuItem jMtela02;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPavisoAtendimento;
    private javax.swing.JPopupMenu jPopcoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSpinner jSdias;
    public javax.swing.JTabbedPane jTaabas;
    private javax.swing.JTextField jTcliente;
    private javax.swing.JTextField jTclientedescritivo;
    private javax.swing.JTable jTconsulta;
    private javax.swing.JTextField jTidcliente;
    private javax.swing.JTextField jTidclientedescritivo;
    private javax.swing.JTextField jTidtecnico;
    private javax.swing.JTree jTmenu;
    private javax.swing.JTextField jTtecnico;
    // End of variables declaration//GEN-END:variables

    private void inicializaView() {
        jLusuario.setText("Ola " + new UsuarioLogadoBeans().getNome());
        jPavisoAtendimento.setVisible(false);
        jMtela01.setVisible(false);
        jMtela02.setVisible(false);
        jTidcliente.setVisible(false);
        jTidclientedescritivo.setVisible(false);
        jTidtecnico.setVisible(false);

        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    try {
                        GregorianCalendar x;
                        x = new GregorianCalendar();
                        jLdata.setText(String.valueOf(x.getTime()));
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao Sincronizar Data", "Data", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                    }
                }

            }
        }).start();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] devices = ge.getScreenDevices();
        if (devices.length == 1) {
            jMtela01.setVisible(true);
        } else if (devices.length == 2) {
            jMtela01.setVisible(true);
            jMtela02.setVisible(true);
        }

    }

    private void carregaMenu() {
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("MENU");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cadastro");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = null;
        javax.swing.tree.DefaultMutableTreeNode treeNode4 = null;

        if (new NivelAcesso().getAcesso("ViewNivel", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nível de Acesso");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewUsuario", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuários");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewVeiculo", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Veiculos");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewPessoa", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empresas");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewListaAtendimento", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Atendimento");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewModulo", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Modulos");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewEmail", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Email");
            treeNode2.add(treeNode3);
        }
        treeNode1.add(treeNode2);

        if (new NivelAcesso().getAcesso("ViewRelatorio", "acessar", false)) {
            treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Relatórios");
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Gerencial");
            treeNode2.add(treeNode3);
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Clientes");
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Clientes Chamado Descritivo");
            treeNode3.add(treeNode4);
            treeNode4 = new javax.swing.tree.DefaultMutableTreeNode("Clientes Chamado Sintetico");
            treeNode3.add(treeNode4);
        }
        if (treeNode3 != null) {
            treeNode2.add(treeNode3);
        }
        // if (treeNode2 != null) {
        treeNode1.add(treeNode2);
        // }

        jTmenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));

    }

    private Boolean getJanelaAberta(String titulo) {
        Boolean verifica = false;
        for (int i = 0; i < jTaabas.getTabCount(); i++) {
            if (titulo.equals(jTaabas.getTitleAt(i))) {
                verifica = true;
            }
        }
        return verifica;
    }

    private Component getJanelaAbertaClass(String titulo) {
        for (int i = 0; i < jTaabas.getTabCount(); i++) {
            if (titulo.equals(jTaabas.getTitleAt(i))) {
                return jTaabas.getComponentAt(i);
            }
        }
        return null;
    }

    private void avisos() {
        new Thread(new Runnable() {

            @Override
            public void run() {

                while (true) {
                    try {
                        getAtendimentoAberto();
                        getAtendimentoTecnico();
                        Thread.sleep(1000);

                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao Carregar Avisos\n" + ex);
                    }
                }

            }
        }).start();

    }

    private void getAtendimentoAberto() {
        jLpendente.setText("Pendentes: " + String.valueOf(new Avisos().getStatusAtendimento("'PENDENTE'", new UsuarioLogadoBeans().getIdusuario(), new UsuarioLogadoBeans().getVchamados())));
        jLaberto.setText("Abertos: " + String.valueOf(new Avisos().getStatusAtendimento("'ABERTO'", new UsuarioLogadoBeans().getIdusuario(), new UsuarioLogadoBeans().getVchamados())));
        jLiniciado.setText("Iniciado: " + String.valueOf(new Avisos().getStatusAtendimento("'INICIADO'", new UsuarioLogadoBeans().getIdusuario(), new UsuarioLogadoBeans().getVchamados())));
    }

    private void getAtendimentoTecnico() throws InterruptedException {
        Integer countAtend = 0;
        countAtend = new Avisos().getStatusAtendimento("'ABERTO'", new UsuarioLogadoBeans().getIdusuario(), false);
        if ((countAtedTecnico == 0) && (countAtend != 0)) {
            countAtedTecnico = countAtend;
            jPavisoAtendimento.setVisible(true);
            Toolkit.getDefaultToolkit().beep();
            Thread.sleep(7000);
            jPavisoAtendimento.setVisible(false);
        }
        if (countAtedTecnico != countAtend) {
            if (countAtedTecnico < countAtend) {
                countAtedTecnico = countAtend;
                jPavisoAtendimento.setVisible(true);
                Toolkit.getDefaultToolkit().beep();
                Thread.sleep(7000);
                jPavisoAtendimento.setVisible(false);
            } else if (countAtedTecnico > countAtend) {
                countAtedTecnico = countAtend;
            }
        }

    }

    private void getTela() {
        if (null != jTmenu.getPathForRow(jTmenu.getLeadSelectionRow())) {
            if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Empresas")) {
                if (!getJanelaAberta("Cadastro de Empresas")) {
                    ViewPessoa viewcadpessoa = new ViewPessoa();
                    jTaabas.addTab("Cadastro de Empresas", null, viewcadpessoa);
                    jTaabas.setSelectedComponent(viewcadpessoa);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Modulos")) {
                if (!getJanelaAberta("Cadastro de Modulos")) {
                    ViewModulo viewmodulo = new ViewModulo();
                    jTaabas.addTab("Cadastro de Modulos", null, viewmodulo);
                    jTaabas.setSelectedComponent(viewmodulo);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Nível de Acesso")) {
                if (!getJanelaAberta("Nível de Acesso")) {
                    ViewNivel viewnivel = new ViewNivel();
                    jTaabas.addTab("Nível de Acesso", null, viewnivel);
                    jTaabas.setSelectedComponent(viewnivel);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Usuários")) {
                if (!getJanelaAberta("Cadastro de Usuários")) {
                    ViewUsuario viewusuario = new ViewUsuario();
                    jTaabas.addTab("Cadastro de Usuários", null, viewusuario);
                    jTaabas.setSelectedComponent(viewusuario);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Veiculos")) {
                if (!getJanelaAberta("Cadastro de Veiculos")) {
                    ViewVeiculo view = new ViewVeiculo();
                    jTaabas.addTab("Cadastro de Veiculos", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Atendimento")) {
                if (!getJanelaAberta("Atendimento")) {
                    ViewListaAtendimento view = new ViewListaAtendimento(this, true);
                    jTaabas.addTab("Atendimento", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Relatórios, Gerencial")) {
                if (!getJanelaAberta("Relatório Gerencial")) {
                    ViewRelatorio view = new ViewRelatorio();
                    jTaabas.addTab("Relatório Gerencial", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Relatórios, Clientes, Clientes Chamado Descritivo")) {
                jTclientedescritivo.setText("");
                jTidclientedescritivo.setText("");
                jTtecnico.setText("");
                jTidtecnico.setText("");
                jCtipo.setSelectedIndex(0);
                jCstatus.setSelectedIndex(0);
                jDaberturaini.setDate(null);
                jDaberturafin.setDate(null);
                jDiniciadoini.setDate(null);
                jDiniciadofin.setDate(null);
                jDfechadoini.setDate(null);
                jDfechadofin.setDate(null);
                jDClienteChamadoDescritivo.setLocationRelativeTo(jTaabas);
                jDClienteChamadoDescritivo.setVisible(true);
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Relatórios, Clientes, Clientes Chamado Sintetico")) {
                jTcliente.setText("");
                jTidcliente.setText("");
                jSdias.setValue(0);
                jSdias.requestFocusInWindow();
                jDClienteChamadoSintetico.setLocationRelativeTo(jTaabas);
                jDClienteChamadoSintetico.setVisible(true);
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Email")) {
                if (!getJanelaAberta("Gerenciador de Email")) {
                    ViewEmail view = new ViewEmail();
                    jTaabas.addTab("Gerenciador de Email", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            }

        }
    }

    private void inicializaAtalhos() {

        //Atalho Atendimento
        KeyStroke keyStrokeAtendimento = KeyStroke.getKeyStroke(KeyEvent.VK_A, KeyEvent.ALT_DOWN_MASK);
        String actionNameAtendimento = "Alt+A";
        InputMap inputMapAtendimento = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapAtendimento.put(keyStrokeAtendimento, actionNameAtendimento);
        ActionMap actionMapAtendimento = jTmenu.getActionMap();
        actionMapAtendimento.put(actionNameAtendimento, acaoAtendimento);

        //Atalho Nivel de Acesso
        KeyStroke keyStrokeNivelAcesso = KeyStroke.getKeyStroke(KeyEvent.VK_N, KeyEvent.ALT_DOWN_MASK);
        String actionNameNivelAcesso = "Alt+N";
        InputMap inputMapNivelAtendimento = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapNivelAtendimento.put(keyStrokeNivelAcesso, actionNameNivelAcesso);
        ActionMap actionMapNivelAcesso = jTmenu.getActionMap();
        actionMapNivelAcesso.put(actionNameNivelAcesso, acaoNivelAcesso);

        //Atalho Usuario
        KeyStroke keyStrokeUsuario = KeyStroke.getKeyStroke(KeyEvent.VK_U, KeyEvent.ALT_DOWN_MASK);
        String actionNameUsuario = "Alt+U";
        InputMap inputMapUsuario = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapUsuario.put(keyStrokeUsuario, actionNameUsuario);
        ActionMap actionMapUsuario = jTmenu.getActionMap();
        actionMapUsuario.put(actionNameUsuario, acaoUsuario);

        //Atalho veiculos
        KeyStroke keyStrokeVeiculo = KeyStroke.getKeyStroke(KeyEvent.VK_V, KeyEvent.ALT_DOWN_MASK);
        String actionNameVeiculo = "Alt+V";
        InputMap inputMapVeiculo = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapVeiculo.put(keyStrokeVeiculo, actionNameVeiculo);
        ActionMap actionMapVeiculo = jTmenu.getActionMap();
        actionMapUsuario.put(actionNameVeiculo, acaoVeiculo);

        //Atalho empresas
        KeyStroke keyStrokeEmpresa = KeyStroke.getKeyStroke(KeyEvent.VK_E, KeyEvent.ALT_DOWN_MASK);
        String actionNameEmpresa = "Alt+E";
        InputMap inputMapEmpresa = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapEmpresa.put(keyStrokeEmpresa, actionNameEmpresa);
        ActionMap actionMapEmpresa = jTmenu.getActionMap();
        actionMapEmpresa.put(actionNameEmpresa, acaoEmpresa);

        //Atalho modulo
        KeyStroke keyStrokeModulo = KeyStroke.getKeyStroke(KeyEvent.VK_M, KeyEvent.ALT_DOWN_MASK);
        String actionNameModulo = "Alt+M";
        InputMap inputMapModulo = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapModulo.put(keyStrokeModulo, actionNameModulo);
        ActionMap actionMapModulo = jTmenu.getActionMap();
        actionMapModulo.put(actionNameModulo, acaoModulo);

    }

    //FUNCAO de atalho Atendimento
    Action acaoAtendimento = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoAtendimento();
        }
    };

    //FUNCAO de atalho Nivel Acesso
    Action acaoNivelAcesso = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoNivelAcesso();
        }
    };

    //FUNCAO de atalho Usuario
    Action acaoUsuario = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoUsuario();
        }
    };

    //FUNCAO de atalho Veiculo
    Action acaoVeiculo = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoVeiculos();
        }
    };

    //FUNCAO de atalho Empresa
    Action acaoEmpresa = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoEmpresa();
        }
    };

    //FUNCAO de atalho modulo
    Action acaoModulo = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoModulos();
        }
    };

    public void getAtalhoAtendimento() {
        if (new NivelAcesso().getAcesso("ViewListaAtendimento", "acessar", false)) {
            if (!getJanelaAberta("Atendimento")) {
                ViewListaAtendimento view = new ViewListaAtendimento(this, true);
                jTaabas.addTab("Atendimento", null, view);
                jTaabas.setSelectedComponent(view);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoNivelAcesso() {
        if (new NivelAcesso().getAcesso("ViewNivel", "acessar", false)) {
            if (!getJanelaAberta("Nível de Acesso")) {
                ViewNivel viewnivel = new ViewNivel();
                jTaabas.addTab("Nível de Acesso", null, viewnivel);
                jTaabas.setSelectedComponent(viewnivel);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoUsuario() {
        if (new NivelAcesso().getAcesso("ViewUsuario", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Usuários")) {
                ViewUsuario viewusuario = new ViewUsuario();
                jTaabas.addTab("Cadastro de Usuários", null, viewusuario);
                jTaabas.setSelectedComponent(viewusuario);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoVeiculos() {
        if (new NivelAcesso().getAcesso("ViewVeiculo", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Veiculos")) {
                ViewVeiculo view = new ViewVeiculo();
                jTaabas.addTab("Cadastro de Veiculos", null, view);
                jTaabas.setSelectedComponent(view);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoEmpresa() {
        if (new NivelAcesso().getAcesso("ViewPessoa", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Empresas")) {
                ViewPessoa viewcadpessoa = new ViewPessoa();
                jTaabas.addTab("Cadastro de Empresas", null, viewcadpessoa);
                jTaabas.setSelectedComponent(viewcadpessoa);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoModulos() {
        if (new NivelAcesso().getAcesso("ViewModulo", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Modulos")) {
                ViewModulo viewmodulo = new ViewModulo();
                jTaabas.addTab("Cadastro de Modulos", null, viewmodulo);
                jTaabas.setSelectedComponent(viewmodulo);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    private void exibeTelaSec(int tela) {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] devices = ge.getScreenDevices();

        devices[tela].setFullScreenWindow(this);
        int xx = (int) this.getLocation().getX();
        int yy = (int) this.getLocation().getY();
        devices[tela].setFullScreenWindow(null);
        this.setLocation(xx, yy);

    }

    private void chamdoPendente() {
        if (new NivelAcesso().getAcesso("ViewListaAtendimento", "acessar", false)) {
            if (!getJanelaAberta("Atendimento")) {
                ViewListaAtendimento view = new ViewListaAtendimento(this, false);
                jTaabas.addTab("Atendimento", null, view);
                jTaabas.setSelectedComponent(view);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                Calendar c = Calendar.getInstance();
                c.add(Calendar.DAY_OF_YEAR, -360);
                view.buscaAtendimento("'PENDENTE'", new UsuarioLogadoBeans().getIdusuario(), c.getTime(), new Timestamp(new Date().getTime()), "dtabertura");
            } else {
                Calendar c = Calendar.getInstance();
                c.add(Calendar.DAY_OF_YEAR, -360);
                if (getJanelaAbertaClass("Atendimento") instanceof ViewListaAtendimento) {
                    ViewListaAtendimento view = (ViewListaAtendimento) getJanelaAbertaClass("Atendimento");
                    view.buscaAtendimento("'PENDENTE'", new UsuarioLogadoBeans().getIdusuario(), c.getTime(), new Timestamp(new Date().getTime()), "dtabertura");
                }
            }
        }
    }

    private void chamadoAberto() {
        if (new NivelAcesso().getAcesso("ViewListaAtendimento", "acessar", false)) {
            if (!getJanelaAberta("Atendimento")) {
                ViewListaAtendimento view = new ViewListaAtendimento(this, false);
                jTaabas.addTab("Atendimento", null, view);
                jTaabas.setSelectedComponent(view);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                Calendar c = Calendar.getInstance();
                c.add(Calendar.DAY_OF_YEAR, -360);
                view.buscaAtendimento("'ABERTO'", new UsuarioLogadoBeans().getIdusuario(), c.getTime(), new Timestamp(new Date().getTime()), "dtabertura");
            } else {
                Calendar c = Calendar.getInstance();
                c.add(Calendar.DAY_OF_YEAR, -360);
                if (getJanelaAbertaClass("Atendimento") instanceof ViewListaAtendimento) {
                    ViewListaAtendimento view = (ViewListaAtendimento) getJanelaAbertaClass("Atendimento");
                    view.buscaAtendimento("'ABERTO'", new UsuarioLogadoBeans().getIdusuario(), c.getTime(), new Timestamp(new Date().getTime()), "dtabertura");
                }
            }
        }
    }

    private void chamadoIniciado() {
        if (new NivelAcesso().getAcesso("ViewListaAtendimento", "acessar", false)) {
            if (!getJanelaAberta("Atendimento")) {
                ViewListaAtendimento view = new ViewListaAtendimento(this, false);
                jTaabas.addTab("Atendimento", null, view);
                jTaabas.setSelectedComponent(view);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                Calendar c = Calendar.getInstance();
                c.add(Calendar.DAY_OF_YEAR, -360);
                view.buscaAtendimento("'INICIADO'", new UsuarioLogadoBeans().getIdusuario(), c.getTime(), new Timestamp(new Date().getTime()), "dtabertura");
            } else {
                Calendar c = Calendar.getInstance();
                c.add(Calendar.DAY_OF_YEAR, -360);
                if (getJanelaAbertaClass("Atendimento") instanceof ViewListaAtendimento) {
                    ViewListaAtendimento view = (ViewListaAtendimento) getJanelaAbertaClass("Atendimento");
                    view.buscaAtendimento("'INICIADO'", new UsuarioLogadoBeans().getIdusuario(), c.getTime(), new Timestamp(new Date().getTime()), "dtabertura");
                }
            }
        }
    }

    private void getCliente(String parametro) {
        jTconsulta.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "idpessoa", "RAZAO", "FANTASIA", "CNPJ"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTconsulta.getColumnModel().getColumn(0).setMinWidth(0);
        jTconsulta.getColumnModel().getColumn(0).setMaxWidth(0);
        List<PessoaBeans> pb = new ArrayList<>();
        pb = new PessoaDao().getPessoaAtivo(parametro, "RAZAO");
        DefaultTableModel tbconsulta = new DefaultTableModel();
        tbconsulta = (DefaultTableModel) jTconsulta.getModel();

        if (pb.size() > 0) {
            for (PessoaBeans pb1 : pb) {
                tbconsulta.addRow(new Object[]{pb1.getIdpessoa(), pb1.getRazao(), pb1.getFantasia(), pb1.getCnpj()});
            }
            jDconsulta.setLocationRelativeTo(jTaabas);
            jDconsulta.setVisible(true);
        }
    }

    private void getReportClienteChamadoSintetico() {
        String sql = "";
        jDClienteChamadoSintetico.setVisible(false);
        if ((!jTidcliente.getText().equals(""))) {
            if ((Integer) jSdias.getValue() == 0) {
                sql = " where dias>=" + jSdias.getValue().toString() + " and idpessoa=" + jTidcliente.getText() + "";
                new Report().getReport("ReportClienteChamadosSintetico", sql,this);
            } else {
                sql = " where dias>=" + jSdias.getValue().toString() + " and dias<0 and idpessoa=" + jTidcliente.getText() + "";
               new Report(). getReport("ReportClienteChamadosSintetico", sql,this);
            }
        } else if ((Integer) jSdias.getValue() == 0) {
            sql = " where dias>=" + jSdias.getValue().toString() + "";
            new Report().getReport("ReportClienteChamadosSintetico", sql,this);
        } else {
            sql = " where dias>=" + jSdias.getValue().toString() + " and dias<0";
            new Report().getReport("ReportClienteChamadosSintetico", sql,this);
        }

    }

   

    public void showAguarde() {
        jDaguarde.setLocationRelativeTo(this.jTaabas);
        jDaguarde.setVisible(true);
    }
    public void closeAguarde() {        
        jDaguarde.setVisible(false);
    }

    private void getTecnico() {
        jTconsulta.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{},
                new String[]{
                    "idusuario", "NOME"
                }
        ) {
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        });
        jTconsulta.getColumnModel().getColumn(0).setMinWidth(0);
        jTconsulta.getColumnModel().getColumn(0).setMaxWidth(0);
        List<UsuarioBeans> ub = new ArrayList<>();
        ub = new UsuarioDao().getUsuario("nome", jTtecnico.getText(), "nome");
        DefaultTableModel tbconsulta = new DefaultTableModel();
        tbconsulta = (DefaultTableModel) jTconsulta.getModel();

        if (ub.size() > 0) {
            for (UsuarioBeans pb1 : ub) {
                tbconsulta.addRow(new Object[]{pb1.getIdusuario(), pb1.getNome()});
            }
            jDconsulta.setLocationRelativeTo(jTaabas);
            jDconsulta.setVisible(true);
        }
    }

    private void getReportClienteChamadoDescritivo() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
        String sql = "";
        jDClienteChamadoDescritivo.setVisible(false);
        if (!jTidclientedescritivo.getText().equals("")) {
            if (sql.equals("")) {
                sql = "where idpessoa=" + jTidclientedescritivo.getText() + "";
            } else {
                sql = sql + " and idpessoa=" + jTidclientedescritivo.getText() + "";
            }
        }
        if (!jTidtecnico.getText().equals("")) {
            if (sql.equals("")) {
                sql = "where idtecnico=" + jTidtecnico.getText() + "";
            } else {
                sql = sql + " and idtecnico=" + jTidtecnico.getText() + "";
            }
        }
        if(jCtipo.getSelectedIndex()>0){
             if (sql.equals("")) {
                sql = "where tipo='" + jCtipo.getSelectedItem().toString() + "'";
            } else {
                sql = sql + " and tipo='" + jCtipo.getSelectedItem().toString() + "'";
            }
        }
        if(jCstatus.getSelectedIndex()>0){
             if (sql.equals("")) {
                sql = "where status='" + jCstatus.getSelectedItem().toString() + "'";
            } else {
                sql = sql + " and status='" + jCstatus.getSelectedItem().toString() + "'";
            }
        }
        if((jDaberturaini.getDate()!=null)&&(jDaberturafin.getDate()!=null)){
           if (sql.equals("")) {
                sql = "where cast(dtabertura as date) between '" + sdf.format(jDaberturaini.getDate())+ "' and '"+sdf.format(jDaberturafin.getDate())+"'";
            } else {
                sql = sql + " and cast(dtabertura as date) between '" + sdf.format(jDaberturaini.getDate())+ "' and '"+sdf.format(jDaberturafin.getDate())+"'";
            } 
        } 
        if((jDiniciadoini.getDate()!=null)&&(jDiniciadofin.getDate()!=null)){
           if (sql.equals("")) {
                sql = "where cast(dtinicial as date) between '" + sdf.format(jDiniciadoini.getDate())+ "' and '"+sdf.format(jDiniciadofin.getDate())+"'";
            } else {
                sql = sql + " and cast(dtinicial as date) between '" + sdf.format(jDiniciadoini.getDate())+ "' and '"+sdf.format(jDiniciadofin.getDate())+"'";
            } 
        } 
        if((jDfechadoini.getDate()!=null)&&(jDfechadofin.getDate()!=null)){
           if (sql.equals("")) {
                sql = "where cast(dtfinal as date) between '" + sdf.format(jDfechadoini.getDate())+ "' and '"+sdf.format(jDfechadofin.getDate())+"'";
            } else {
                sql = sql + " and cast(dtfinal as date) between '" + sdf.format(jDfechadoini.getDate())+ "' and '"+sdf.format(jDfechadofin.getDate())+"'";
            } 
        } 
        new Report().getReport("ReportClienteChamadoDescritivo", sql,this);
        //getReport("ReportClienteChamadoDescritivo", sql);
    }

    private void inicializaReport() {
        new Thread(new Runnable() {
            @Override
            public void run() {
                new Report().inicializaReport("ReportClienteChamadoDescritivo", "where idpessoa=0");
                new Report(). inicializaReport("ReportClienteChamadosSintetico","where idpessoa=0");
                new Report().inicializaReportChamado();
            }
        }).start();
    }
}
