/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atmatech.sac.view;

import br.com.atmatech.sac.beans.UsuarioLogadoBeans;
import br.com.atmatech.sac.controller.Avisos;
import br.com.atmatech.sac.controller.ButtonTabComponent;
import br.com.atmatech.sac.controller.NivelAcesso;
import java.awt.Dimension;
import java.awt.Frame;
import java.awt.GraphicsDevice;
import java.awt.GraphicsEnvironment;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.util.GregorianCalendar;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author MARCOS
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    Integer countAtedTecnico = 0;
    JMenuItem menuitem;

    public ViewPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //this.setUndecorated(true);
        inicializaView();
        carregaMenu();
        avisos();
        inicializaAtalhos();
        
//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopcoes = new javax.swing.JPopupMenu();
        jMtela01 = new javax.swing.JMenuItem();
        jMtela02 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLusuario = new javax.swing.JLabel();
        jLdata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jBopcoes = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTmenu = new javax.swing.JTree();
        jTaabas = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLpendente = new javax.swing.JLabel();
        jLaberto = new javax.swing.JLabel();
        jLiniciado = new javax.swing.JLabel();
        jPavisoAtendimento = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        jPopcoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPopcoesKeyPressed(evt);
            }
        });
        jPopcoes.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jPopcoesMenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });

        jMtela01.setText("Tela 01");
        jMtela01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMtela01ActionPerformed(evt);
            }
        });
        jPopcoes.add(jMtela01);

        jMtela02.setText("Tela 02");
        jMtela02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMtela02ActionPerformed(evt);
            }
        });
        jPopcoes.add(jMtela02);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAC");
        setUndecorated(true);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 59));

        jLusuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLdata.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/logo.png"))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("x");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton2.setText("_");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jBopcoes.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jBopcoes.setText("*");
        jBopcoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jBopcoesMouseClicked(evt);
            }
        });
        jBopcoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBopcoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(104, 104, 104)
                            .addComponent(jLdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jBopcoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jBopcoes))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLdata, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setMaximumSize(new java.awt.Dimension(23, 23));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("MENU");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cadastro");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nível de Acesso");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuários");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Veiculos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empresas");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Atendimento");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Modulos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Email");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Relatórios");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Gerencial");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTmenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTmenu.setMinimumSize(new java.awt.Dimension(90, 48));
        jTmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTmenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTmenuMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTmenu);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("AVISOS"));
        jPanel4.setMaximumSize(new java.awt.Dimension(207, 253));
        jPanel4.setMinimumSize(new java.awt.Dimension(207, 253));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Atendimento:"));

        jLpendente.setForeground(new java.awt.Color(255, 0, 0));
        jLpendente.setText(" ");

        jLaberto.setForeground(new java.awt.Color(0, 204, 0));
        jLaberto.setText(" ");

        jLiniciado.setForeground(new java.awt.Color(255, 255, 255));
        jLiniciado.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLpendente)
                    .addComponent(jLaberto)
                    .addComponent(jLiniciado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLpendente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLaberto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLiniciado)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        jPavisoAtendimento.setBackground(new java.awt.Color(255, 0, 0));
        jPavisoAtendimento.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPavisoAtendimento.setPreferredSize(new java.awt.Dimension(200, 104));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("VOCÊ POSSUI UM NOVO CHAMADO");

        javax.swing.GroupLayout jPavisoAtendimentoLayout = new javax.swing.GroupLayout(jPavisoAtendimento);
        jPavisoAtendimento.setLayout(jPavisoAtendimentoLayout);
        jPavisoAtendimentoLayout.setHorizontalGroup(
            jPavisoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
        );
        jPavisoAtendimentoLayout.setVerticalGroup(
            jPavisoAtendimentoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPavisoAtendimentoLayout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel2)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPavisoAtendimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPavisoAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTaabas)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTaabas))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(800, 667));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTmenuMouseClicked
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null, jTmenu.getLeadSelectionRow());
    }//GEN-LAST:event_jTmenuMouseClicked

    private void jTmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTmenuMousePressed
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null, jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()));         
        getTela();
    }//GEN-LAST:event_jTmenuMousePressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        this.setState(Frame.ICONIFIED);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jBopcoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBopcoesActionPerformed
        // TODO add your handling code here:        
        jPopcoes.show(this, jBopcoes.getX(), jBopcoes.getY());
    }//GEN-LAST:event_jBopcoesActionPerformed

    private void jBopcoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jBopcoesMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_jBopcoesMouseClicked

    private void jPopcoesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPopcoesKeyPressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jPopcoesKeyPressed

    private void jPopcoesMenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jPopcoesMenuKeyPressed
        // TODO add your handling code here:        
    }//GEN-LAST:event_jPopcoesMenuKeyPressed

    private void jMtela01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMtela01ActionPerformed
        // TODO add your handling code here:
        exibeTelaSec(0);
    }//GEN-LAST:event_jMtela01ActionPerformed

    private void jMtela02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMtela02ActionPerformed
        // TODO add your handling code here:
        exibeTelaSec(1);
    }//GEN-LAST:event_jMtela02ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBopcoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLaberto;
    public javax.swing.JLabel jLdata;
    private javax.swing.JLabel jLiniciado;
    private javax.swing.JLabel jLpendente;
    public javax.swing.JLabel jLusuario;
    private javax.swing.JMenuItem jMtela01;
    private javax.swing.JMenuItem jMtela02;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPavisoAtendimento;
    private javax.swing.JPopupMenu jPopcoes;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTaabas;
    private javax.swing.JTree jTmenu;
    // End of variables declaration//GEN-END:variables

    private void inicializaView() {
        jLusuario.setText("Ola " + new UsuarioLogadoBeans().getNome());
        jPavisoAtendimento.setVisible(false);
        jMtela01.setVisible(false);
        jMtela02.setVisible(false);

        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    try {
                        GregorianCalendar x;
                        x = new GregorianCalendar();
                        jLdata.setText(String.valueOf(x.getTime()));
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao Sincronizar Data", "Data", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                    }
                }

            }
        }).start();

        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] devices = ge.getScreenDevices();          
        if (devices.length == 1) {
            jMtela01.setVisible(true);
        } else if (devices.length == 2) {
            jMtela01.setVisible(true);
            jMtela02.setVisible(true);
        }

    }

    private void carregaMenu() {
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("MENU");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cadastro");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = null;

        if (new NivelAcesso().getAcesso("ViewNivel", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nível de Acesso");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewUsuario", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuários");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewVeiculo", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Veiculos");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewPessoa", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empresas");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewListaAtendimento", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Atendimento");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewModulo", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Modulos");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewEmail", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Email");
            treeNode2.add(treeNode3);
        }
        treeNode1.add(treeNode2);

        if (new NivelAcesso().getAcesso("ViewRelatorio", "acessar", false)) {
            treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Relatórios");
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Gerencial");
        }
        if (treeNode3 != null) {
            treeNode2.add(treeNode3);
        }
        if (treeNode2 != null) {
            treeNode1.add(treeNode2);
        }

        jTmenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));

    }

    private Boolean getJanelaAberta(String titulo) {
        Boolean verifica = false;
        for (int i = 0; i < jTaabas.getTabCount(); i++) {
            if (titulo.equals(jTaabas.getTitleAt(i))) {
                verifica = true;
            }
        }
        return verifica;
    }

    private void avisos() {
        new Thread(new Runnable() {

            @Override
            public void run() {

                while (true) {
                    try {
                        getAtendimentoAberto();
                        getAtendimentoTecnico();
                        Thread.sleep(1000);

                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao Carregar Avisos\n" + ex);
                    }
                }

            }
        }).start();

    }

    private void getAtendimentoAberto() {
        jLpendente.setText("Pendentes: " + String.valueOf(new Avisos().getStatusAtendimento("'PENDENTE'", new UsuarioLogadoBeans().getIdusuario(), new UsuarioLogadoBeans().getVchamados())));
        jLaberto.setText("Abertos: " + String.valueOf(new Avisos().getStatusAtendimento("'ABERTO'", new UsuarioLogadoBeans().getIdusuario(), new UsuarioLogadoBeans().getVchamados())));
        jLiniciado.setText("Iniciado: " + String.valueOf(new Avisos().getStatusAtendimento("'INICIADO'", new UsuarioLogadoBeans().getIdusuario(), new UsuarioLogadoBeans().getVchamados())));
    }

    private void getAtendimentoTecnico() throws InterruptedException {
        Integer countAtend = 0;
        countAtend = new Avisos().getStatusAtendimento("'ABERTO'", new UsuarioLogadoBeans().getIdusuario(), false);
        if ((countAtedTecnico == 0) && (countAtend != 0)) {
            countAtedTecnico = countAtend;
            jPavisoAtendimento.setVisible(true);
            Toolkit.getDefaultToolkit().beep();
            Thread.sleep(7000);
            jPavisoAtendimento.setVisible(false);
        }
        if (countAtedTecnico != countAtend) {
            if (countAtedTecnico < countAtend) {
                countAtedTecnico = countAtend;
                jPavisoAtendimento.setVisible(true);
                Toolkit.getDefaultToolkit().beep();
                Thread.sleep(7000);
                jPavisoAtendimento.setVisible(false);
            } else if (countAtedTecnico > countAtend) {
                countAtedTecnico = countAtend;
            }
        }

    }

    private void getTela() {
        if (null != jTmenu.getPathForRow(jTmenu.getLeadSelectionRow())) {
            if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Empresas")) {
                if (!getJanelaAberta("Cadastro de Empresas")) {
                    ViewPessoa viewcadpessoa = new ViewPessoa();
                    jTaabas.addTab("Cadastro de Empresas", null, viewcadpessoa);
                    jTaabas.setSelectedComponent(viewcadpessoa);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Modulos")) {
                if (!getJanelaAberta("Cadastro de Modulos")) {
                    ViewModulo viewmodulo = new ViewModulo();
                    jTaabas.addTab("Cadastro de Modulos", null, viewmodulo);
                    jTaabas.setSelectedComponent(viewmodulo);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Nível de Acesso")) {
                if (!getJanelaAberta("Nível de Acesso")) {
                    ViewNivel viewnivel = new ViewNivel();
                    jTaabas.addTab("Nível de Acesso", null, viewnivel);
                    jTaabas.setSelectedComponent(viewnivel);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Usuários")) {
                if (!getJanelaAberta("Cadastro de Usuários")) {
                    ViewUsuario viewusuario = new ViewUsuario();
                    jTaabas.addTab("Cadastro de Usuários", null, viewusuario);
                    jTaabas.setSelectedComponent(viewusuario);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Veiculos")) {
                if (!getJanelaAberta("Cadastro de Veiculos")) {
                    ViewVeiculo view = new ViewVeiculo();
                    jTaabas.addTab("Cadastro de Veiculos", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Atendimento")) {
                if (!getJanelaAberta("Atendimento")) {
                    ViewListaAtendimento view = new ViewListaAtendimento(this, null);
                    jTaabas.addTab("Atendimento", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Relatórios, Gerencial")) {
                if (!getJanelaAberta("Relatório Gerencial")) {
                    ViewRelatorio view = new ViewRelatorio();
                    jTaabas.addTab("Relatório Gerencial", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Email")) {
                if (!getJanelaAberta("Gerenciador de Email")) {
                    ViewEmail view = new ViewEmail();
                    jTaabas.addTab("Gerenciador de Email", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            }

        }
    }

    private void inicializaAtalhos() {

        //Atalho Atendimento
        KeyStroke keyStrokeAtendimento = KeyStroke.getKeyStroke(KeyEvent.VK_A, KeyEvent.ALT_DOWN_MASK);
        String actionNameAtendimento = "Alt+A";
        InputMap inputMapAtendimento = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapAtendimento.put(keyStrokeAtendimento, actionNameAtendimento);
        ActionMap actionMapAtendimento = jTmenu.getActionMap();
        actionMapAtendimento.put(actionNameAtendimento, acaoAtendimento);

        //Atalho Nivel de Acesso
        KeyStroke keyStrokeNivelAcesso = KeyStroke.getKeyStroke(KeyEvent.VK_N, KeyEvent.ALT_DOWN_MASK);
        String actionNameNivelAcesso = "Alt+N";
        InputMap inputMapNivelAtendimento = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapNivelAtendimento.put(keyStrokeNivelAcesso, actionNameNivelAcesso);
        ActionMap actionMapNivelAcesso = jTmenu.getActionMap();
        actionMapNivelAcesso.put(actionNameNivelAcesso, acaoNivelAcesso);

        //Atalho Usuario
        KeyStroke keyStrokeUsuario = KeyStroke.getKeyStroke(KeyEvent.VK_U, KeyEvent.ALT_DOWN_MASK);
        String actionNameUsuario = "Alt+U";
        InputMap inputMapUsuario = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapUsuario.put(keyStrokeUsuario, actionNameUsuario);
        ActionMap actionMapUsuario = jTmenu.getActionMap();
        actionMapUsuario.put(actionNameUsuario, acaoUsuario);

        //Atalho veiculos
        KeyStroke keyStrokeVeiculo = KeyStroke.getKeyStroke(KeyEvent.VK_V, KeyEvent.ALT_DOWN_MASK);
        String actionNameVeiculo = "Alt+V";
        InputMap inputMapVeiculo = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapVeiculo.put(keyStrokeVeiculo, actionNameVeiculo);
        ActionMap actionMapVeiculo = jTmenu.getActionMap();
        actionMapUsuario.put(actionNameVeiculo, acaoVeiculo);

        //Atalho empresas
        KeyStroke keyStrokeEmpresa = KeyStroke.getKeyStroke(KeyEvent.VK_E, KeyEvent.ALT_DOWN_MASK);
        String actionNameEmpresa = "Alt+E";
        InputMap inputMapEmpresa = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapEmpresa.put(keyStrokeEmpresa, actionNameEmpresa);
        ActionMap actionMapEmpresa = jTmenu.getActionMap();
        actionMapEmpresa.put(actionNameEmpresa, acaoEmpresa);

        //Atalho modulo
        KeyStroke keyStrokeModulo = KeyStroke.getKeyStroke(KeyEvent.VK_M, KeyEvent.ALT_DOWN_MASK);
        String actionNameModulo = "Alt+M";
        InputMap inputMapModulo = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapModulo.put(keyStrokeModulo, actionNameModulo);
        ActionMap actionMapModulo = jTmenu.getActionMap();
        actionMapModulo.put(actionNameModulo, acaoModulo);

    }

    //FUNCAO de atalho Atendimento
    Action acaoAtendimento = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoAtendimento();
        }
    };

    //FUNCAO de atalho Nivel Acesso
    Action acaoNivelAcesso = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoNivelAcesso();
        }
    };

    //FUNCAO de atalho Usuario
    Action acaoUsuario = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoUsuario();
        }
    };

    //FUNCAO de atalho Veiculo
    Action acaoVeiculo = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoVeiculos();
        }
    };

    //FUNCAO de atalho Empresa
    Action acaoEmpresa = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoEmpresa();
        }
    };

    //FUNCAO de atalho modulo
    Action acaoModulo = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoModulos();
        }
    };

    public void getAtalhoAtendimento() {
        if (new NivelAcesso().getAcesso("ViewListaAtendimento", "acessar", false)) {
            if (!getJanelaAberta("Atendimento")) {
                ViewListaAtendimento view = new ViewListaAtendimento(this, null);
                jTaabas.addTab("Atendimento", null, view);
                jTaabas.setSelectedComponent(view);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoNivelAcesso() {
        if (new NivelAcesso().getAcesso("ViewNivel", "acessar", false)) {
            if (!getJanelaAberta("Nível de Acesso")) {
                ViewNivel viewnivel = new ViewNivel();
                jTaabas.addTab("Nível de Acesso", null, viewnivel);
                jTaabas.setSelectedComponent(viewnivel);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoUsuario() {
        if (new NivelAcesso().getAcesso("ViewUsuario", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Usuários")) {
                ViewUsuario viewusuario = new ViewUsuario();
                jTaabas.addTab("Cadastro de Usuários", null, viewusuario);
                jTaabas.setSelectedComponent(viewusuario);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoVeiculos() {
        if (new NivelAcesso().getAcesso("ViewVeiculo", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Veiculos")) {
                ViewVeiculo view = new ViewVeiculo();
                jTaabas.addTab("Cadastro de Veiculos", null, view);
                jTaabas.setSelectedComponent(view);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoEmpresa() {
        if (new NivelAcesso().getAcesso("ViewPessoa", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Empresas")) {
                ViewPessoa viewcadpessoa = new ViewPessoa();
                jTaabas.addTab("Cadastro de Empresas", null, viewcadpessoa);
                jTaabas.setSelectedComponent(viewcadpessoa);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoModulos() {
        if (new NivelAcesso().getAcesso("ViewModulo", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Modulos")) {
                ViewModulo viewmodulo = new ViewModulo();
                jTaabas.addTab("Cadastro de Modulos", null, viewmodulo);
                jTaabas.setSelectedComponent(viewmodulo);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    private void exibeTelaSec(int tela) {
        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        GraphicsDevice[] devices = ge.getScreenDevices();

        devices[tela].setFullScreenWindow(this);
        int xx = (int) this.getLocation().getX();
        int yy = (int) this.getLocation().getY();
        devices[tela].setFullScreenWindow(null);
        this.setLocation(xx, yy);

    }

}
