/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atmatech.sac.view;

import br.com.atmatech.sac.beans.UsuarioLogadoBeans;
import br.com.atmatech.sac.controller.Avisos;
import br.com.atmatech.sac.controller.ButtonTabComponent;
import br.com.atmatech.sac.controller.NivelAcesso;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.util.GregorianCalendar;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author MARCOS
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form ViewPrincipal
     */
    public ViewPrincipal() {

        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        //this.setUndecorated(true);
        inicializaView();
        carregaMenu();
        avisos();
        inicializaAtalhos();
        //coloca a tela cheia em cima da barra de tarefa
//        Dimension d = Toolkit.getDefaultToolkit().getScreenSize();  
//       this.setSize(d);   
//       this.setResizable(false);
//       this.setAlwaysOnTop(false);
//        //this.setAlwaysOnTop(true);  
//        this.setLocationRelativeTo(null);  

//        GraphicsEnvironment ge = GraphicsEnvironment.getLocalGraphicsEnvironment();  
//        GraphicsDevice gd = ge.getDefaultScreenDevice();             
//       // this.setAlwaysOnTop(true);
//        gd.setFullScreenWindow(this);
//        this.validate();
//
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLusuario = new javax.swing.JLabel();
        jLdata = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTmenu = new javax.swing.JTree();
        jTaabas = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLpendente = new javax.swing.JLabel();
        jLaberto = new javax.swing.JLabel();
        jLiniciado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SAC");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(260, 59));

        jLusuario.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        jLdata.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/atmatech/sac/icon/logo.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 369, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLusuario, javax.swing.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jLdata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLusuario, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLdata, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("MENU");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cadastro");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nível de Acesso");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuários");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Veiculos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empresas");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Atendimento");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Modulos");
        treeNode2.add(treeNode3);
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Email");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Relatórios");
        treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Gerencial");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        jTmenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTmenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTmenuMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTmenuMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTmenu);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("AVISOS"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Atendimento:"));

        jLpendente.setForeground(new java.awt.Color(255, 0, 0));
        jLpendente.setText(" ");

        jLaberto.setForeground(new java.awt.Color(255, 255, 0));
        jLaberto.setText(" ");

        jLiniciado.setForeground(new java.awt.Color(255, 255, 255));
        jLiniciado.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLpendente)
                    .addComponent(jLaberto)
                    .addComponent(jLiniciado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLpendente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLaberto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLiniciado)
                .addGap(0, 43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTaabas)
                .addContainerGap())
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jTaabas))
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(816, 638));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTmenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTmenuMouseClicked
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null, jTmenu.getLeadSelectionRow());
    }//GEN-LAST:event_jTmenuMouseClicked

    private void jTmenuMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTmenuMousePressed
        // TODO add your handling code here:
        // JOptionPane.showMessageDialog(null, jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()));         
        getTela();
    }//GEN-LAST:event_jTmenuMousePressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLaberto;
    public javax.swing.JLabel jLdata;
    private javax.swing.JLabel jLiniciado;
    private javax.swing.JLabel jLpendente;
    public javax.swing.JLabel jLusuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTabbedPane jTaabas;
    private javax.swing.JTree jTmenu;
    // End of variables declaration//GEN-END:variables

    private void inicializaView() {
        jLusuario.setText("Ola " + new UsuarioLogadoBeans().getNome());

        new Thread(new Runnable() {

            @Override
            public void run() {
                while (true) {
                    try {
                        GregorianCalendar x;
                        x = new GregorianCalendar();
                        jLdata.setText(String.valueOf(x.getTime()));
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(null, "Erro ao Sincronizar Data", "Data", JOptionPane.ERROR_MESSAGE);
                        System.exit(0);
                    }
                }

            }
        }).start();
    }

    private void carregaMenu() {
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("MENU");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Cadastro");
        javax.swing.tree.DefaultMutableTreeNode treeNode3 = null;

        if (new NivelAcesso().getAcesso("ViewNivel", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Nível de Acesso");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewUsuario", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Usuários");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewVeiculo", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Veiculos");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewPessoa", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Empresas");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewListaAtendimento", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Atendimento");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewModulo", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Modulos");
            treeNode2.add(treeNode3);
        }
        if (new NivelAcesso().getAcesso("ViewEmail", "acessar", false)) {
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Email");
            treeNode2.add(treeNode3);
        }
        treeNode1.add(treeNode2);

        if (new NivelAcesso().getAcesso("ViewRelatorio", "acessar", false)) {
            treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Relatórios");
            treeNode3 = new javax.swing.tree.DefaultMutableTreeNode("Gerencial");
        }
        if (treeNode3 != null) {
            treeNode2.add(treeNode3);
        }
        if (treeNode2 != null) {
            treeNode1.add(treeNode2);
        }

        jTmenu.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));

    }

    private Boolean getJanelaAberta(String titulo) {
        Boolean verifica = false;
        for (int i = 0; i < jTaabas.getTabCount(); i++) {
            if (titulo.equals(jTaabas.getTitleAt(i))) {
                verifica = true;
            }
        }
        return verifica;
    }

    private void avisos() {
        new Thread(new Runnable() {

            @Override
            public void run() {

                while (true) {
                    try {                        
                        getAtendimentoAberto();
                        Thread.sleep(1000);

                    } catch (InterruptedException ex) {
                        JOptionPane.showMessageDialog(rootPane, "Erro ao Carregar Avisos\n" + ex);
                    }
                }

            }
        }).start();

    }

    private void getAtendimentoAberto() {
        jLpendente.setText("Pendentes: " + String.valueOf(new Avisos().getStatusAtendimento("'PENDENTE'", new UsuarioLogadoBeans().getIdusuario(), new UsuarioLogadoBeans().getVchamados())));
        jLaberto.setText("Abertos: " + String.valueOf(new Avisos().getStatusAtendimento("'ABERTO'", new UsuarioLogadoBeans().getIdusuario(), new UsuarioLogadoBeans().getVchamados())));
        jLiniciado.setText("Iniciado: " + String.valueOf(new Avisos().getStatusAtendimento("'INICIADO'", new UsuarioLogadoBeans().getIdusuario(), new UsuarioLogadoBeans().getVchamados())));
    }

    private void getTela() {
        if (null != jTmenu.getPathForRow(jTmenu.getLeadSelectionRow())) {
            if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Empresas")) {
                if (!getJanelaAberta("Cadastro de Empresas")) {
                    ViewPessoa viewcadpessoa = new ViewPessoa();
                    jTaabas.addTab("Cadastro de Empresas", null, viewcadpessoa);
                    jTaabas.setSelectedComponent(viewcadpessoa);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Modulos")) {
                if (!getJanelaAberta("Cadastro de Modulos")) {
                    ViewModulo viewmodulo = new ViewModulo();
                    jTaabas.addTab("Cadastro de Modulos", null, viewmodulo);
                    jTaabas.setSelectedComponent(viewmodulo);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Nível de Acesso")) {
                if (!getJanelaAberta("Nível de Acesso")) {
                    ViewNivel viewnivel = new ViewNivel();
                    jTaabas.addTab("Nível de Acesso", null, viewnivel);
                    jTaabas.setSelectedComponent(viewnivel);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Usuários")) {
                if (!getJanelaAberta("Cadastro de Usuários")) {
                    ViewUsuario viewusuario = new ViewUsuario();
                    jTaabas.addTab("Cadastro de Usuários", null, viewusuario);
                    jTaabas.setSelectedComponent(viewusuario);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Veiculos")) {
                if (!getJanelaAberta("Cadastro de Veiculos")) {
                    ViewVeiculo view = new ViewVeiculo();
                    jTaabas.addTab("Cadastro de Veiculos", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Atendimento")) {
                if (!getJanelaAberta("Atendimento")) {
                    ViewListaAtendimento view = new ViewListaAtendimento(this, null);
                    jTaabas.addTab("Atendimento", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Relatórios, Gerencial")) {
                if (!getJanelaAberta("Relatório Gerencial")) {
                    ViewRelatorio view = new ViewRelatorio();
                    jTaabas.addTab("Relatório Gerencial", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            } else if (jTmenu.getPathForRow(jTmenu.getLeadSelectionRow()).toString().contains("[MENU, Cadastro, Email")) {
                if (!getJanelaAberta("Gerenciador de Email")) {
                    ViewEmail view = new ViewEmail();
                    jTaabas.addTab("Gerenciador de Email", null, view);
                    jTaabas.setSelectedComponent(view);
                    int j = jTaabas.getSelectedIndex();
                    jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
                }
            }

        }
    }

    private void inicializaAtalhos() {

        //Atalho Atendimento
        KeyStroke keyStrokeAtendimento = KeyStroke.getKeyStroke(KeyEvent.VK_A, KeyEvent.ALT_DOWN_MASK);
        String actionNameAtendimento = "Alt+A";
        InputMap inputMapAtendimento = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapAtendimento.put(keyStrokeAtendimento, actionNameAtendimento);
        ActionMap actionMapAtendimento = jTmenu.getActionMap();
        actionMapAtendimento.put(actionNameAtendimento, acaoAtendimento);

        //Atalho Nivel de Acesso
        KeyStroke keyStrokeNivelAcesso = KeyStroke.getKeyStroke(KeyEvent.VK_N, KeyEvent.ALT_DOWN_MASK);
        String actionNameNivelAcesso = "Alt+N";
        InputMap inputMapNivelAtendimento = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapNivelAtendimento.put(keyStrokeNivelAcesso, actionNameNivelAcesso);
        ActionMap actionMapNivelAcesso = jTmenu.getActionMap();
        actionMapNivelAcesso.put(actionNameNivelAcesso, acaoNivelAcesso);

        //Atalho Usuario
        KeyStroke keyStrokeUsuario = KeyStroke.getKeyStroke(KeyEvent.VK_U, KeyEvent.ALT_DOWN_MASK);
        String actionNameUsuario = "Alt+U";
        InputMap inputMapUsuario = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapUsuario.put(keyStrokeUsuario, actionNameUsuario);
        ActionMap actionMapUsuario = jTmenu.getActionMap();
        actionMapUsuario.put(actionNameUsuario, acaoUsuario);

        //Atalho veiculos
        KeyStroke keyStrokeVeiculo = KeyStroke.getKeyStroke(KeyEvent.VK_V, KeyEvent.ALT_DOWN_MASK);
        String actionNameVeiculo = "Alt+V";
        InputMap inputMapVeiculo = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapVeiculo.put(keyStrokeVeiculo, actionNameVeiculo);
        ActionMap actionMapVeiculo = jTmenu.getActionMap();
        actionMapUsuario.put(actionNameVeiculo, acaoVeiculo);

        //Atalho empresas
        KeyStroke keyStrokeEmpresa = KeyStroke.getKeyStroke(KeyEvent.VK_E, KeyEvent.ALT_DOWN_MASK);
        String actionNameEmpresa = "Alt+E";
        InputMap inputMapEmpresa = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapEmpresa.put(keyStrokeEmpresa, actionNameEmpresa);
        ActionMap actionMapEmpresa = jTmenu.getActionMap();
        actionMapEmpresa.put(actionNameEmpresa, acaoEmpresa);

        //Atalho modulo
        KeyStroke keyStrokeModulo = KeyStroke.getKeyStroke(KeyEvent.VK_M, KeyEvent.ALT_DOWN_MASK);
        String actionNameModulo = "Alt+M";
        InputMap inputMapModulo = jTmenu.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapModulo.put(keyStrokeModulo, actionNameModulo);
        ActionMap actionMapModulo = jTmenu.getActionMap();
        actionMapModulo.put(actionNameModulo, acaoModulo);

    }

    //FUNCAO de atalho Atendimento
    Action acaoAtendimento = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoAtendimento();
        }
    };

    //FUNCAO de atalho Nivel Acesso
    Action acaoNivelAcesso = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoNivelAcesso();
        }
    };

    //FUNCAO de atalho Usuario
    Action acaoUsuario = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoUsuario();
        }
    };

    //FUNCAO de atalho Veiculo
    Action acaoVeiculo = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoVeiculos();
        }
    };

    //FUNCAO de atalho Empresa
    Action acaoEmpresa = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoEmpresa();
        }
    };

    //FUNCAO de atalho modulo
    Action acaoModulo = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão  
            getAtalhoModulos();
        }
    };

    public void getAtalhoAtendimento() {
        if (new NivelAcesso().getAcesso("ViewListaAtendimento", "acessar", false)) {
            if (!getJanelaAberta("Atendimento")) {
                ViewListaAtendimento view = new ViewListaAtendimento(this, null);
                jTaabas.addTab("Atendimento", null, view);
                jTaabas.setSelectedComponent(view);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoNivelAcesso() {
        if (new NivelAcesso().getAcesso("ViewNivel", "acessar", false)) {
            if (!getJanelaAberta("Nível de Acesso")) {
                ViewNivel viewnivel = new ViewNivel();
                jTaabas.addTab("Nível de Acesso", null, viewnivel);
                jTaabas.setSelectedComponent(viewnivel);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoUsuario() {
        if (new NivelAcesso().getAcesso("ViewUsuario", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Usuários")) {
                ViewUsuario viewusuario = new ViewUsuario();
                jTaabas.addTab("Cadastro de Usuários", null, viewusuario);
                jTaabas.setSelectedComponent(viewusuario);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoVeiculos() {
        if (new NivelAcesso().getAcesso("ViewVeiculo", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Veiculos")) {
                ViewVeiculo view = new ViewVeiculo();
                jTaabas.addTab("Cadastro de Veiculos", null, view);
                jTaabas.setSelectedComponent(view);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoEmpresa() {
        if (new NivelAcesso().getAcesso("ViewPessoa", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Empresas")) {
                ViewPessoa viewcadpessoa = new ViewPessoa();
                jTaabas.addTab("Cadastro de Empresas", null, viewcadpessoa);
                jTaabas.setSelectedComponent(viewcadpessoa);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }

    public void getAtalhoModulos() {
        if (new NivelAcesso().getAcesso("ViewModulo", "acessar", false)) {
            if (!getJanelaAberta("Cadastro de Modulos")) {
                ViewModulo viewmodulo = new ViewModulo();
                jTaabas.addTab("Cadastro de Modulos", null, viewmodulo);
                jTaabas.setSelectedComponent(viewmodulo);
                int j = jTaabas.getSelectedIndex();
                jTaabas.setTabComponentAt(j, new ButtonTabComponent(jTaabas));
            }
        }
    }
}
