/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atmatech.painel.view;

import br.com.atmatech.painel.beans.DBConfigBeans;
import br.com.atmatech.painel.config.DBConfig;
import com.towel.swing.img.JImagePanel;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Marcos
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form viewPrincipal
     */
    int x=0;
    Thread vthreadletreiro;
    boolean ativaletreiro=false;
    JImagePanel background;

    public ViewPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        try {
            jMenu.setVisible(false);
            DBConfigBeans dbc = new DBConfig().getConfig();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Carregar Config \n" + ex);
            System.exit(0);
        }
        
        inicializaCorBackground();
        inicializaGrade();
        inicializarAtalhos();
        inicializaLetreiro();  
        inicializaTipoLayout();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDcarga = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTlocalbalancabanco = new javax.swing.JTextField();
        jTusuariobalancabanco = new javax.swing.JTextField();
        jTsenhabalancabanco = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTsenhabanco = new javax.swing.JTextField();
        jTusuariobanco = new javax.swing.JTextField();
        jTlocalbanco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDlayout = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jRTabela1 = new javax.swing.JRadioButton();
        jRTabela2 = new javax.swing.JRadioButton();
        jRTabela3 = new javax.swing.JRadioButton();
        jRTabela4 = new javax.swing.JRadioButton();
        jSLinhaTabela = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jRSequencial = new javax.swing.JRadioButton();
        jRTabelaCheia = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        jRletreiro = new javax.swing.JRadioButton();
        jTletreirotexto = new javax.swing.JTextField();
        jStransicaoLetreiro = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        jPCorFundoLetreiro = new javax.swing.JPanel();
        jPCorFonteLetreiro = new javax.swing.JPanel();
        jBsalvar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jCTipoLocalizacao = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jSTamanhox = new javax.swing.JSpinner();
        jLabel11 = new javax.swing.JLabel();
        jSTamanhoy = new javax.swing.JSpinner();
        jTFileImagem1 = new javax.swing.JTextField();
        jBImagem1 = new javax.swing.JButton();
        GroupTabelas = new javax.swing.ButtonGroup();
        jDFileImagem = new javax.swing.JDialog();
        jFileChooser1 = new javax.swing.JFileChooser();
        jDColorLetreiro = new javax.swing.JDialog();
        jColorChooser1 = new javax.swing.JColorChooser();
        jPbackground = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPimagem1 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPletreiro = new javax.swing.JPanel();
        jPletreiroint = new javax.swing.JPanel();
        jLletreirointFrase = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jDcarga.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDcarga.setTitle("CARGA");
        jDcarga.setAlwaysOnTop(true);
        jDcarga.setMinimumSize(new java.awt.Dimension(465, 300));
        jDcarga.setModal(true);
        jDcarga.setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Banco Balança"));

        jLabel1.setText("Local:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Senha:");

        jTlocalbalancabanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTlocalbalancabancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTlocalbalancabanco)
                    .addComponent(jTusuariobalancabanco)
                    .addComponent(jTsenhabalancabanco))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTlocalbalancabanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTusuariobalancabanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTsenhabalancabanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Banco Local"));

        jLabel4.setText("Local:");

        jLabel5.setText("Usuario:");

        jLabel6.setText("Senha:");

        jTsenhabanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsenhabancoActionPerformed(evt);
            }
        });

        jTlocalbanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTlocalbancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTlocalbanco)
                    .addComponent(jTusuariobanco, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(jTsenhabanco))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTlocalbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTusuariobanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTsenhabanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDcargaLayout = new javax.swing.GroupLayout(jDcarga.getContentPane());
        jDcarga.getContentPane().setLayout(jDcargaLayout);
        jDcargaLayout.setHorizontalGroup(
            jDcargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDcargaLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDcargaLayout.setVerticalGroup(
            jDcargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDcargaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        jDlayout.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDlayout.setTitle("Layout");
        jDlayout.setMinimumSize(new java.awt.Dimension(600, 460));
        jDlayout.setPreferredSize(new java.awt.Dimension(600, 460));
        jDlayout.setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabelas"));
        jPanel4.setToolTipText("");

        GroupTabelas.add(jRTabela1);
        jRTabela1.setText("1 Tabela");

        GroupTabelas.add(jRTabela2);
        jRTabela2.setText("2 Tabelas");

        GroupTabelas.add(jRTabela3);
        jRTabela3.setText("3 Tabelas");

        GroupTabelas.add(jRTabela4);
        jRTabela4.setText("4 Tabelas");

        jSLinhaTabela.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel8.setText("Linhas Por Tabelas");

        jRSequencial.setText("Tabelas Sequenciais");

        jRTabelaCheia.setText("Tabelas Cheias");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRTabela1)
                    .addComponent(jRTabela2)
                    .addComponent(jRTabela3)
                    .addComponent(jRTabela4))
                .addGap(61, 61, 61)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jSLinhaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jRTabelaCheia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRSequencial, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTabela1)
                    .addComponent(jSLinhaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTabela2)
                    .addComponent(jRSequencial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTabela3)
                    .addComponent(jRTabelaCheia))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRTabela4)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Letreiro"));

        jRletreiro.setText("Letreiro");
        jRletreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRletreiroActionPerformed(evt);
            }
        });

        jTletreirotexto.setDocument(new br.com.atmatech.painel.util.LimitaCaracterUpper(100,true));

        jStransicaoLetreiro.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel9.setText("Tempo Transição Letreiro");

        jPCorFundoLetreiro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cor Fundo"));
        jPCorFundoLetreiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPCorFundoLetreiroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCorFundoLetreiroLayout = new javax.swing.GroupLayout(jPCorFundoLetreiro);
        jPCorFundoLetreiro.setLayout(jPCorFundoLetreiroLayout);
        jPCorFundoLetreiroLayout.setHorizontalGroup(
            jPCorFundoLetreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPCorFundoLetreiroLayout.setVerticalGroup(
            jPCorFundoLetreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        jPCorFonteLetreiro.setBorder(javax.swing.BorderFactory.createTitledBorder("Cor Fonte"));
        jPCorFonteLetreiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPCorFonteLetreiroMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPCorFonteLetreiroLayout = new javax.swing.GroupLayout(jPCorFonteLetreiro);
        jPCorFonteLetreiro.setLayout(jPCorFonteLetreiroLayout);
        jPCorFonteLetreiroLayout.setHorizontalGroup(
            jPCorFonteLetreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 80, Short.MAX_VALUE)
        );
        jPCorFonteLetreiroLayout.setVerticalGroup(
            jPCorFonteLetreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jRletreiro)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTletreirotexto, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jStransicaoLetreiro, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jPCorFundoLetreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPCorFonteLetreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRletreiro)
                    .addComponent(jTletreirotexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jStransicaoLetreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPCorFundoLetreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPCorFonteLetreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jBsalvar.setText("Salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Plano de Fundo"));

        jCTipoLocalizacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "RESIZE", "CENTER", "SIDE_BY_SIDE" }));
        jCTipoLocalizacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCTipoLocalizacaoActionPerformed(evt);
            }
        });

        jLabel7.setText("Tipo de Localização");

        jSTamanhox.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel11.setText("Tamanho Plano de Fundo");

        jSTamanhoy.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jTFileImagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTFileImagem1ActionPerformed(evt);
            }
        });

        jBImagem1.setText("...");
        jBImagem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBImagem1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jSTamanhox, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSTamanhoy, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jCTipoLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTFileImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, Short.MAX_VALUE)
                .addGap(62, 62, 62))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCTipoLocalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jTFileImagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBImagem1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSTamanhox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSTamanhoy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jDlayoutLayout = new javax.swing.GroupLayout(jDlayout.getContentPane());
        jDlayout.getContentPane().setLayout(jDlayoutLayout);
        jDlayoutLayout.setHorizontalGroup(
            jDlayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDlayoutLayout.createSequentialGroup()
                .addComponent(jBsalvar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDlayoutLayout.setVerticalGroup(
            jDlayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDlayoutLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBsalvar)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jDFileImagem.setTitle("ARQUIVO");
        jDFileImagem.setMinimumSize(new java.awt.Dimension(614, 397));
        jDFileImagem.setModal(true);

        jFileChooser1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFileChooser1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDFileImagemLayout = new javax.swing.GroupLayout(jDFileImagem.getContentPane());
        jDFileImagem.getContentPane().setLayout(jDFileImagemLayout);
        jDFileImagemLayout.setHorizontalGroup(
            jDFileImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDFileImagemLayout.setVerticalGroup(
            jDFileImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDFileImagemLayout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jDColorLetreiro.setTitle("Cor");
        jDColorLetreiro.setMinimumSize(new java.awt.Dimension(615, 350));
        jDColorLetreiro.setModal(true);
        jDColorLetreiro.setPreferredSize(new java.awt.Dimension(615, 350));
        jDColorLetreiro.setResizable(false);

        jColorChooser1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jColorChooser1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jDColorLetreiroLayout = new javax.swing.GroupLayout(jDColorLetreiro.getContentPane());
        jDColorLetreiro.getContentPane().setLayout(jDColorLetreiroLayout);
        jDColorLetreiroLayout.setHorizontalGroup(
            jDColorLetreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDColorLetreiroLayout.setVerticalGroup(
            jDColorLetreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDColorLetreiroLayout.createSequentialGroup()
                .addComponent(jColorChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jPbackground.setBackground(new java.awt.Color(204, 0, 0));
        jPbackground.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jPimagem1.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPimagem1Layout = new javax.swing.GroupLayout(jPimagem1);
        jPimagem1.setLayout(jPimagem1Layout);
        jPimagem1Layout.setHorizontalGroup(
            jPimagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPimagem1Layout.setVerticalGroup(
            jPimagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 87, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jPletreiro.setBackground(new java.awt.Color(204, 0, 0));

        jPletreiroint.setBackground(new java.awt.Color(204, 0, 0));

        jLletreirointFrase.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPletreirointLayout = new javax.swing.GroupLayout(jPletreiroint);
        jPletreiroint.setLayout(jPletreirointLayout);
        jPletreirointLayout.setHorizontalGroup(
            jPletreirointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPletreirointLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLletreirointFrase, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPletreirointLayout.setVerticalGroup(
            jPletreirointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLletreirointFrase, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPletreiroLayout = new javax.swing.GroupLayout(jPletreiro);
        jPletreiro.setLayout(jPletreiroLayout);
        jPletreiroLayout.setHorizontalGroup(
            jPletreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPletreiroLayout.createSequentialGroup()
                .addGap(0, 1221, Short.MAX_VALUE)
                .addComponent(jPletreiroint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPletreiroLayout.setVerticalGroup(
            jPletreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPletreiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPletreiroint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPbackgroundLayout = new javax.swing.GroupLayout(jPbackground);
        jPbackground.setLayout(jPbackgroundLayout);
        jPbackgroundLayout.setHorizontalGroup(
            jPbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPimagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbackgroundLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPletreiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPbackgroundLayout.setVerticalGroup(
            jPbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbackgroundLayout.createSequentialGroup()
                .addComponent(jPimagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPletreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Configuração");

        jMenuItem1.setText("Carga");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Layout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenu.add(jMenu1);

        jMenu2.setText("Sair");

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenu.add(jMenu2);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:        
        DBConfigBeans dbc = new DBConfigBeans();
        jTlocalbalancabanco.setText(dbc.getDirdb());
        jTusuariobalancabanco.setText(dbc.getUser());
        jTsenhabalancabanco.setText(dbc.getPassword());
        jTlocalbanco.setText(dbc.getLocaldirdb());
        jTusuariobanco.setText(dbc.getLocaluser());
        jTsenhabanco.setText(dbc.getLocalpassword());
        jDcarga.setLocationRelativeTo(this);
        jDcarga.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DBConfigBeans dbc = new DBConfigBeans();
        jRTabela1.setSelected(dbc.isTabela1());
        jRTabela2.setSelected(dbc.isTabela2());
        jRTabela3.setSelected(dbc.isTabela3());
        jRTabela4.setSelected(dbc.isTabela4());
        jRSequencial.setSelected(dbc.isSequencial());
        jRletreiro.setSelected(dbc.isLetreiro());
        jSLinhaTabela.setValue((Integer) dbc.getLinhatabela());        
        jTletreirotexto.setText(dbc.getLetreirotexto());
        jStransicaoLetreiro.setValue((Integer) dbc.getLetreirotempo());
        jRTabelaCheia.setSelected(dbc.isTabelacheia());
        jCTipoLocalizacao.setSelectedItem(dbc.getTipolocalizacao());        
        jTFileImagem1.setText(dbc.getFundoimagem1());        
        jSTamanhox.setValue(dbc.getTamanhox());
        jSTamanhoy.setValue(dbc.getTamanhoy());
        jPCorFundoLetreiro.setBackground(new Color(Integer.valueOf(dbc.getLetreirocorfundo())));
        jPCorFonteLetreiro.setBackground(new Color(Integer.valueOf(dbc.getLetreirocorfonte())));
        jDlayout.setLocationRelativeTo(this);
        jDlayout.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DBConfigBeans dbc = new DBConfigBeans();
        dbc.setDirdb(jTlocalbalancabanco.getText());
        dbc.setUser(jTsenhabalancabanco.getText());
        dbc.setPassword(jTsenhabalancabanco.getText());
        dbc.setLocaldirdb(jTlocalbanco.getText());
        dbc.setLocalpassword(jTsenhabanco.getText());
        dbc.setLocaluser(jTusuariobanco.getText());
        try {
            new DBConfig().createConfig(dbc);
            jDcarga.setVisible(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Salvar" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTlocalbalancabancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTlocalbalancabancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTlocalbalancabancoActionPerformed

    private void jTlocalbancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTlocalbancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTlocalbancoActionPerformed

    private void jTsenhabancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsenhabancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsenhabancoActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        DBConfigBeans dbc = new DBConfigBeans();
        dbc.setTabela1(jRTabela1.isSelected());
        dbc.setTabela2(jRTabela2.isSelected());
        dbc.setTabela3(jRTabela3.isSelected());
        dbc.setTabela4(jRTabela4.isSelected());
        dbc.setSequencial(jRSequencial.isSelected());
        dbc.setLetreiro(jRletreiro.isSelected());
        dbc.setLinhatabela((Integer) jSLinhaTabela.getValue());
        dbc.setLetreirotexto(jTletreirotexto.getText());
        dbc.setLetreirotempo((Integer) jStransicaoLetreiro.getValue());
        dbc.setTabelacheia(jRTabelaCheia.isSelected());
        dbc.setTipolocalizacao(jCTipoLocalizacao.getSelectedItem().toString());        
        dbc.setFundoimagem1(jTFileImagem1.getText());        
        dbc.setTamanhox((Integer) jSTamanhox.getValue());
        dbc.setTamanhoy((Integer) jSTamanhoy.getValue());                
        dbc.setLetreirocorfundo(String.valueOf(jPCorFundoLetreiro.getBackground().getRGB()));
        dbc.setLetreirocorfonte(String.valueOf(jPCorFonteLetreiro.getBackground().getRGB()));
        try {
            new DBConfig().createConfig(dbc);
            jDlayout.setVisible(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Salvar" + ex);
        }
        if (jPanel3.getComponentCount() > 0) {
            for (int i = 0; i < jPanel3.getComponentCount(); i++) {
                jPanel3.getComponent(i).setVisible(false);
            }
            jPanel3.setVisible(false);
            jPanel3.setVisible(true);            
            inicializaCorBackground();
            inicializaGrade();
            inicializaLetreiro(); 
            inicializaTipoLayout();            
        }

    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jRletreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRletreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRletreiroActionPerformed

    private void jTFileImagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTFileImagem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTFileImagem1ActionPerformed

    private void jCTipoLocalizacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCTipoLocalizacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCTipoLocalizacaoActionPerformed

    private void jBImagem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBImagem1ActionPerformed
        // TODO add your handling code here:
        jDFileImagem.setLocationRelativeTo(null);
        jDFileImagem.setVisible(true);
        String file=jFileChooser1.getSelectedFile().toString();
        jTFileImagem1.setText(file);
    }//GEN-LAST:event_jBImagem1ActionPerformed

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        // TODO add your handling code here:       
        jDFileImagem.setVisible(false);
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    private void jPCorFundoLetreiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPCorFundoLetreiroMouseClicked
        // TODO add your handling code here:
        jDColorLetreiro.setLocationRelativeTo(null);
        jDColorLetreiro.setVisible(true);
        jPCorFundoLetreiro.setBackground(jColorChooser1.getColor());
    }//GEN-LAST:event_jPCorFundoLetreiroMouseClicked

    private void jColorChooser1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jColorChooser1MouseClicked
        // TODO add your handling code here:
        if(evt.getClickCount()==2){
            jDColorLetreiro.setVisible(false);
        }
    }//GEN-LAST:event_jColorChooser1MouseClicked

    private void jPCorFonteLetreiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPCorFonteLetreiroMouseClicked
        // TODO add your handling code here:
        jDColorLetreiro.setLocationRelativeTo(null);
        jDColorLetreiro.setVisible(true);
        jPCorFonteLetreiro.setBackground(jColorChooser1.getColor());
    }//GEN-LAST:event_jPCorFonteLetreiroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupTabelas;
    private javax.swing.JButton jBImagem1;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jCTipoLocalizacao;
    private javax.swing.JColorChooser jColorChooser1;
    private javax.swing.JDialog jDColorLetreiro;
    private javax.swing.JDialog jDFileImagem;
    private javax.swing.JDialog jDcarga;
    private javax.swing.JDialog jDlayout;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLletreirointFrase;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPCorFonteLetreiro;
    private javax.swing.JPanel jPCorFundoLetreiro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPbackground;
    private javax.swing.JPanel jPimagem1;
    private javax.swing.JPanel jPletreiro;
    private javax.swing.JPanel jPletreiroint;
    private javax.swing.JRadioButton jRSequencial;
    private javax.swing.JRadioButton jRTabela1;
    private javax.swing.JRadioButton jRTabela2;
    private javax.swing.JRadioButton jRTabela3;
    private javax.swing.JRadioButton jRTabela4;
    private javax.swing.JRadioButton jRTabelaCheia;
    private javax.swing.JRadioButton jRletreiro;
    private javax.swing.JSpinner jSLinhaTabela;
    private javax.swing.JSpinner jSTamanhox;
    private javax.swing.JSpinner jSTamanhoy;
    private javax.swing.JSpinner jStransicaoLetreiro;
    private javax.swing.JTextField jTFileImagem1;
    private javax.swing.JTextField jTletreirotexto;
    private javax.swing.JTextField jTlocalbalancabanco;
    private javax.swing.JTextField jTlocalbanco;
    private javax.swing.JTextField jTsenhabalancabanco;
    private javax.swing.JTextField jTsenhabanco;
    private javax.swing.JTextField jTusuariobalancabanco;
    private javax.swing.JTextField jTusuariobanco;
    // End of variables declaration//GEN-END:variables

    private void inicializarAtalhos() {
        KeyStroke keyStrokeJBalterar = KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0);
        String actionNameJBalterar = "TECLA_F3";
        InputMap inputMapJBalterar = jPbackground.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapJBalterar.put(keyStrokeJBalterar, actionNameJBalterar);
        ActionMap actionMapJBMARCA = jPbackground.getActionMap();
        actionMapJBMARCA.put(actionNameJBalterar, ativaMenu);

        //Atalho enter
//        InputMap inputMapJBenter = this.jPimagem1.getRootPane().getInputMap(JComponent.HEIGHT);
//        inputMapJBenter.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "forward");
//        this.jPimagem1.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMapJBenter);
//        this.jPimagem1.getRootPane().getActionMap().put("forward", new AbstractAction() {
//            private static final long serialVersionUID = 1L;
//
//            @Override
//            public void actionPerformed(ActionEvent e) {
//                System.err.print("Atalho 2");
//                if (jMenu.isVisible()) {
//                    jMenu.setVisible(false);
//                } else {
//                    jMenu.setVisible(true);
//                }
//            }
//
//        });

    }

    Action ativaMenu = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão              
            if (jMenu.isVisible()) {
                jMenu.setVisible(false);
            } else {
                jMenu.setVisible(true);
            }
        }
    };

    private void inicializaGrade() {
        DBConfigBeans dbc = new DBConfigBeans();
        Integer tabelas = 0;
        if (dbc.isTabela1()) {
            tabelas = 1;
        } else if (dbc.isTabela2()) {
            tabelas = 2;
        } else if (dbc.isTabela3()) {
            tabelas = 3;
        } else if (dbc.isTabela4()) {
            tabelas = 4;
        }
        ViewLayoutTabelas view = new ViewLayoutTabelas(tabelas);
        view.setSize(300, 300);
        jPanel3.add(view);
        jPanel3.repaint();
        jPanel3.validate();              
    }

    private void threadletreiro(final String frase,final Integer tempo) {                       
        x=jPletreiro.getSize().width; 
        vthreadletreiro=new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(tempo);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    jLletreirointFrase.setText(frase.toUpperCase());
                    jPletreiroint.setLocation(x--, jPletreiroint.getY());                                        
                    if((0-(jLletreirointFrase.getText().length()*20))>=x){
                        x=jPletreiro.getSize().width; 
                    }
                }
            }
        });
        vthreadletreiro.start();
        
    }

    private void inicializaLetreiro() {
        DBConfigBeans dbc = new DBConfigBeans();
        jPletreiro.setBackground(new Color(Integer.valueOf(dbc.getLetreirocorfundo())));
        jPletreiroint.setBackground(new Color(Integer.valueOf(dbc.getLetreirocorfundo())));
        jLletreirointFrase.setForeground(new Color(Integer.valueOf(dbc.getLetreirocorfonte())));
        if (dbc.isLetreiro()) {
            if(vthreadletreiro==null){
            jPletreiro.setVisible(true);
            threadletreiro(dbc.getLetreirotexto(),dbc.getLetreirotempo());
            }else if(vthreadletreiro.isAlive()){
             vthreadletreiro.stop();
             jPletreiro.setVisible(false);
             jPletreiro.setVisible(true);             
            threadletreiro(dbc.getLetreirotexto(),dbc.getLetreirotempo());
            }else{
            jPletreiro.setVisible(true);
            threadletreiro(dbc.getLetreirotexto(),dbc.getLetreirotempo());
            }
        } else {
            if(vthreadletreiro!=null){                    
                vthreadletreiro.stop();
            }
            jPletreiro.setVisible(false);
        }
    }

    private void inicializaBackground() {
        try {
            
            DBConfigBeans dbc=new DBConfigBeans();    
            if(dbc.getFundoimagem1().length()>3){
                background=new JImagePanel(loadImage(dbc.getFundoimagem1()));
            }else{
            background=new JImagePanel(loadImage("./imagem/Padrao1.jpg"));
            }
            background.setVisible(true);
            background.setSize(dbc.getTamanhox(),dbc.getTamanhoy());
            String filltype=dbc.getTipolocalizacao();
            background.setFillType(JImagePanel.FillType.valueOf(filltype));            
            //jPbackground.add(background);
            if(jPbackground.getComponentCount()==5){
            jPbackground.remove(4);    
            }                        
            jPbackground.add(background);
            jPbackground.repaint();
            jPbackground.validate();            
        } catch (IOException ex) {
            new DBConfig().createArq("Erro ao Buscar Imagem Background"+ex);
        }
    }

    private BufferedImage loadImage(String file) throws IOException {
        return ImageIO.read(new File(file));
    }

    private void inicializaCorBackground() {
        Color cor=new Color(0,0,0,0);
        jPanel3.setBackground(cor);
        jPimagem1.setBackground(cor);
        jPanel6.setBackground(cor);          
        inicializaBackground();
    }

    private void inicializaTipoLayout() {
        DBConfigBeans dbc=new DBConfigBeans();
        if(dbc.isTabelacheia()){
            jPimagem1.setVisible(false);
            jPanel6.setVisible(false);
        }else{
            jPimagem1.setVisible(true);
            jPanel6.setVisible(true);
        }
    }

}
