/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atmatech.painel.view;

import br.com.atmatech.painel.beans.DBConfigBeans;
import br.com.atmatech.painel.config.DBConfig;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.KeyStroke;

/**
 *
 * @author Marcos
 */
public class ViewPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form viewPrincipal
     */
    int x=0;

    public ViewPrincipal() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        try {
            jMenu.setVisible(false);
            DBConfigBeans dbc = new DBConfig().getConfig();
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao Carregar Config \n" + ex);
            System.exit(0);
        }
        
        inicializaGrade();
        inicializarAtalhos();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDcarga = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTlocalbalancabanco = new javax.swing.JTextField();
        jTusuariobalancabanco = new javax.swing.JTextField();
        jTsenhabalancabanco = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTsenhabanco = new javax.swing.JTextField();
        jTusuariobanco = new javax.swing.JTextField();
        jTlocalbanco = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jDlayout = new javax.swing.JDialog();
        jPanel4 = new javax.swing.JPanel();
        jRTabela1 = new javax.swing.JRadioButton();
        jRTabela2 = new javax.swing.JRadioButton();
        jRTabela3 = new javax.swing.JRadioButton();
        jRTabela4 = new javax.swing.JRadioButton();
        jSLinhaTabela = new javax.swing.JSpinner();
        jLabel8 = new javax.swing.JLabel();
        jRSequencial = new javax.swing.JRadioButton();
        jRletreiro = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jBsalvar = new javax.swing.JButton();
        GroupTabelas = new javax.swing.ButtonGroup();
        jPbackground = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPimagem1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPletreiro = new javax.swing.JPanel();
        jPletreiroint = new javax.swing.JPanel();
        jLletreirointFrase = new javax.swing.JLabel();
        jMenu = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        jDcarga.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDcarga.setTitle("CARGA");
        jDcarga.setAlwaysOnTop(true);
        jDcarga.setMinimumSize(new java.awt.Dimension(465, 300));
        jDcarga.setModal(true);
        jDcarga.setResizable(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Banco Balança"));

        jLabel1.setText("Local:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Senha:");

        jTlocalbalancabanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTlocalbalancabancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTlocalbalancabanco)
                    .addComponent(jTusuariobalancabanco)
                    .addComponent(jTsenhabalancabanco))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTlocalbalancabanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTusuariobalancabanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTsenhabalancabanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Banco Local"));

        jLabel4.setText("Local:");

        jLabel5.setText("Usuario:");

        jLabel6.setText("Senha:");

        jTsenhabanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTsenhabancoActionPerformed(evt);
            }
        });

        jTlocalbanco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTlocalbancoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel6)
                        .addComponent(jLabel5))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTlocalbanco)
                    .addComponent(jTusuariobanco, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                    .addComponent(jTsenhabanco))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTlocalbanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTusuariobanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTsenhabanco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("SALVAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDcargaLayout = new javax.swing.GroupLayout(jDcarga.getContentPane());
        jDcarga.getContentPane().setLayout(jDcargaLayout);
        jDcargaLayout.setHorizontalGroup(
            jDcargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDcargaLayout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDcargaLayout.setVerticalGroup(
            jDcargaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDcargaLayout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12))
        );

        jDlayout.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDlayout.setTitle("Layout");
        jDlayout.setMinimumSize(new java.awt.Dimension(543, 321));
        jDlayout.setResizable(false);

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabelas"));
        jPanel4.setToolTipText("");

        GroupTabelas.add(jRTabela1);
        jRTabela1.setText("1 Tabela");

        GroupTabelas.add(jRTabela2);
        jRTabela2.setText("2 Tabelas");

        GroupTabelas.add(jRTabela3);
        jRTabela3.setText("3 Tabelas");

        GroupTabelas.add(jRTabela4);
        jRTabela4.setText("4 Tabelas");

        jSLinhaTabela.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));

        jLabel8.setText("Linhas Por Tabelas");

        jRSequencial.setText("Tabelas Sequenciais");

        jRletreiro.setText("Letreiro");
        jRletreiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRletreiroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRTabela4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRTabela1)
                            .addComponent(jRTabela2)
                            .addComponent(jRTabela3))
                        .addGap(61, 61, 61)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jRletreiro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRSequencial)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jSLinhaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))))
                .addGap(0, 122, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTabela1)
                    .addComponent(jSLinhaTabela, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTabela2)
                    .addComponent(jRSequencial))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRTabela3)
                    .addComponent(jRletreiro)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jRTabela4)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tabelas Fonte"));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 531, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 104, Short.MAX_VALUE)
        );

        jBsalvar.setText("Salvar");
        jBsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBsalvarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDlayoutLayout = new javax.swing.GroupLayout(jDlayout.getContentPane());
        jDlayout.getContentPane().setLayout(jDlayoutLayout);
        jDlayoutLayout.setHorizontalGroup(
            jDlayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jDlayoutLayout.createSequentialGroup()
                .addComponent(jBsalvar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jDlayoutLayout.setVerticalGroup(
            jDlayoutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDlayoutLayout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBsalvar)
                .addGap(36, 36, 36))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 0, 0));
        setUndecorated(true);
        setResizable(false);

        jPbackground.setBackground(new java.awt.Color(255, 51, 51));
        jPbackground.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setForeground(new java.awt.Color(204, 0, 0));
        jPanel3.setLayout(new javax.swing.BoxLayout(jPanel3, javax.swing.BoxLayout.LINE_AXIS));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Marcos\\Desktop\\fundo\\images.jpg")); // NOI18N

        javax.swing.GroupLayout jPimagem1Layout = new javax.swing.GroupLayout(jPimagem1);
        jPimagem1.setLayout(jPimagem1Layout);
        jPimagem1Layout.setHorizontalGroup(
            jPimagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPimagem1Layout.setVerticalGroup(
            jPimagem1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 137, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 454, Short.MAX_VALUE)
        );

        jPletreiro.setBackground(new java.awt.Color(204, 0, 0));

        jPletreiroint.setBackground(new java.awt.Color(204, 0, 0));

        jLletreirointFrase.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N

        javax.swing.GroupLayout jPletreirointLayout = new javax.swing.GroupLayout(jPletreiroint);
        jPletreiroint.setLayout(jPletreirointLayout);
        jPletreirointLayout.setHorizontalGroup(
            jPletreirointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPletreirointLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLletreirointFrase, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPletreirointLayout.setVerticalGroup(
            jPletreirointLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLletreirointFrase, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPletreiroLayout = new javax.swing.GroupLayout(jPletreiro);
        jPletreiro.setLayout(jPletreiroLayout);
        jPletreiroLayout.setHorizontalGroup(
            jPletreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPletreiroLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPletreiroint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPletreiroLayout.setVerticalGroup(
            jPletreiroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPletreiroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPletreiroint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPbackgroundLayout = new javax.swing.GroupLayout(jPbackground);
        jPbackground.setLayout(jPbackgroundLayout);
        jPbackgroundLayout.setHorizontalGroup(
            jPbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPimagem1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPbackgroundLayout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
            .addComponent(jPletreiro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPbackgroundLayout.setVerticalGroup(
            jPbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPbackgroundLayout.createSequentialGroup()
                .addComponent(jPimagem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(jPbackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addComponent(jPletreiro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jMenu1.setText("Configuração");

        jMenuItem1.setText("Carga");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Layout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenu.add(jMenu1);

        jMenu2.setText("Sair");

        jMenuItem3.setText("Sair");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenu.add(jMenu2);

        setJMenuBar(jMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPbackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:        
        DBConfigBeans dbc = new DBConfigBeans();
        jTlocalbalancabanco.setText(dbc.getDirdb());
        jTusuariobalancabanco.setText(dbc.getUser());
        jTsenhabalancabanco.setText(dbc.getPassword());
        jTlocalbanco.setText(dbc.getLocaldirdb());
        jTusuariobanco.setText(dbc.getLocaluser());
        jTsenhabanco.setText(dbc.getLocalpassword());
        jDcarga.setLocationRelativeTo(this);
        jDcarga.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        DBConfigBeans dbc = new DBConfigBeans();
        jRTabela1.setSelected(dbc.isTabela1());
        jRTabela2.setSelected(dbc.isTabela2());
        jRTabela3.setSelected(dbc.isTabela3());
        jRTabela4.setSelected(dbc.isTabela4());
        jRSequencial.setSelected(dbc.isSequencial());
        jRletreiro.setSelected(dbc.isLetreiro());
        jSLinhaTabela.setValue((Integer) dbc.getLinhatabela());
        jDlayout.setLocationRelativeTo(this);
        jDlayout.setVisible(true);

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        DBConfigBeans dbc = new DBConfigBeans();
        dbc.setDirdb(jTlocalbalancabanco.getText());
        dbc.setUser(jTsenhabalancabanco.getText());
        dbc.setPassword(jTsenhabalancabanco.getText());
        dbc.setLocaldirdb(jTlocalbanco.getText());
        dbc.setLocalpassword(jTsenhabanco.getText());
        dbc.setLocaluser(jTusuariobanco.getText());
        try {
            new DBConfig().createConfig(dbc);
            jDcarga.setVisible(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Salvar" + ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTlocalbalancabancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTlocalbalancabancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTlocalbalancabancoActionPerformed

    private void jTlocalbancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTlocalbancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTlocalbancoActionPerformed

    private void jTsenhabancoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTsenhabancoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTsenhabancoActionPerformed

    private void jBsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBsalvarActionPerformed
        // TODO add your handling code here:
        DBConfigBeans dbc = new DBConfigBeans();
        dbc.setTabela1(jRTabela1.isSelected());
        dbc.setTabela2(jRTabela2.isSelected());
        dbc.setTabela3(jRTabela3.isSelected());
        dbc.setTabela4(jRTabela4.isSelected());
        dbc.setSequencial(jRSequencial.isSelected());
        dbc.setLetreiro(jRletreiro.isSelected());
        dbc.setLinhatabela((Integer) jSLinhaTabela.getValue());
        try {
            new DBConfig().createConfig(dbc);
            jDlayout.setVisible(false);
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(this, "Erro ao Salvar" + ex);
        }
        if (jPanel3.getComponentCount() > 0) {
            for (int i = 0; i < jPanel3.getComponentCount(); i++) {
                jPanel3.getComponent(i).setVisible(false);
            }
            inicializaGrade();
        }

    }//GEN-LAST:event_jBsalvarActionPerformed

    private void jRletreiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRletreiroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRletreiroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GroupTabelas;
    private javax.swing.JButton jBsalvar;
    private javax.swing.JButton jButton1;
    private javax.swing.JDialog jDcarga;
    private javax.swing.JDialog jDlayout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLletreirointFrase;
    private javax.swing.JMenuBar jMenu;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPbackground;
    private javax.swing.JPanel jPimagem1;
    private javax.swing.JPanel jPletreiro;
    private javax.swing.JPanel jPletreiroint;
    private javax.swing.JRadioButton jRSequencial;
    private javax.swing.JRadioButton jRTabela1;
    private javax.swing.JRadioButton jRTabela2;
    private javax.swing.JRadioButton jRTabela3;
    private javax.swing.JRadioButton jRTabela4;
    private javax.swing.JRadioButton jRletreiro;
    private javax.swing.JSpinner jSLinhaTabela;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTlocalbalancabanco;
    private javax.swing.JTextField jTlocalbanco;
    private javax.swing.JTextField jTsenhabalancabanco;
    private javax.swing.JTextField jTsenhabanco;
    private javax.swing.JTextField jTusuariobalancabanco;
    private javax.swing.JTextField jTusuariobanco;
    // End of variables declaration//GEN-END:variables

    private void inicializarAtalhos() {
        KeyStroke keyStrokeJBalterar = KeyStroke.getKeyStroke(KeyEvent.VK_F3, 0);
        String actionNameJBalterar = "TECLA_F3";
        InputMap inputMapJBalterar = jPanel6.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);

        inputMapJBalterar.put(keyStrokeJBalterar, actionNameJBalterar);
        ActionMap actionMapJBMARCA = jPanel6.getActionMap();
        actionMapJBMARCA.put(actionNameJBalterar, ativaMenu);

        //Atalho enter
        InputMap inputMapJBenter = this.jPimagem1.getRootPane().getInputMap(JComponent.HEIGHT);
        inputMapJBenter.put(KeyStroke.getKeyStroke(KeyEvent.VK_F2, 0), "forward");
        this.jPimagem1.getRootPane().setInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW, inputMapJBenter);
        this.jPimagem1.getRootPane().getActionMap().put("forward", new AbstractAction() {
            private static final long serialVersionUID = 1L;

            @Override
            public void actionPerformed(ActionEvent e) {
                System.err.print("Atalho 2");
                if (jMenu.isVisible()) {
                    jMenu.setVisible(false);
                } else {
                    jMenu.setVisible(true);
                }
            }

        });

    }

    Action ativaMenu = new AbstractAction() {  //funcao da acao do botao
        @Override
        public void actionPerformed(ActionEvent e) {
            //simula o click no botão              
            if (jMenu.isVisible()) {
                jMenu.setVisible(false);
            } else {
                jMenu.setVisible(true);
            }
        }
    };

    private void inicializaGrade() {
        DBConfigBeans dbc = new DBConfigBeans();
        Integer tabelas = 0;
        if (dbc.isTabela1()) {
            tabelas = 1;
        } else if (dbc.isTabela2()) {
            tabelas = 2;
        } else if (dbc.isTabela3()) {
            tabelas = 3;
        } else if (dbc.isTabela4()) {
            tabelas = 4;
        }
        ViewLayoutTabelas view = new ViewLayoutTabelas(tabelas);
        view.setSize(300, 300);
        jPanel3.add(view);
        jPanel3.repaint();
        jPanel3.validate();
        if (dbc.isLetreiro()) {
            jPletreiro.setVisible(true);
            threadletreiro("teste");
        } else {
            jPletreiro.setVisible(false);
        }
    }

    private void threadletreiro(final String frase) {                       
        x=jPletreiro.getSize().width; 
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ViewPrincipal.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    jLletreirointFrase.setText(frase.toUpperCase());
                    jPletreiroint.setLocation(x--, jPletreiroint.getY());
                    System.err.println("\n" + jPletreiroint.getLocation());
                }
            }
        }).start();
    }

}
